/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/admin/tenants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Los tenants, para elegir cuál se compone */
        get: operations["listTenants"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/tenants/{tenantId}/layouts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Las versiones de layout del tenant · borrador y publicada */
        get: operations["listLayouts"];
        put?: never;
        /**
         * Crear un borrador vacío
         * @description Responde **201**, no 200. `version_id` es opcional al crear: se puede
         *     poner al publicar.
         */
        post: operations["createDraft"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/tenants/{tenantId}/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Las métricas del tenant, SIN filtrar por rol
         * @description La diferencia con `/config/catalog` es esa: acá no se aplica
         *     `hidden_metric_ids`, porque quien compone tiene que poder asignar una
         *     métrica que después un rol no verá.
         *
         *     Devuelve el mismo `CatalogMetric` que la consola — **ese struct SÍ tiene
         *     etiquetas `json:`**.
         */
        get: operations["adminCatalog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/layouts/{layoutId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** El layout con sus pestañas y paneles · para el builder */
        get: operations["getLayout"];
        /**
         * Reemplazar las pestañas y los paneles
         * @description **Es un REEMPLAZO COMPLETO**, no un parche: se envía el layout entero y
         *     lo que no venga se borra.
         *
         *     **Solo un `draft` es editable** — sobre uno publicado responde 409.
         *
         *     El cuerpo va en **snake_case**, a diferencia de la respuesta.
         */
        put: operations["updateLayout"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/layouts/{layoutId}/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Validar la composición contra la tabla `blocks`
         * @description **Responde 200 aunque la composición sea inválida**: el resultado va en
         *     `data.valid` y `data.errors`. Un 200 no quiere decir que el layout esté
         *     bien — quiere decir que la validación corrió.
         */
        post: operations["validateLayout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/layouts/{layoutId}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Publicar la versión
         * @description **Demota el layout publicado anterior del tenant a `draft`.** Solo hay
         *     uno publicado por tenant, así que publicar cambia lo que ve la consola en
         *     su próxima carga.
         *
         *     Rechaza con **422** si hay paneles inválidos.
         */
        post: operations["publishLayout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Envelope: {
            /** @enum {boolean} */
            success: true;
        };
        /** @description El mismo de la consola · `error` es una CADENA. */
        ErrorResponse: {
            /** @enum {boolean} */
            success: false;
            error: string;
        };
        /** @description `ports.TenantPublicOption` · SÍ tiene etiquetas `json:`. */
        TenantOption: {
            /** Format: uuid */
            id: string;
            name: string;
        };
        /**
         * @description `domain.DDCatalogMetric`, el mismo de `/config/catalog`. **Con etiquetas
         *     `json:`**, así que sale en snake_case. Ver `synapse-console-wire.yaml`
         *     para el detalle de cada campo — no se duplica acá.
         */
        CatalogMetric: {
            /** Format: uuid */
            id: string;
            key: string;
            name: string;
            shape: string;
            family: string;
            layer: string;
            source: string;
            base: string;
            min_grain: string;
            catalog_version: number;
        } & {
            [key: string]: unknown;
        };
        /**
         * @description `domain.DDLayoutVersion`, **serializado SIN etiquetas `json:`**. Las
         *     claves son los nombres de los campos de Go.
         *
         *     `Tenant` viaja porque el struct lo declara y no lleva `json:"-"`. Hoy
         *     llega en cero —nadie hace `Preload`— y por eso no se declaran sus
         *     campos acá: **lo que sea que traiga, el front no lo lee**.
         */
        LayoutVersion: {
            /** Format: uuid */
            ID: string;
            /** Format: uuid */
            TenantID: string;
            /**
             * @description Solo uno `published` por tenant. Publicar demota al anterior.
             * @enum {string}
             */
            Status: "draft" | "published";
            /** @description Etiqueta legible. Cadena vacía si nunca se puso. */
            VersionID: string;
            /** Format: date-time */
            PublishedAt?: string | null;
            /** Format: date-time */
            CreatedAt?: string;
            /** Format: date-time */
            UpdatedAt?: string;
            /** @description **No se lee.** Ver el aviso de la cabecera del archivo. */
            Tenant?: {
                [key: string]: unknown;
            };
        };
        /** @description `domain.DDTab`, también sin etiquetas `json:`. */
        LayoutTab: {
            /** Format: uuid */
            ID: string;
            /** Format: uuid */
            LayoutVersionID: string;
            Name: string;
            /**
             * @description La pregunta operativa. Cadena vacía si no se puso — **y el producto
             *     dice que una pestaña que no contesta una pregunta no se compone**,
             *     así que el builder no la deja vacía aunque el backend sí.
             */
            OperationalQuestion?: string;
            SortOrder: number;
            /** @description Vacío significa «la ven todos los roles». */
            RoleIDs?: string[];
            /** Format: date-time */
            CreatedAt?: string;
            /** Format: date-time */
            UpdatedAt?: string;
        };
        /**
         * @description `domain.DDPanel`, sin etiquetas `json:`. **Ojo con `Type`**: en la base la
         *     columna es `block_type` y acá el campo es `Type`.
         */
        LayoutPanel: {
            /** Format: uuid */
            ID: string;
            /** Format: uuid */
            TabID: string;
            /** Format: uuid */
            MetricID: string;
            Type: string;
            ColStart: number;
            ColSpan: number;
            RowSpan: number;
            /** @description Los nombres van en inglés · ver `PARAMS` del adaptador. */
            Options?: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            CreatedAt?: string;
            /** Format: date-time */
            UpdatedAt?: string;
        };
        /**
         * @description `ports.DDLayoutDetail`. **Las dos claves de afuera SÍ tienen etiqueta**
         *     —`layout`, `tabs`— y lo de adentro no. Esa mezcla es toda la deuda.
         */
        LayoutDetail: {
            layout: components["schemas"]["LayoutVersion"];
            tabs: {
                tab: components["schemas"]["LayoutTab"];
                panels: components["schemas"]["LayoutPanel"][];
            }[];
        };
        /**
         * @description `ports.DDLayoutUpdateRequest`. **El cuerpo va en snake_case y la respuesta
         *     en PascalCase**: el builder manda una forma y recibe otra.
         */
        LayoutUpdateRequest: {
            tabs: components["schemas"]["TabInput"][];
        };
        TabInput: {
            /**
             * Format: uuid
             * @description Omitir —o mandar el UUID cero— **genera una pestaña nueva**. Mandar un
             *     UUID existente conserva el id al reemplazar el contenido. Es la
             *     diferencia entre editar y recrear, y no la avisa nada.
             */
            id?: string;
            name: string;
            operational_question?: string;
            /** @description Default si viene 0: el índice del arreglo + 1. */
            sort_order?: number;
            role_ids?: string[];
            panels?: components["schemas"]["PanelInput"][];
        };
        PanelInput: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            metric_id: string;
            type: string;
            /** @description Default si viene 0: 1. */
            col_start?: number;
            /** @description Default si viene 0: 3. */
            col_span?: number;
            /** @description Default si viene 0: 4. */
            row_span?: number;
            options?: {
                [key: string]: unknown;
            };
        };
        /** @description `ports.DDLayoutValidationResult` · SÍ tiene etiquetas `json:`. */
        ValidationResult: {
            valid: boolean;
            errors: components["schemas"]["ValidationIssue"][];
        };
        /**
         * @description Trae `tab_id` y `panel_id` cuando aplica, **así que el error se puede
         *     mostrar SOBRE el panel** y no en una lista al pie.
         */
        ValidationIssue: {
            /** Format: uuid */
            tab_id?: string | null;
            /** Format: uuid */
            panel_id?: string | null;
            field?: string;
            message: string;
        };
    };
    responses: {
        /** @description Identificador mal formado */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description El JWT no es de rol `admin` */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description No existe */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Composición inválida */
        Unprocessable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        tenantId: string;
        layoutId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listTenants: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista de tenants */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["TenantOption"][];
                    };
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    listLayouts: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: components["parameters"]["tenantId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Versiones */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["LayoutVersion"][];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
        };
    };
    createDraft: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: components["parameters"]["tenantId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** @example borrador-f4 */
                    version_id?: string;
                };
            };
        };
        responses: {
            /** @description El borrador creado */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["LayoutVersion"];
                    };
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    adminCatalog: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: components["parameters"]["tenantId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Catálogo completo del tenant */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["CatalogMetric"][];
                    };
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    getLayout: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                layoutId: components["parameters"]["layoutId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Detalle del layout */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["LayoutDetail"];
                    };
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updateLayout: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                layoutId: components["parameters"]["layoutId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LayoutUpdateRequest"];
            };
        };
        responses: {
            /** @description El layout guardado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["LayoutDetail"];
                    };
                };
            };
            /** @description El layout está publicado y no se puede editar */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            422: components["responses"]["Unprocessable"];
        };
    };
    validateLayout: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                layoutId: components["parameters"]["layoutId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Resultado de la validación */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["ValidationResult"];
                    };
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    publishLayout: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                layoutId: components["parameters"]["layoutId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** @example v3 */
                    version_id?: string;
                };
            };
        };
        responses: {
            /** @description La versión publicada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["LayoutVersion"];
                    };
                };
            };
            422: components["responses"]["Unprocessable"];
        };
    };
}
