/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/admin/tenants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Los tenants, para elegir cuál se compone */
        get: operations["listTenants"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/tenants/{tenantId}/layouts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Las versiones de layout del tenant · borrador y publicada */
        get: operations["listLayouts"];
        put?: never;
        /**
         * Crear un borrador vacío
         * @description Responde **201**, no 200. `version_id` es opcional al crear: se puede
         *     poner al publicar.
         */
        post: operations["createDraft"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/tenants/{tenantId}/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Las métricas del tenant, SIN filtrar por rol
         * @description La diferencia con `/config/catalog` es esa: acá no se aplica
         *     `hidden_metric_ids`, porque quien compone tiene que poder asignar una
         *     métrica que después un rol no verá.
         *
         *     Devuelve el mismo `CatalogMetric` que la consola — **ese struct SÍ tiene
         *     etiquetas `json:`**.
         */
        get: operations["adminCatalog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/layouts/{layoutId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** El layout con sus pestañas y paneles · para el builder */
        get: operations["getLayout"];
        /**
         * Reemplazar las pestañas y los paneles
         * @description **Es un REEMPLAZO COMPLETO**, no un parche: se envía el layout entero y
         *     lo que no venga se borra.
         *
         *     **Solo un `draft` es editable** — sobre uno publicado responde 409.
         *
         *     El cuerpo va en **snake_case**, a diferencia de la respuesta.
         */
        put: operations["updateLayout"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/layouts/{layoutId}/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Validar la composición contra la tabla `blocks`
         * @description **Responde 200 aunque la composición sea inválida**: el resultado va en
         *     `data.valid` y `data.errors`. Un 200 no quiere decir que el layout esté
         *     bien — quiere decir que la validación corrió.
         */
        post: operations["validateLayout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/tenants/{tenantId}/roles/composition": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Los roles del cliente, con su composición
         * @description **LA TOMARON, y en la ruta que propusimos** · B4.8 · medida el 2026-09-26.
         *     Acá decía «no la sirve el servicio desplegado», y eso venció el
         *     2026-09-25: `GET .../roles/composition` responde 200. La colisión con su
         *     propio `GET .../roles` se resolvió moviendo el NUESTRO, y su ruta quedó
         *     intacta.
         *
         *     `user_count` viaja en el listado a propósito: es lo que decide si el rol
         *     se puede borrar, y la pantalla tiene que poder decirlo **antes** de
         *     ofrecer el botón, no después de un 409.
         */
        get: operations["listRoles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/tenants/{tenantId}/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Crear un rol
         * @description **409 si ya existe un rol con ese nombre en el cliente.** El índice único
         *     es `(tenant_id, name)` y el servicio pregunta antes para poder decir qué
         *     pasó en vez de devolver el error de Postgres como un 500.
         */
        post: operations["createRole"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/roles/{roleId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Editar un rol
         * @description **Escribe cuatro columnas: `name`, `tab_ids`, `hidden_metric_ids` y
         *     `layout_overrides`.** `tenant_id` no se toca: un rol no cambia de cliente.
         *
         *     `layout_overrides` ausente se escribe como `{}`, no se deja intacto.
         */
        put: operations["updateRole"];
        post?: never;
        /**
         * Borrar un rol
         * @description **204 sin cuerpo.** Y **409 con la razón y el número si tiene usuarios
         *     asignados** — no borra en cascada: dejaría usuarios sin rol, que es un
         *     usuario que no puede entrar a ninguna pestaña.
         */
        delete: operations["deleteRole"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/layouts/{layoutId}/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * El layout como lo vería un rol
         * @description ── **YA LA SIRVE EL SERVICIO** · medido el 2026-09-26 ─────────────────
         *
         *     Acá decía «no la sirve el servicio desplegado, escrita en el fork». La
         *     tomaron en `8633b10` y **responde 200**. Con eso el fork queda absorbido
         *     entero: era su última parte pendiente.
         *
         *     **Y resolvieron la colisión de diseño como propusimos.** `168a761` había
         *     puesto una compuerta que comparaba el rol SIMULADO contra «es admin», así
         *     que un borrador se rechazaba siempre; hoy `dd_config_service.go:424`
         *     compara `sel.CallerRole` —quién pregunta— y el lente es otra cosa.
         *
         *     ── **EL PARÁMETRO ES `role_id`, NO `roleId`** ─────────────────────────
         *
         *     Medido: `?roleId=` devuelve **400 · «role_id es requerido y debe ser un
         *     uuid»**, y `?role_id=` devuelve 200. Nuestro cliente mandaba `roleId`,
         *     así que F4.12 **nunca pudo haber funcionado** contra el servicio real.
         *
         *     **No se deduce del resto del cable**: `/config/tabs/{tabId}` usa
         *     `layoutId` y `dashboardId` en camelCase, en el mismo binario. Dos
         *     convenciones, y la única forma de saber cuál es cuál es leer el handler.
         *
         *     **Ojo con un comentario SUYO que es falso**: dice «es lo que hace `GetTab`
         *     cuando el admin manda `?roleId=`». `GetTab` toma el rol **sólo del
         *     token**, vía `resolveTenantAndRole` → `c.Get("role_id")`, y **ignora
         *     cualquier parámetro de rol**. `?roleId=` ahí da 200 porque se descarta,
         *     no porque se aplique.
         *
         *     **Viene SIN paneles**, medido: `tabs[]` trae `id`, `name`,
         *     `operational_question` y `sort_order`, y nada más. Con eso alcanza para
         *     «qué pestañas ve el CEO y cuáles el Planner»; **no alcanza** para ver qué
         *     paneles ve, que es lo que `hidden_metric_ids` filtra. Y no hay otra ruta
         *     que lo dé, porque `GetTab` no acepta lente. Es la razón escrita de por
         *     qué F4.12 no trae cifras.
         *
         *     Un `role_id` de otro tenant devuelve **404 y no 403**: un 403 confirmaría
         *     que el rol existe.
         */
        get: operations["previewLayout"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/layouts/{layoutId}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Publicar la versión
         * @description **Demota el layout publicado anterior del tenant a `draft`.** Solo hay
         *     uno publicado por tenant, así que publicar cambia lo que ve la consola en
         *     su próxima carga.
         *
         *     Rechaza con **422** si hay paneles inválidos.
         */
        post: operations["publishLayout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/layouts/{layoutId}/revert": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Volver a una versión anterior
         * @description **B4.2 · llegó con `5924bf2b`.** Toma la versión destino —`to_layout_id`,
         *     o por defecto el `previous_layout_id` de la última publicación—, **copia**
         *     sus pestañas y paneles a un draft nuevo, lo valida contra el catálogo
         *     actual y lo publica.
         *
         *     **Nunca se reactiva una versión archivada**, y es la decisión que hace
         *     auditable el historial: la versión a la que se volvió sigue `archived`, y
         *     en `GET /admin/layouts/{id}/publications` la vuelta aparece como una
         *     publicación más con `action: "rollback"`, su actor y su
         *     `previous_layout_id`.
         *
         *     Por eso también **puede fallar con 422**: una versión vieja puede ya no
         *     validar contra el catálogo de hoy.
         *
         *     ── **LO QUE SE MIDIÓ Y LO QUE NO** ────────────────────────────────────
         *
         *     **Medidas, las dos compuertas**, sobre un tenant con un solo layout — que
         *     es justo lo que deja probarlas sin tocar nada:
         *
         *         POST …/revert  {}                    → 409 CONFLICT_NO_PREVIOUS
         *         POST …/revert  {to_layout_id: él}    → 409 CONFLICT_REVERT_SELF
         *
         *     Las dos con mensaje redactado y **en español**, que es lo que muestra que
         *     los dos mensajes en inglés del cable de consola son handlers sueltos y no
         *     una política.
         *
         *     **NO medida, la reversión en sí**: copia y publica, así que cambiaría el
         *     layout que la consola está sirviendo. El `200` de abajo sale de su
         *     documento y no de una respuesta vista — se mide cuando haya una segunda
         *     versión que no sea la de nadie.
         */
        post: operations["revertLayout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/tenants/{tenantId}/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Los agentes configurados para el cliente
         * @description **Transcrita el 2026-09-21 desde `82da946`**, leyendo
         *     `internal/core/ports/agent.go` —`AgentAdminDTO`— y
         *     `internal/adapters/handler/agent_handler.go`.
         *
         *     **`AgentAdminDTO` SÍ tiene etiquetas `json:` y sale en snake_case.** Al
         *     transcribirla era la excepción —el resto de admin serializaba structs de
         *     dominio en PascalCase— y desde `8633b10` es la regla: B4.10 les puso
         *     etiquetas a los tres structs de layout. No se deduce del patrón: se leyó,
         *     las dos veces.
         *
         *     **Nunca incluye credenciales** — lo dice el comentario del DTO y lo
         *     confirma la lista de campos. Lo que sí trae y **§7.3 prohíbe mostrar**
         *     es `snowflake_db`, `snowflake_schema` y `warehouse`: «ni base, ni rol
         *     técnico, ni grants, ni warehouse». Se transcriben porque describir el
         *     cable no es pintarlo.
         *
         *     **Devuelve también los inactivos.** `is_active` es una baja lógica que
         *     alguien apretó, no una verificación de que el acceso funcione.
         */
        get: operations["listAgents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Todos los usuarios de la plataforma, con su cliente
         * @description ── **CIERRA EL HUECO DE ALCANCE DE A3** · B4.17, medida el 2026-09-26 ──
         *
         *     El dibujo de A3 declara `ALCANCE · PLATAFORMA` y su resumen dice «17
         *     usuarios · 2 clientes con usuarios». Hasta `6e521cc` la única ruta era
         *     **por cliente**, y `UserList` lo declaraba como hueco con su razón: «no se
         *     compensa pidiendo N veces la ruta — un total armado acá se leería como un
         *     número de plataforma y sería una suma nuestra».
         *
         *     **Esta ruta lo da del lado del servidor**, y con `tenant_name` por usuario,
         *     que es la columna `CLIENTE` del dibujo.
         *
         *     **`total` y `tenants` los cuenta el servicio**, no nosotros. Es la
         *     diferencia que la razón del hueco señalaba: si un cliente fallara, un
         *     total nuestro bajaría sin decirlo.
         */
        get: operations["listAllUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/tenants/{tenantId}/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Los usuarios del cliente, con su rol
         * @description **Transcrita el 2026-09-25 desde `1e080ee`**, leyendo la respuesta del
         *     servicio corriendo campo por campo.
         *
         *     **Va colgada del tenant, y A3 está dibujada con alcance PLATAFORMA** —su
         *     resumen dice «17 usuarios · 2 clientes con usuarios»—. La diferencia se
         *     declara en la pantalla; no se compensa pidiendo N veces esta ruta, que
         *     daría un número que parece de plataforma y es una suma nuestra.
         *
         *     **`/admin/users` NO existe** y da 404: la lista es por cliente.
         */
        get: operations["listUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/tenants/{tenantId}/feeds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Las fuentes de datos del cliente y su salud
         * @description **Transcrita el 2026-09-25 desde `1e080ee`**, leyendo la respuesta del
         *     servicio corriendo campo por campo.
         *
         *     Es la ruta que A5 necesita, y se pidió **como ruta y no como un campo
         *     `estado` en la métrica**: el estado de una métrica se DERIVA de
         *     `frescura > cadencia × tolerancia`, y guardarlo crearía dos fuentes para
         *     el mismo hecho que se separan en el primer feed atrasado.
         *
         *     **`status` llega igual y el front NO lo usa.** Está acá porque el
         *     servicio lo manda, no porque la pantalla lo lea · §PEN:A5, al pie: «el
         *     estado no se escribe, se deriva».
         */
        get: operations["listFeeds"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description El sobre de `GET /admin/users` · B4.17 · medido el 2026-09-26.
         *
         *     **No es un arreglo desnudo**, al revés de casi todo el resto del cable:
         *     trae los dos conteos que el dibujo de A3 pinta en su resumen.
         */
        UsersPlatform: {
            /** @description Usuarios en toda la plataforma. **Lo cuenta el servicio.** */
            total: number;
            /**
             * @description Clientes **con al menos un usuario**, que es lo que el dibujo dice —«2
             *     clientes con usuarios»— y no la cantidad de clientes.
             */
            tenants: number;
            users: components["schemas"]["User"][];
        };
        /**
         * @description Un usuario del cliente · `1e080ee`.
         *
         *     **Lo que A3 dibuja y esto NO trae**, declarado y no inventado: el estado
         *     de INVITACIÓN PENDIENTE —`is_active` sólo distingue activo de
         *     suspendido—, quién dio de alta —el dibujo pone «POR M. BENÍTEZ»— y la
         *     paginación, que la ruta no ofrece.
         */
        User: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tenant_id: string;
            /** @example Under Armour México */
            tenant_name?: string;
            email: string;
            first_name: string;
            last_name: string;
            /** @description Puede venir vacío */
            phone?: string;
            /** @description El nombre del rol · admin, planner */
            role: string;
            /**
             * Format: uuid
             * @description Para enlazar con la ficha
             */
            role_id: string;
            /**
             * Format: date-time
             * @description **`null` cuando nunca entró**, que el dibujo pinta como «Nunca». No
             *     es un error ni un cero.
             */
            last_login_at?: string | null;
            /**
             * @description Activo o suspendido. **No distingue la invitación pendiente**, que el
             *     dibujo declara como un tercer estado.
             */
            is_active: boolean;
            /**
             * Format: date-time
             * @description El alta
             */
            created_at: string;
        };
        /**
         * @description Una fuente de datos del tenant · `1e080ee`.
         *
         *     **Los cuatro campos que importan son `cadence_hours`,
         *     `tolerance_factor`, `freshness_hours` y `last_load_at`**: de ahí sale el
         *     estado, derivado. El resto es lo que la tabla de §PEN:A5 pinta.
         *
         *     **`layer` NO llega**, y el dibujo la pone como columna. Declarado como
         *     hueco en F4.24 en vez de inventarlo.
         */
        Feed: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tenant_id: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
            key: string;
            /** @description El nombre que ve una persona */
            name: string;
            /** @description Puede venir vacío · una fuente sin tabla Gold todavía */
            gold_table?: string;
            /** @description Cada cuántas horas se espera una carga */
            cadence_hours: number;
            /** @description El múltiplo de la cadencia que se tolera */
            tolerance_factor: number;
            /** @description Los textos de `source` de las métricas que caen en esta fuente */
            source_labels?: string[];
            /**
             * Format: date-time
             * @description **`null` cuando nunca cargó**, que es como llegan las cuatro del
             *     tenant de prueba el 2026-09-25. No es un error: es una fuente sin
             *     Gold todavía.
             */
            last_load_at?: string | null;
            /** Format: date-time */
            last_load_checked_at?: string | null;
            rows_processed?: number | null;
            /** @description Las que fallaron la validación Silver→Gold */
            rows_failed?: number | null;
            /** @description Horas desde la última carga. `null` si nunca cargó */
            freshness_hours?: number | null;
            /**
             * @description **El front NO lo lee.** Lo manda el servicio y la pantalla deriva el
             *     suyo · §PEN:A5. Se transcribe para que la próxima persona que lo vea
             *     sepa que la omisión es deliberada.
             */
            status?: string;
            metric_count: number;
            /** @description Las métricas que dependen de esta fuente */
            metric_keys: string[];
            is_active: boolean;
        };
        Envelope: {
            /** @enum {boolean} */
            success: true;
        };
        /** @description El mismo de la consola · `error` es una CADENA. */
        ErrorResponse: {
            /** @enum {boolean} */
            success: false;
            error: string;
            /**
             * @description **B0.4 · llegó con `5924bf2b`**, y acá es donde más rinde: las rutas
             *     de administración son las que tienen reglas de negocio con estado.
             *
             *     `FAMILIA_DETALLE`, y **se decide por la familia** — ellos suman
             *     detalles sin avisar. Ver el cable de consola para el juego completo.
             *
             *     Los de acá, declarados por ellos: `CONFLICT_NOT_DRAFT`,
             *     `VALIDATION_LAYOUT`, `VALIDATION_CHAT_SUGGESTIONS`,
             *     `NOT_FOUND_LAYOUT`, `NOT_FOUND_ROLE`, `AUTH_DRAFT_PREVIEW`,
             *     `VALIDATION_THEME`, `VALIDATION_DASHBOARD_NOT_VISIBLE`,
             *     `CONFLICT_NO_PREVIOUS`, `CONFLICT_REVERT_SELF`,
             *     `NOT_FOUND_REVERT_TARGET`, `VALIDATION_REVERT_TARGET`.
             *
             *     **Medidos acá**: `AUTH_FORBIDDEN` con token de planner,
             *     `CONFLICT_NO_PREVIOUS` y `CONFLICT_REVERT_SELF` en el revert.
             * @example CONFLICT_NO_PREVIOUS
             * @example AUTH_FORBIDDEN
             * @example VALIDATION_LAYOUT
             */
            code: string;
        };
        /**
         * @description `ports.TenantAdminOption` · snake_case.
         *
         *     ── **B4.1 LLEGÓ** · 2026-09-26, medido contra `8633b10` ────────────────
         *
         *     Acá había dos campos, `id` y `name`, y eso era el bloqueo de **A1 · la
         *     banda de clientes**: el dibujo pide cinco columnas y la ruta daba el
         *     nombre. Estaba escrita en nuestro fork —`8c03132`— esperando que la
         *     tomaran, y la escribieron ellos.
         *
         *     **El nombre del esquema ya no describe lo que es** —una «opción» de un
         *     selector— pero no se renombra: `admin-generated.ts` se genera de acá y el
         *     renombre tocaría los consumidores sin cambiar un solo campo.
         *
         *     **Dos de las cinco columnas llegan en `null`**, y desde el 2026-09-26
         *     por razones DISTINTAS · `docs/DECISIONES-2026-09-26-estado-y-vertical.md`.
         *     Hasta acá compartían una —«esperan que definamos sus valores»— y ya no:
         *
         *       · `status` **está decidido**: `ACTIVO`, `PILOTO`, `SUSPENDIDO`. Los dos
         *         primeros los dibuja el `.pen` en A1, así que son transcripción. Ahora
         *         falta **la columna**: su `Tenant` de `internal/core/domain/tenant.go`
         *         no la tiene, medido contra `6e595e3`.
         *
         *         **Acá NO se declara el enum, a propósito.** Este archivo transcribe
         *         lo que el servicio emite, y emite `null`; declararlo sería afirmar
         *         una forma que nadie manda. El día que el valor llegue, el enum se
         *         cierra en el ADAPTADOR, que es donde ya se cierran `shape`, `family`
         *         y `layer` — el cable los trae como `string` libre.
         *
         *         Y `SUSPENDIDO` no es sólo una columna: es una compuerta en el login,
         *         que exceptúa a los super-admins.
         *
         *       · `vertical` **se retiró**. §3.5 de `design.md` declara `vertical` Y
         *         `plantillaOrigen` —dos campos— y el `.pen` dibuja el par en la misma
         *         celda de A1: `Retail · apparel` sobre `retail_apparel_v2`. Es la
         *         cabeza de la herencia de §3.4, que no existe de ninguno de los dos
         *         lados. **Su `null` no es un pendiente de nadie.**
         */
        TenantOption: {
            /** Format: uuid */
            id: string;
            name: string;
            /**
             * @description **La forma corta** · llegó en `f70cec2` con `tenant.label` del cable
             *     de consola, y acá se transcribió tarde: lo encontró `npm run humo`
             *     el 2026-09-28, no una lectura.
             *
             *     **Y acá SÍ puede venir vacía**, a diferencia de `/config/me`, donde
             *     el servicio la hace caer a `name`. Medido ese día: el tenant
             *     sembrado la trae en `""`. Quien la pinte cae a `name` — es lo que
             *     hace A1.
             * @example UA México
             */
            label: string;
            /** @example es-CO */
            locale: string;
            /** @example COP */
            currency: string;
            /** @example America/Bogota */
            timezone: string;
            /**
             * @description Usuarios ACTIVOS del tenant. **Cero es un valor válido y no un
             *     hueco**: un cliente recién creado no tiene usuarios hasta que alguien
             *     acepte la invitación.
             */
            user_count: number;
            /**
             * Format: date-time
             * @description `null` si nunca se publicó un layout.
             */
            last_published_at?: string | null;
            /**
             * @description El PEOR de los feeds del tenant, ya reducido por el servicio. Vale
             *     `unknown` cuando ningún feed cargó nunca — que es distinto de estar
             *     vencido, y por eso no se colapsa con él.
             *
             *     **Los tres valores se leyeron de `dashboard.FeedStatus`**, no se
             *     dedujeron: acá había `examples: ['unknown', 'ok', 'late', 'stale']`
             *     con `ok` y `late` INVENTADOS, escritos el 2026-09-26 mirando una
             *     respuesta que sólo traía `unknown`. La pantalla mostró `fresh` y ahí
             *     se fue a leer el código.
             *
             *     **Y el orden importa**: `WorstStatus` rankea `stale > unknown >
             *     fresh`, o sea que **no saber es peor que estar al día**. Es una
             *     decisión de producto y no un detalle: un cliente cuyas fuentes nunca
             *     cargaron no se presenta como sano.
             * @enum {string}
             */
            worst_feed_status?: "fresh" | "unknown" | "stale";
            /**
             * @description Horas desde la última carga del peor feed. **`null` es «nunca cargó»
             *     y 0 es «recién»** — la misma distinción que `FeedHealth` ya sostiene
             *     del lado nuestro, y confundirlas pinta un feed muerto como sano.
             */
            worst_feed_freshness_hours?: number | null;
            /** @description `null` hasta que definamos los valores · pedido abierto. */
            status?: string | null;
            /** @description `null` hasta que definamos los valores · pedido abierto. */
            vertical?: string | null;
            /** Format: date-time */
            created_at: string;
        };
        /**
         * @description `domain.DDCatalogMetric`, el mismo de `/config/catalog`. **Con etiquetas
         *     `json:`**, así que sale en snake_case. Ver `synapse-console-wire.yaml`
         *     para el detalle de cada campo — no se duplica acá.
         */
        CatalogMetric: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tenant_id: string;
            dimensions: string[];
            key: string;
            name: string;
            shape: string;
            family: string;
            layer: string;
            source: string;
            base: string;
            min_grain: string;
            catalog_version: number;
        } & {
            [key: string]: unknown;
        };
        /**
         * @description `domain.DDLayoutVersion`.
         *
         *     ── **PASÓ DE PascalCase A snake_case** · 2026-09-26, `8633b10` ─────────
         *
         *     Acá decía «serializado SIN etiquetas `json:`, las claves son los nombres
         *     de los campos de Go», y era cierto: medido el 2026-09-16 contra
         *     `82da946`, el struct **no tenía ni una etiqueta**, así que Go serializaba
         *     `ID`, `TenantID`, `Status`. `CLAUDE.md` lo registró como «el PascalCase
         *     quedó confirmado y no deducido».
         *
         *     **`8633b10` les puso etiquetas a los tres structs** —B4.10—, y con eso
         *     las claves cambiaron todas. No lo vio ninguna persona: lo encontró
         *     `humo` la primera vez que supo mirar los campos que el servicio manda y
         *     el cable no declara.
         *
         *     **Y rompía en silencio.** `src/api/admin.ts` leía quince campos en
         *     PascalCase y los quince pasaron a `undefined`; el peor no fallaba —
         *     `ESTADOS[w.Status] ?? 'borrador'` afirmaba que TODO layout era borrador,
         *     incluido el publicado.
         *
         *     `Tenant` ya no viaja: `a643cfe` le puso `json:"-"` a él y a las dos
         *     credenciales, que es el hallazgo que les reportamos el 2026-09-22.
         */
        LayoutVersion: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tenant_id: string;
            /**
             * Format: uuid
             * @description **Nuevo con el multi-dashboard.** Un tenant puede tener varios
             *     dashboards y cada layout cuelga de uno · F5.1.
             */
            dashboard_id: string;
            /**
             * @description Uno `published` por **dashboard**, no por tenant: publicar demota al
             *     anterior del mismo dashboard.
             * @enum {string}
             */
            status: "draft" | "published";
            /** @description Etiqueta legible. Cadena vacía si nunca se puso. */
            version_id: string;
            /** Format: date-time */
            published_at?: string | null;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        /**
         * @description **Nuevo el 2026-09-26.** `GET /admin/layouts/{layoutId}` pasó a devolver
         *     el dashboard al que pertenece el layout, además de `layout` y `tabs`.
         *     Es lo que deja al builder decir DE QUÉ dashboard está editando una
         *     versión, que con varios por tenant deja de ser obvio.
         */
        LayoutDashboard: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tenant_id: string;
            /** @example Overview */
            name: string;
            /** @example overview */
            slug: string;
            /** @description El que resuelve cuando el rol no declara preferencia. */
            is_default: boolean;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        /** @description `domain.DDTab`, también en snake_case desde `8633b10`. */
        LayoutTab: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            layout_version_id: string;
            name: string;
            /**
             * @description La pregunta operativa. Cadena vacía si no se puso — **y el producto
             *     dice que una pestaña que no contesta una pregunta no se compone**,
             *     así que el builder no la deja vacía aunque el backend sí.
             */
            operational_question?: string;
            sort_order: number;
            /**
             * @description **La identidad estable de la pestaña dentro del dashboard** · llegó
             *     en `f70cec2`, y es lo que faltaba para que una restricción de rol
             *     sobreviva a una publicación: `dd_tabs.id` se recrea en cada versión
             *     y `key` no.
             *
             *     Medido el 2026-09-28: la pestaña sembrada sale `overview`.
             *
             *     **Es único por versión de layout**, no por tenant.
             */
            key?: string;
            /**
             * @description Cadena vacía si no se puso. El mismo campo que el cable de consola
             *     declara en `TabMeta.icon`.
             */
            icon?: string;
            /** @description Las preguntas sugeridas de la pestaña. Arreglo vacío si no hay. */
            chat_suggestions?: string[];
            /** @description Vacío significa «la ven todos los roles». */
            role_ids?: string[];
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        /**
         * @description `domain.DDPanel`, en snake_case desde `8633b10`. **Ojo con `type`**: en la
         *     base la columna es `block_type` y acá el campo es `type`.
         */
        LayoutPanel: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tab_id: string;
            /** Format: uuid */
            metric_id: string;
            type: string;
            col_start: number;
            col_span: number;
            row_span: number;
            /**
             * @description **Cuál de los 49 gráficos dibuja el panel** · llegó en `f70cec2`,
             *     pedido por nosotros. Va **junto a `type` y no en su lugar**: el
             *     bloque decide la anatomía del cuerpo y el gráfico decide el dibujo,
             *     y 16 de los 49 sirven más de una forma.
             *
             *     Cadena vacía = el gráfico por defecto del bloque. Los doce paneles
             *     publicados salen así, medido el 2026-09-28.
             *
             *     **No lo validan contra el repertorio** —«eso es del front, que tiene
             *     los 49 y sus mínimos»—, así que un id inventado llega tal cual y el
             *     cuerpo lo declara con `UnknownPlotState`. Descartarlo en el
             *     adaptador haría que el panel cayera al gráfico por defecto sin que
             *     nadie se entere.
             */
            chart?: string;
            /** @description La nota al pie del panel. Cadena vacía si no se puso. */
            note?: string;
            /** @description Los nombres van en inglés · ver `PARAMS` del adaptador. */
            options?: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        /**
         * @description `ports.DDLayoutDetail`. **La mezcla de convenciones se terminó**: acá
         *     decía «las dos claves de afuera SÍ tienen etiqueta y lo de adentro no,
         *     esa mezcla es toda la deuda». Desde `8633b10` todo va en snake_case, y
         *     el builder ya manda y recibe la misma forma.
         */
        LayoutDetail: {
            layout: components["schemas"]["LayoutVersion"];
            dashboard?: components["schemas"]["LayoutDashboard"];
            tabs: {
                tab: components["schemas"]["LayoutTab"];
                panels: components["schemas"]["LayoutPanel"][];
            }[];
        };
        /**
         * @description `ports.DDLayoutUpdateRequest`. **La asimetría se terminó el 2026-09-26**:
         *     acá decía «el cuerpo va en snake_case y la respuesta en PascalCase, el
         *     builder manda una forma y recibe otra». Desde `8633b10` las dos van en
         *     snake_case.
         */
        LayoutUpdateRequest: {
            tabs: components["schemas"]["TabInput"][];
        };
        TabInput: {
            /**
             * Format: uuid
             * @description Omitir —o mandar el UUID cero— **genera una pestaña nueva**. Mandar un
             *     UUID existente conserva el id al reemplazar el contenido. Es la
             *     diferencia entre editar y recrear, y no la avisa nada.
             */
            id?: string;
            name: string;
            /**
             * @description Opcional. **Se SLUGIFICA, que es más de lo que su documento dice**
             *     —ahí figura «recortado»—. Medido el 2026-09-28 contra `f70cec2`:
             *     `"  MI-Clave  "` se guarda como `mi-clave`.
             *
             *     **Omitirla la deriva del nombre**, quitando los acentos:
             *     `"Visión General"` → `vision-general`.
             *
             *     **Repetida dentro del mismo layout es `422 VALIDATION_TAB_KEY`**, y
             *     el mensaje nombra las dos pestañas: `tab "Otra": la key "repe" ya la
             *     usa la pestaña "Una"`.
             */
            key?: string;
            operational_question?: string;
            /** @description Default si viene 0: el índice del arreglo + 1. */
            sort_order?: number;
            role_ids?: string[];
            panels?: components["schemas"]["PanelInput"][];
        };
        PanelInput: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            metric_id: string;
            type: string;
            /**
             * @description Opcional · **se recorta y se baja a minúsculas**. Medido el
             *     2026-09-28: `"  Waterfall  "` se guarda como `waterfall`.
             *
             *     Omitirlo deja cadena vacía, que es el gráfico por defecto del
             *     bloque. **No se valida contra el repertorio** · ver `LayoutPanel`.
             */
            chart?: string;
            /** @description Opcional · se recorta. Medido: `" una nota "` → `una nota`. */
            note?: string;
            /** @description Default si viene 0: 1. */
            col_start?: number;
            /** @description Default si viene 0: 3. */
            col_span?: number;
            /** @description Default si viene 0: 4. */
            row_span?: number;
            options?: {
                [key: string]: unknown;
            };
        };
        /** @description `ports.DDLayoutValidationResult` · SÍ tiene etiquetas `json:`. */
        ValidationResult: {
            valid: boolean;
            errors: components["schemas"]["ValidationIssue"][];
        };
        /**
         * @description Trae `tab_id` y `panel_id` cuando aplica, **así que el error se puede
         *     mostrar SOBRE el panel** y no en una lista al pie.
         */
        ValidationIssue: {
            /** Format: uuid */
            tab_id?: string | null;
            /** Format: uuid */
            panel_id?: string | null;
            field?: string;
            message: string;
        };
        /**
         * @description `ports.DDRoleDTO`, snake_case entero. Acá decía «a diferencia de
         *     `LayoutVersion` y compañía», y **B4.10 cerró esa diferencia** en
         *     `8633b10`: ya no hay dos convenciones en el cable de admin.
         */
        Role: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tenant_id: string;
            /** @example Planner */
            name: string;
            /** @description Vacío significa «ve todas las pestañas». */
            tab_ids: string[];
            /**
             * @description **Oculta, NO impide.** El servidor vuelve a verificar en
             *     `/config/catalog` y en el batch: un rol que oculta una métrica no es
             *     un rol que no pueda pedirla.
             */
            hidden_metric_ids: string[];
            /**
             * @description Por pestaña y por panel · `col_start`, `col_span`, `row_span`,
             *     `options`. **No muta el layout publicado**: `GetTab` los aplica al
             *     responder.
             */
            layout_overrides?: {
                [key: string]: unknown;
            };
            /** @description Cuántos usuarios tienen el rol. Con uno o más, borrar da 409. */
            user_count: number;
            /**
             * @description Los dashboards que el rol puede ver. Vacío significa «los que el
             *     tenant tenga por default», no «ninguno».
             */
            dashboard_ids?: string[];
            /**
             * Format: uuid
             * @description El que abre primero. **`null` es lo normal**: la resolución cae a
             *     `preferencia del usuario > rol > default del tenant`, y este campo es
             *     el escalón del medio.
             */
            default_dashboard_id?: string | null;
            /**
             * @description `DELETE /admin/roles/{roleId}` **desactiva, no borra** — medido el
             *     2026-09-26: responde 200 con `{id, is_active: false}`. La auditoría de
             *     quién vio qué se conserva.
             */
            is_active?: boolean;
        };
        RoleInput: {
            name: string;
            tab_ids?: string[];
            hidden_metric_ids?: string[];
            /** @description Ausente se escribe como `{}`: «sin overrides» es un estado, no una omisión. */
            layout_overrides?: {
                [key: string]: unknown;
            };
        };
        /**
         * @description `ports.DDPreviewResponse`.
         *
         *     ── **REESCRITO CONTRA EL SERVICIO** · 2026-09-26, `8633b10` ────────────
         *
         *     Acá estaba la forma de NUESTRO fork, y la suya es otra. Se transcribió a
         *     ciegas porque el servicio devolvía 404; ahora responde y se midió:
         *
         *       nuestra           suya
         *       `role_id`         `role.id`      · anidado
         *       `role_name`       `role.name`
         *       —                 `dashboard_id` · nuevo con el multi-dashboard
         *       —                 `status`       · para avisar que es un borrador
         *       `tabs[].tab`      `tabs[]`       · la pestaña SIN envoltorio
         *       `tabs[].panels`   —              · **no vienen**
         *       `without_payloads` —             · la ausencia no se declara
         *
         *     **La diferencia que importaba era `panels`, y se cerró** ·
         *     2026-09-28, `5924bf2b`. Hasta acá decía que su preview devolvía sólo QUÉ
         *     PESTAÑAS ve cada rol, y que eso era el techo de F4.12.
         *
         *     **Ahora `tabs[]` trae `panels[]`**, filtrados exactamente como los vería
         *     ese rol: sin las métricas de `hidden_metric_ids` y con los
         *     `layout_overrides` aplicados. Es el mismo código que sirve
         *     `GET /config/tabs/{tabId}`, así que no pueden divergir.
         *
         *     Medido con los dos lentes sobre el mismo layout publicado:
         *
         *       lente `admin`     1 pestaña · **12** paneles · `col_span` 12
         *       lente `planner`   1 pestaña · **9** paneles · `col_span` **4**
         *
         *     Los 9 contra 12 son `hidden_metric_ids`; el `col_span` 4 contra 12 es un
         *     override. **Las dos mitades de lo que F4.12 promete, en una sola
         *     respuesta.**
         *
         *     **Lo que sigue sin existir es el lente en la consola**:
         *     `GET /config/tabs/{tabId}` resuelve el rol desde el token y no lo acepta.
         *     No hace falta para F4.12 — el preview ya lo da — y conviene no volver a
         *     pedirlo.
         */
        Preview: {
            /** Format: uuid */
            layout_id: string;
            /** Format: uuid */
            dashboard_id: string;
            /**
             * @description El del layout que se está previsualizando. **Un borrador se puede
             *     previsualizar y un rol no-admin no lo vería**: la compuerta mira quién
             *     pregunta, no a quién se simula.
             * @enum {string}
             */
            status: "draft" | "published";
            /** @description El lente. Anidado, no dos campos planos. */
            role: {
                /** Format: uuid */
                id: string;
                /** @example planner */
                name: string;
            };
            /**
             * @description Sólo las que el rol puede ver, por `roles.tab_ids`. Sin envoltorio
             *     `{tab, panels}`: la pestaña va plana, **con sus paneles adentro**
             *     desde el 2026-09-28.
             */
            tabs: {
                /** Format: uuid */
                id: string;
                name: string;
                /**
                 * @description **La identidad estable de la pestaña** · llegó en `f70cec2` y
                 *     acá se transcribió tarde: lo encontró `npm run humo` el
                 *     2026-09-28, no una lectura del diff.
                 *
                 *     Es la que va a usar `roles.tab_keys` para decidir qué ve cada
                 *     rol, así que en el preview es **el campo por el que se filtra**
                 *     — hoy filtra por `tab_ids`, que se recrean al publicar.
                 * @example overview
                 */
                key: string;
                operational_question: string;
                sort_order: number;
                /** @example  */
                icon: string;
                /** @description **Lista, nunca `null`** · igual que en el cable de consola. */
                chat_suggestions: string[];
                /**
                 * @description **Los paneles COMO LOS VERÍA ESE ROL** · B4.9, medido el
                 *     2026-09-28.
                 *
                 *     Ya vienen filtrados por `hidden_metric_ids` y con los
                 *     `layout_overrides` aplicados —posición, `options`, `note`—, así
                 *     que el front **no filtra ni recompone nada**: dibuja.
                 *
                 *     Es la misma forma que `PanelDTO` del cable de consola, y el
                 *     mismo código las sirve.
                 */
                panels: {
                    /** Format: uuid */
                    id: string;
                    /** Format: uuid */
                    metric_id: string;
                    /**
                     * @example kpi
                     * @example series
                     * @example bars
                     */
                    type: string;
                    col_start: number;
                    /**
                     * @example 4
                     * @example 12
                     */
                    col_span: number;
                    row_span: number;
                    options?: {
                        [key: string]: unknown;
                    };
                    note: string;
                    /**
                     * @description **El gráfico, igual que en el cable de consola** · llegó
                     *     en `f70cec2`. Cadena vacía = el de por defecto del
                     *     bloque, y así salen los doce publicados.
                     *
                     *     Importa que esté acá y no sólo en la consola: **la vista
                     *     previa por rol tiene que dibujar lo mismo que el rol va a
                     *     ver**, y si el preview no trajera el gráfico mostraría
                     *     una cascada como dona y nadie lo notaría.
                     * @example
                     * @example waterfall
                     */
                    chart: string;
                }[];
            }[];
        };
        /**
         * @description `ports.AgentAdminDTO` · el agente visto desde administración.
         *
         *     **Tres de estos campos no se pintan nunca**, y no es un olvido:
         *     `snowflake_db`, `snowflake_schema` y `warehouse` son vocabulario de
         *     infraestructura, que §7.3 de `design.md` prohíbe en esta superficie —
         *     «se declara la consecuencia, no la plomería».
         *
         *     **Y el campo que §7.3 SÍ pide no existe:** «acceso vigente, última
         *     verificación». `is_active` no lo es y `updated_at` tampoco: uno es un
         *     interruptor y el otro dice cuándo se editó la fila.
         */
        AgentAdmin: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tenant_id: string;
            name: string;
            /**
             * @description El rol de PRODUCTO que atiende este agente —«Planner», «CEO»—, no un
             *     rol técnico de Snowflake. Sale de `roles.name`.
             */
            target_role: string;
            /** @description No se pinta · §7.3. */
            snowflake_db: string;
            /** @description No se pinta · §7.3. */
            snowflake_schema: string;
            snowflake_cortex_agent_name: string;
            /** @description No se pinta · §7.3. */
            warehouse: string;
            /**
             * @description Las vistas que el agente puede consultar. **Nombres de objeto de
             *     Snowflake**, así que tampoco se pintan crudos.
             */
            semantic_views: string[];
            system_prompt_base: string;
            /**
             * @description **Baja lógica, no verificación de acceso.** Un agente activo puede
             *     tener la credencial vencida y este campo seguiría en `true`.
             */
            is_active: boolean;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
    };
    responses: {
        /** @description Identificador mal formado */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description El JWT no es de rol `admin` */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description No existe */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Composición inválida */
        Unprocessable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /**
         * @description Choca con una regla · nombre de rol duplicado, o un rol con usuarios
         *     asignados. **El mensaje dice qué hacer**, no «conflicto».
         */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        tenantId: string;
        layoutId: string;
        roleId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listTenants: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista de tenants */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["TenantOption"][];
                    };
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    listLayouts: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: components["parameters"]["tenantId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Versiones */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["LayoutVersion"][];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
        };
    };
    createDraft: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: components["parameters"]["tenantId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** @example borrador-f4 */
                    version_id?: string;
                };
            };
        };
        responses: {
            /** @description El borrador creado */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["LayoutVersion"];
                    };
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    adminCatalog: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: components["parameters"]["tenantId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Catálogo completo del tenant */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["CatalogMetric"][];
                    };
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    getLayout: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                layoutId: components["parameters"]["layoutId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Detalle del layout */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["LayoutDetail"];
                    };
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updateLayout: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                layoutId: components["parameters"]["layoutId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LayoutUpdateRequest"];
            };
        };
        responses: {
            /** @description El layout guardado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["LayoutDetail"];
                    };
                };
            };
            /** @description El layout está publicado y no se puede editar */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            422: components["responses"]["Unprocessable"];
        };
    };
    validateLayout: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                layoutId: components["parameters"]["layoutId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Resultado de la validación */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["ValidationResult"];
                    };
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    listRoles: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: components["parameters"]["tenantId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Los roles */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["Role"][];
                    };
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    createRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: components["parameters"]["tenantId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoleInput"];
            };
        };
        responses: {
            /** @description El rol creado */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["Role"];
                    };
                };
            };
            409: components["responses"]["Conflict"];
        };
    };
    updateRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roleId: components["parameters"]["roleId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoleInput"];
            };
        };
        responses: {
            /** @description El rol editado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["Role"];
                    };
                };
            };
            409: components["responses"]["Conflict"];
        };
    };
    deleteRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roleId: components["parameters"]["roleId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Borrado */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            409: components["responses"]["Conflict"];
        };
    };
    previewLayout: {
        parameters: {
            query: {
                /**
                 * @description **snake_case**, al revés de `layoutId` y `dashboardId` de
                 *     `/config/tabs`. Se leyó del handler; mandarlo en camelCase da 400.
                 */
                role_id: string;
            };
            header?: never;
            path: {
                layoutId: components["parameters"]["layoutId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description El layout filtrado por ese rol */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["Preview"];
                    };
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    publishLayout: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                layoutId: components["parameters"]["layoutId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** @example v3 */
                    version_id?: string;
                };
            };
        };
        responses: {
            /** @description La versión publicada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["LayoutVersion"];
                    };
                };
            };
            422: components["responses"]["Unprocessable"];
        };
    };
    revertLayout: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                layoutId: components["parameters"]["layoutId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /**
                     * Format: uuid
                     * @description A qué versión volver. **Sin esto se usa el
                     *     `previous_layout_id` de la última publicación**, y si no hay
                     *     da `409 CONFLICT_NO_PREVIOUS`.
                     */
                    to_layout_id?: string;
                    /**
                     * @description El nombre de la versión nueva. Por defecto
                     *     `rollback-<versión copiada>`.
                     * @example rollback-v1
                     */
                    version_id?: string;
                };
            };
        };
        responses: {
            /** @description La versión nueva, ya publicada · **no medida** */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["LayoutVersion"];
                    };
                };
            };
            /** @description El destino no existe o es de otro dashboard · `NOT_FOUND_REVERT_TARGET` */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /**
             * @description `CONFLICT_NO_PREVIOUS` — no hay a qué volver y no mandaron destino ·
             *     **medido** · `CONFLICT_REVERT_SELF` — el destino es este mismo layout ·
             *     **medido** · `CONFLICT_REVERT_TO_DRAFT` — el destino es un borrador.
             */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description `VALIDATION_REVERT_TARGET` — la versión vieja ya no valida contra el catálogo actual */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listAgents: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: components["parameters"]["tenantId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Los agentes del cliente */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["AgentAdmin"][];
                    };
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listAllUsers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Los usuarios de todos los clientes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["UsersPlatform"];
                    };
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    listUsers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: components["parameters"]["tenantId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Los usuarios del cliente */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["User"][];
                    };
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listFeeds: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: components["parameters"]["tenantId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Las fuentes, con su cadencia, su frescura y sus métricas */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["Feed"][];
                    };
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
}
