/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/admin/tenants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Los tenants, para elegir cuál se compone */
        get: operations["listTenants"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/tenants/{tenantId}/layouts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Las versiones de layout del tenant · borrador y publicada */
        get: operations["listLayouts"];
        put?: never;
        /**
         * Crear un borrador vacío
         * @description Responde **201**, no 200. `version_id` es opcional al crear: se puede
         *     poner al publicar.
         */
        post: operations["createDraft"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/tenants/{tenantId}/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Las métricas del tenant, SIN filtrar por rol
         * @description La diferencia con `/config/catalog` es esa: acá no se aplica
         *     `hidden_metric_ids`, porque quien compone tiene que poder asignar una
         *     métrica que después un rol no verá.
         *
         *     Devuelve el mismo `CatalogMetric` que la consola — **ese struct SÍ tiene
         *     etiquetas `json:`**.
         */
        get: operations["adminCatalog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/layouts/{layoutId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** El layout con sus pestañas y paneles · para el builder */
        get: operations["getLayout"];
        /**
         * Reemplazar las pestañas y los paneles
         * @description **Es un REEMPLAZO COMPLETO**, no un parche: se envía el layout entero y
         *     lo que no venga se borra.
         *
         *     **Solo un `draft` es editable** — sobre uno publicado responde 409.
         *
         *     El cuerpo va en **snake_case**, a diferencia de la respuesta.
         */
        put: operations["updateLayout"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/layouts/{layoutId}/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Validar la composición contra la tabla `blocks`
         * @description **Responde 200 aunque la composición sea inválida**: el resultado va en
         *     `data.valid` y `data.errors`. Un 200 no quiere decir que el layout esté
         *     bien — quiere decir que la validación corrió.
         */
        post: operations["validateLayout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/tenants/{tenantId}/roles/composition": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Los roles del cliente, con su composición
         * @description **No la sirve el servicio desplegado.** Escrita en el fork · B4.8.
         *
         *     `user_count` viaja en el listado a propósito: es lo que decide si el rol
         *     se puede borrar, y la pantalla tiene que poder decirlo **antes** de
         *     ofrecer el botón, no después de un 409.
         */
        get: operations["listRoles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/tenants/{tenantId}/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Crear un rol
         * @description **409 si ya existe un rol con ese nombre en el cliente.** El índice único
         *     es `(tenant_id, name)` y el servicio pregunta antes para poder decir qué
         *     pasó en vez de devolver el error de Postgres como un 500.
         */
        post: operations["createRole"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/roles/{roleId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Editar un rol
         * @description **Escribe cuatro columnas: `name`, `tab_ids`, `hidden_metric_ids` y
         *     `layout_overrides`.** `tenant_id` no se toca: un rol no cambia de cliente.
         *
         *     `layout_overrides` ausente se escribe como `{}`, no se deja intacto.
         */
        put: operations["updateRole"];
        post?: never;
        /**
         * Borrar un rol
         * @description **204 sin cuerpo.** Y **409 con la razón y el número si tiene usuarios
         *     asignados** — no borra en cascada: dejaría usuarios sin rol, que es un
         *     usuario que no puede entrar a ninguna pestaña.
         */
        delete: operations["deleteRole"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/layouts/{layoutId}/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * El layout como lo vería un rol
         * @description **No la sirve el servicio desplegado.** Escrita en el fork · B4.9.
         *
         *     **Pasa por el mismo `GetTab` que sirve a la consola**, así que
         *     `tab_ids`, `hidden_metric_ids` y `layout_overrides` se aplican una sola
         *     vez y en un solo lugar. Un preview que reimplemente el filtrado termina
         *     mostrando algo que la consola no muestra, y se publica confiando en él.
         *
         *     **Viene SIN payloads** y lo declara en `without_payloads`. Con el layout
         *     alcanza para «CEO vs Planner»; con payloads habría que decidir qué
         *     período usa y si un panel oculto llega como `SIN_PERMISO`.
         *
         *     Un `roleId` de otro tenant devuelve **404 y no 403**: un 403 confirmaría
         *     que el rol existe.
         */
        get: operations["previewLayout"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/layouts/{layoutId}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Publicar la versión
         * @description **Demota el layout publicado anterior del tenant a `draft`.** Solo hay
         *     uno publicado por tenant, así que publicar cambia lo que ve la consola en
         *     su próxima carga.
         *
         *     Rechaza con **422** si hay paneles inválidos.
         */
        post: operations["publishLayout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/tenants/{tenantId}/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Los agentes configurados para el cliente
         * @description **Transcrita el 2026-09-21 desde `82da946`**, leyendo
         *     `internal/core/ports/agent.go` —`AgentAdminDTO`— y
         *     `internal/adapters/handler/agent_handler.go`.
         *
         *     **`AgentAdminDTO` SÍ tiene etiquetas `json:` y sale en snake_case**, a
         *     diferencia del resto de admin, que serializa structs de dominio en
         *     PascalCase. No se deduce del patrón: se leyó.
         *
         *     **Nunca incluye credenciales** — lo dice el comentario del DTO y lo
         *     confirma la lista de campos. Lo que sí trae y **§7.3 prohíbe mostrar**
         *     es `snowflake_db`, `snowflake_schema` y `warehouse`: «ni base, ni rol
         *     técnico, ni grants, ni warehouse». Se transcriben porque describir el
         *     cable no es pintarlo.
         *
         *     **Devuelve también los inactivos.** `is_active` es una baja lógica que
         *     alguien apretó, no una verificación de que el acceso funcione.
         */
        get: operations["listAgents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Envelope: {
            /** @enum {boolean} */
            success: true;
        };
        /** @description El mismo de la consola · `error` es una CADENA. */
        ErrorResponse: {
            /** @enum {boolean} */
            success: false;
            error: string;
        };
        /** @description `ports.TenantPublicOption` · SÍ tiene etiquetas `json:`. */
        TenantOption: {
            /** Format: uuid */
            id: string;
            name: string;
        };
        /**
         * @description `domain.DDCatalogMetric`, el mismo de `/config/catalog`. **Con etiquetas
         *     `json:`**, así que sale en snake_case. Ver `synapse-console-wire.yaml`
         *     para el detalle de cada campo — no se duplica acá.
         */
        CatalogMetric: {
            /** Format: uuid */
            id: string;
            key: string;
            name: string;
            shape: string;
            family: string;
            layer: string;
            source: string;
            base: string;
            min_grain: string;
            catalog_version: number;
        } & {
            [key: string]: unknown;
        };
        /**
         * @description `domain.DDLayoutVersion`, **serializado SIN etiquetas `json:`**. Las
         *     claves son los nombres de los campos de Go.
         *
         *     `Tenant` viaja porque el struct lo declara y no lleva `json:"-"`. Hoy
         *     llega en cero —nadie hace `Preload`— y por eso no se declaran sus
         *     campos acá: **lo que sea que traiga, el front no lo lee**.
         */
        LayoutVersion: {
            /** Format: uuid */
            ID: string;
            /** Format: uuid */
            TenantID: string;
            /**
             * @description Solo uno `published` por tenant. Publicar demota al anterior.
             * @enum {string}
             */
            Status: "draft" | "published";
            /** @description Etiqueta legible. Cadena vacía si nunca se puso. */
            VersionID: string;
            /** Format: date-time */
            PublishedAt?: string | null;
            /** Format: date-time */
            CreatedAt?: string;
            /** Format: date-time */
            UpdatedAt?: string;
            /** @description **No se lee.** Ver el aviso de la cabecera del archivo. */
            Tenant?: {
                [key: string]: unknown;
            };
        };
        /** @description `domain.DDTab`, también sin etiquetas `json:`. */
        LayoutTab: {
            /** Format: uuid */
            ID: string;
            /** Format: uuid */
            LayoutVersionID: string;
            Name: string;
            /**
             * @description La pregunta operativa. Cadena vacía si no se puso — **y el producto
             *     dice que una pestaña que no contesta una pregunta no se compone**,
             *     así que el builder no la deja vacía aunque el backend sí.
             */
            OperationalQuestion?: string;
            SortOrder: number;
            /** @description Vacío significa «la ven todos los roles». */
            RoleIDs?: string[];
            /** Format: date-time */
            CreatedAt?: string;
            /** Format: date-time */
            UpdatedAt?: string;
        };
        /**
         * @description `domain.DDPanel`, sin etiquetas `json:`. **Ojo con `Type`**: en la base la
         *     columna es `block_type` y acá el campo es `Type`.
         */
        LayoutPanel: {
            /** Format: uuid */
            ID: string;
            /** Format: uuid */
            TabID: string;
            /** Format: uuid */
            MetricID: string;
            Type: string;
            ColStart: number;
            ColSpan: number;
            RowSpan: number;
            /** @description Los nombres van en inglés · ver `PARAMS` del adaptador. */
            Options?: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            CreatedAt?: string;
            /** Format: date-time */
            UpdatedAt?: string;
        };
        /**
         * @description `ports.DDLayoutDetail`. **Las dos claves de afuera SÍ tienen etiqueta**
         *     —`layout`, `tabs`— y lo de adentro no. Esa mezcla es toda la deuda.
         */
        LayoutDetail: {
            layout: components["schemas"]["LayoutVersion"];
            tabs: {
                tab: components["schemas"]["LayoutTab"];
                panels: components["schemas"]["LayoutPanel"][];
            }[];
        };
        /**
         * @description `ports.DDLayoutUpdateRequest`. **El cuerpo va en snake_case y la respuesta
         *     en PascalCase**: el builder manda una forma y recibe otra.
         */
        LayoutUpdateRequest: {
            tabs: components["schemas"]["TabInput"][];
        };
        TabInput: {
            /**
             * Format: uuid
             * @description Omitir —o mandar el UUID cero— **genera una pestaña nueva**. Mandar un
             *     UUID existente conserva el id al reemplazar el contenido. Es la
             *     diferencia entre editar y recrear, y no la avisa nada.
             */
            id?: string;
            name: string;
            operational_question?: string;
            /** @description Default si viene 0: el índice del arreglo + 1. */
            sort_order?: number;
            role_ids?: string[];
            panels?: components["schemas"]["PanelInput"][];
        };
        PanelInput: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            metric_id: string;
            type: string;
            /** @description Default si viene 0: 1. */
            col_start?: number;
            /** @description Default si viene 0: 3. */
            col_span?: number;
            /** @description Default si viene 0: 4. */
            row_span?: number;
            options?: {
                [key: string]: unknown;
            };
        };
        /** @description `ports.DDLayoutValidationResult` · SÍ tiene etiquetas `json:`. */
        ValidationResult: {
            valid: boolean;
            errors: components["schemas"]["ValidationIssue"][];
        };
        /**
         * @description Trae `tab_id` y `panel_id` cuando aplica, **así que el error se puede
         *     mostrar SOBRE el panel** y no en una lista al pie.
         */
        ValidationIssue: {
            /** Format: uuid */
            tab_id?: string | null;
            /** Format: uuid */
            panel_id?: string | null;
            field?: string;
            message: string;
        };
        /**
         * @description `ports.DDRoleDTO`. **SÍ lleva etiquetas `json:`**, así que sale en
         *     snake_case entero — a diferencia de `LayoutVersion` y compañía. Es lo
         *     que B4.10 pide para aquellos.
         */
        Role: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tenant_id: string;
            /** @example Planner */
            name: string;
            /** @description Vacío significa «ve todas las pestañas». */
            tab_ids: string[];
            /**
             * @description **Oculta, NO impide.** El servidor vuelve a verificar en
             *     `/config/catalog` y en el batch: un rol que oculta una métrica no es
             *     un rol que no pueda pedirla.
             */
            hidden_metric_ids: string[];
            /**
             * @description Por pestaña y por panel · `col_start`, `col_span`, `row_span`,
             *     `options`. **No muta el layout publicado**: `GetTab` los aplica al
             *     responder.
             */
            layout_overrides?: {
                [key: string]: unknown;
            };
            /** @description Cuántos usuarios tienen el rol. Con uno o más, borrar da 409. */
            user_count: number;
        };
        RoleInput: {
            name: string;
            tab_ids?: string[];
            hidden_metric_ids?: string[];
            /** @description Ausente se escribe como `{}`: «sin overrides» es un estado, no una omisión. */
            layout_overrides?: {
                [key: string]: unknown;
            };
        };
        /**
         * @description `ports.DDPreviewResponse` · el layout como lo vería un rol, resuelto por
         *     el **mismo `GetTab`** que sirve a la consola.
         */
        Preview: {
            /** Format: uuid */
            layout_id: string;
            /** Format: uuid */
            role_id: string;
            role_name: string;
            /**
             * @description Solo las que el rol puede ver, con sus paneles ya filtrados y los
             *     overrides aplicados. **Forma de la CONSOLA** —`ports.DDTabWithPanels`,
             *     snake_case— y no la del builder.
             */
            tabs: {
                tab: {
                    /** Format: uuid */
                    id: string;
                    name: string;
                    operational_question?: string;
                    sort_order: number;
                };
                panels: {
                    /** Format: uuid */
                    id: string;
                    /** Format: uuid */
                    metric_id: string;
                    type: string;
                    col_start: number;
                    col_span: number;
                    row_span: number;
                    options?: {
                        [key: string]: unknown;
                    };
                }[];
            }[];
            /**
             * @description Siempre `true` hoy. **Es una declaración, no un flag**: quien la
             *     consuma tiene que saber que los paneles vienen sin datos, para no
             *     dibujar un cuerpo vacío creyendo que el panel está en blanco.
             */
            without_payloads: boolean;
        };
        /**
         * @description `ports.AgentAdminDTO` · el agente visto desde administración.
         *
         *     **Tres de estos campos no se pintan nunca**, y no es un olvido:
         *     `snowflake_db`, `snowflake_schema` y `warehouse` son vocabulario de
         *     infraestructura, que §7.3 de `design.md` prohíbe en esta superficie —
         *     «se declara la consecuencia, no la plomería».
         *
         *     **Y el campo que §7.3 SÍ pide no existe:** «acceso vigente, última
         *     verificación». `is_active` no lo es y `updated_at` tampoco: uno es un
         *     interruptor y el otro dice cuándo se editó la fila.
         */
        AgentAdmin: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tenant_id: string;
            name: string;
            /**
             * @description El rol de PRODUCTO que atiende este agente —«Planner», «CEO»—, no un
             *     rol técnico de Snowflake. Sale de `roles.name`.
             */
            target_role: string;
            /** @description No se pinta · §7.3. */
            snowflake_db: string;
            /** @description No se pinta · §7.3. */
            snowflake_schema: string;
            snowflake_cortex_agent_name: string;
            /** @description No se pinta · §7.3. */
            warehouse: string;
            /**
             * @description Las vistas que el agente puede consultar. **Nombres de objeto de
             *     Snowflake**, así que tampoco se pintan crudos.
             */
            semantic_views: string[];
            system_prompt_base: string;
            /**
             * @description **Baja lógica, no verificación de acceso.** Un agente activo puede
             *     tener la credencial vencida y este campo seguiría en `true`.
             */
            is_active: boolean;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
    };
    responses: {
        /** @description Identificador mal formado */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description El JWT no es de rol `admin` */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description No existe */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Composición inválida */
        Unprocessable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /**
         * @description Choca con una regla · nombre de rol duplicado, o un rol con usuarios
         *     asignados. **El mensaje dice qué hacer**, no «conflicto».
         */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        tenantId: string;
        layoutId: string;
        roleId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listTenants: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista de tenants */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["TenantOption"][];
                    };
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    listLayouts: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: components["parameters"]["tenantId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Versiones */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["LayoutVersion"][];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
        };
    };
    createDraft: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: components["parameters"]["tenantId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** @example borrador-f4 */
                    version_id?: string;
                };
            };
        };
        responses: {
            /** @description El borrador creado */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["LayoutVersion"];
                    };
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    adminCatalog: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: components["parameters"]["tenantId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Catálogo completo del tenant */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["CatalogMetric"][];
                    };
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    getLayout: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                layoutId: components["parameters"]["layoutId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Detalle del layout */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["LayoutDetail"];
                    };
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updateLayout: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                layoutId: components["parameters"]["layoutId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LayoutUpdateRequest"];
            };
        };
        responses: {
            /** @description El layout guardado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["LayoutDetail"];
                    };
                };
            };
            /** @description El layout está publicado y no se puede editar */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            422: components["responses"]["Unprocessable"];
        };
    };
    validateLayout: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                layoutId: components["parameters"]["layoutId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Resultado de la validación */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["ValidationResult"];
                    };
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    listRoles: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: components["parameters"]["tenantId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Los roles */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["Role"][];
                    };
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    createRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: components["parameters"]["tenantId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoleInput"];
            };
        };
        responses: {
            /** @description El rol creado */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["Role"];
                    };
                };
            };
            409: components["responses"]["Conflict"];
        };
    };
    updateRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roleId: components["parameters"]["roleId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoleInput"];
            };
        };
        responses: {
            /** @description El rol editado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["Role"];
                    };
                };
            };
            409: components["responses"]["Conflict"];
        };
    };
    deleteRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roleId: components["parameters"]["roleId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Borrado */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            409: components["responses"]["Conflict"];
        };
    };
    previewLayout: {
        parameters: {
            query: {
                roleId: string;
            };
            header?: never;
            path: {
                layoutId: components["parameters"]["layoutId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description El layout filtrado por ese rol */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["Preview"];
                    };
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    publishLayout: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                layoutId: components["parameters"]["layoutId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** @example v3 */
                    version_id?: string;
                };
            };
        };
        responses: {
            /** @description La versión publicada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["LayoutVersion"];
                    };
                };
            };
            422: components["responses"]["Unprocessable"];
        };
    };
    listAgents: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: components["parameters"]["tenantId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Los agentes del cliente */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["AgentAdmin"][];
                    };
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
}
