/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Iniciar sesión
         * @description Autentica al usuario y devuelve un JWT válido por 24 horas.
         *
         *     Si `user.password_updated` es `false` el front debe mostrar un modal bloqueante
         *     solicitando cambio de contraseña antes de acceder a la app.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description Login exitoso */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessResponse"] & {
                            data?: {
                                /** @description JWT HS256. Enviar en: Authorization: Bearer <token> */
                                token?: string;
                                user?: components["schemas"]["LoginUserInfo"];
                            };
                        };
                    };
                };
                /** @description Credenciales inválidas */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/token-info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Información del token actual
         * @description Devuelve los datos del usuario en BD y los claims del JWT activo.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Sesión activa */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessResponse"] & {
                            data?: {
                                user?: components["schemas"]["LoginUserInfo"];
                                token_info?: components["schemas"]["JWTTokenClaims"];
                            };
                        };
                    };
                };
                /** @description Token inválido o expirado */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cambiar contraseña
         * @description Cambia la contraseña del usuario autenticado.
         *
         *     **Política de contraseña (validada en servidor):**
         *     - Mínimo 8 caracteres
         *     - Al menos 1 letra
         *     - Al menos 1 número
         *     - Al menos 1 carácter especial (ej: ! @ # $ %)
         *     - Debe ser distinta a la contraseña actual
         *
         *     Tras un cambio exitoso, `password_updated` pasa a `true` en el JWT y en BD.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ChangePasswordRequest"];
                };
            };
            responses: {
                /** @description Contraseña actualizada */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessResponse"] & {
                            data?: {
                                /** @example contraseña actualizada correctamente */
                                message?: string;
                                user?: components["schemas"]["LoginUserInfo"];
                            };
                        };
                    };
                };
                /**
                 * @description Contraseña no cumple la política. El campo `error` indica el criterio fallido:
                 *     - `la contraseña debe tener al menos 8 caracteres`
                 *     - `la contraseña debe incluir al menos una letra`
                 *     - `la contraseña debe incluir al menos un número`
                 *     - `la contraseña debe incluir al menos un carácter especial (por ejemplo: ! @ # $ %)`
                 *     - `la nueva contraseña debe ser distinta a la actual`
                 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Contraseña actual incorrecta o token inválido */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/access-requests/tenants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar compañías (dropdown público)
         * @description Devuelve `id` y `name` de todas las compañías registradas.
         *
         *     **Endpoint público** (sin JWT). Se usa como fuente del dropdown de Tenant
         *     en el panel admin al aprobar solicitudes.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Lista de compañías */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessResponse"] & {
                            data?: components["schemas"]["TenantPublicOption"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/access-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Enviar solicitud de acceso (registro)
         * @description **Endpoint público** (sin JWT).
         *
         *     El solicitante escribe el nombre de su empresa en `company_name` (texto libre).
         *     El administrador asignará el tenant y agente reales al aprobar la solicitud.
         *
         *     Reglas de negocio:
         *     - `accepted_terms` y `accepted_privacy_policy` deben ser `true`.
         *     - No puede existir ya un usuario registrado con ese correo.
         *     - No puede existir ya una solicitud `pending` con ese correo.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SubmitAccessRequestBody"];
                };
            };
            responses: {
                /** @description Solicitud creada. Se envía email de confirmación al solicitante. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessResponse"] & {
                            data?: components["schemas"]["AccessRequestResponse"];
                        };
                    };
                };
                /** @description Datos inválidos o no aceptó términos/política */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Ya existe solicitud pendiente o usuario con ese correo */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/password-reset-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Enviar solicitud de recuperación de contraseña
         * @description **Endpoint público** (sin JWT).
         *
         *     Crea una solicitud `password_reset` para el correo indicado.
         *
         *     **Por seguridad**: si el correo no está registrado, la respuesta es igualmente exitosa
         *     (sin revelar si el correo existe o no). La solicitud solo se crea internamente si existe.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SubmitPasswordResetBody"];
                };
            };
            responses: {
                /** @description Respuesta genérica (éxito independientemente de si el correo existe) */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessResponse"] & {
                            data?: {
                                /** @example Si el correo está registrado, tu solicitud fue enviada y será revisada por el equipo. */
                                message?: string;
                                /** @description Solo presente si el correo está registrado. */
                                request?: components["schemas"]["AccessRequestResponse"];
                            };
                        };
                    };
                };
                /** @description Ya existe una solicitud pendiente con ese correo */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Chat con el agente (Server-Sent Events)
         * @description Envía mensajes al agente Snowflake Cortex del tenant y recibe la respuesta
         *     en tiempo real usando **Server-Sent Events (SSE)**.
         *
         *     **Respuesta:** `Content-Type: text/event-stream`. Cada línea tiene el formato:
         *     ```
         *     data: {"delta":{"type":"text","text_delta":"hola"},"metadata":{...}}
         *     ```
         *
         *     **Creación de thread:**
         *     - Si `thread_id` es `null` o se omite, se crea automáticamente un nuevo thread en Snowflake.
         *     - El `thread_id` retornado en los eventos de metadata debe guardarse para continuar la conversación.
         *
         *     **Rate limiting:** límite por usuario. Si se excede devuelve HTTP 429.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ChatRequest"];
                };
            };
            responses: {
                /** @description Stream SSE con la respuesta del agente */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/event-stream": string;
                    };
                };
                /** @description Body inválido */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Token inválido */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Rate limit excedido */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Error interno o problema con Snowflake Cortex */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cortex/threads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar threads del tenant en Snowflake Cortex
         * @description Devuelve los threads almacenados en Snowflake Cortex para el tenant del usuario autenticado.
         *     Filtrable por aplicación de origen.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Filtrar por aplicación de origen del thread. */
                    origin_application?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Lista de threads */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessResponse"] & {
                            data?: components["schemas"]["Thread"][];
                        };
                    };
                };
                /** @description Error al consultar Snowflake Cortex */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cortex/threads/{thread_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Obtener un thread con sus mensajes (paginado)
         * @description Devuelve el detalle de un thread y sus mensajes, paginados.
         *
         *     **Paginación hacia atrás:** usar `last_message_id` con el ID del mensaje más antiguo
         *     que ya se tiene para cargar los anteriores.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Número de mensajes por página (máx. 100). */
                    page_size?: number;
                    /** @description ID del mensaje desde el que paginar hacia atrás. */
                    last_message_id?: number;
                };
                header?: never;
                path: {
                    /** @description ID numérico del thread en Snowflake Cortex. */
                    thread_id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Thread con mensajes */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessResponse"] & {
                            data?: components["schemas"]["ThreadDetailResponse"];
                        };
                    };
                };
                /** @description Parámetros inválidos */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Thread no encontrado */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/history/threads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Historial de conversaciones del usuario
         * @description Devuelve los threads que el usuario ha iniciado, ordenados por actividad reciente.
         *     Esta lista se almacena en la BD de Synapse (no consulta Snowflake directamente).
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Lista de threads del historial */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessResponse"] & {
                            data?: components["schemas"]["UserThreadResponse"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/history/threads/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Renombrar un thread del historial
         * @description Actualiza el nombre visible (preview del primer mensaje) del thread.
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description UUID interno del registro en el historial. */
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * @description Nuevo nombre visible para el thread.
                         * @example Reporte de ventas Q1 2026
                         */
                        first_message_preview: string;
                    };
                };
            };
            responses: {
                /** @description Thread renombrado */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessResponse"] & {
                            data?: {
                                /** Format: uuid */
                                id?: string;
                                first_message_preview?: string;
                                thread_name?: string;
                            };
                        };
                    };
                };
                /** @description Thread no encontrado */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        post?: never;
        /**
         * Eliminar un thread del historial
         * @description Elimina el registro del thread del historial del usuario (no elimina el thread en Snowflake).
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description UUID interno del registro en el historial. */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Thread eliminado */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessResponse"] & {
                            data?: {
                                /** @example thread eliminado del historial */
                                message?: string;
                            };
                        };
                    };
                };
                /** @description Thread no encontrado en el historial del usuario */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tickets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar tickets del usuario
         * @description Devuelve los tickets del usuario agrupados en `all` y `unread` (no vistos).
         *     Ordenados por `updated_at` DESC dentro de cada grupo.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Tickets del usuario */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessResponse"] & {
                            data?: {
                                all?: components["schemas"]["TicketSummary"][];
                                unread?: components["schemas"]["TicketSummary"][];
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        /**
         * Crear ticket de soporte
         * @description Crea un ticket de soporte asociado a una respuesta del agente.
         *     Enviar como `multipart/form-data`. La imagen es opcional (máx. 10 MB).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        /** @description ID del thread de Snowflake Cortex relacionado. */
                        thread_id?: string;
                        /**
                         * @description Asunto breve del problema.
                         * @example La respuesta del agente está incompleta
                         */
                        asunto: string;
                        /**
                         * @description Descripción detallada del problema.
                         * @example El agente respondió con datos del mes pasado en lugar del actual.
                         */
                        mensaje: string;
                        /** @description JSON completo de la respuesta del agente (campo `data` del SSE). */
                        respuesta: string;
                        /**
                         * Format: binary
                         * @description Screenshot adjunto (PNG/JPEG recomendado, opcional).
                         */
                        imagen?: string;
                    };
                };
            };
            responses: {
                /** @description Ticket registrado */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessResponse"] & {
                            data?: {
                                /** @example ticket registrado correctamente */
                                message?: string;
                            };
                        };
                    };
                };
                /** @description Campos requeridos faltantes o JSON de `respuesta` inválido */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tickets/{ticket_id}/seen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Marcar ticket como visto
         * @description Marca el ticket como leído por el usuario.
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID numérico del ticket. */
                    ticket_id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Ticket marcado como visto */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessResponse"] & {
                            data?: {
                                /** @example ticket marcado como visto */
                                message?: string;
                            };
                        };
                    };
                };
                /** @description ticket_id inválido */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents/ping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Verificar configuración Snowflake del tenant
         * @description Verifica que el tenant del usuario autenticado tiene configuración Snowflake
         *     registrada y accesible. Útil para health-check previo al chat.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Configuración válida */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessResponse"] & {
                            data?: {
                                /** @example ok */
                                status?: string;
                                /** Format: uuid */
                                tenant_id?: string;
                            };
                        };
                    };
                };
                /** @description Tenant no encontrado para este usuario */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/tenants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Crear compañía (tenant)
         * @description Registra una nueva compañía con su configuración de Snowflake.
         *     La clave privada PEM se cifra en BD usando AWS KMS.
         *
         *     **Rol requerido:** `admin`
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateTenantRequest"];
                };
            };
            responses: {
                /** @description Tenant creado */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessResponse"] & {
                            data?: components["schemas"]["TenantResponse"];
                        };
                    };
                };
                /** @description Body inválido */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Rol insuficiente (se requiere admin) */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Crear usuario manualmente
         * @description Crea un usuario directamente en el sistema (sin pasar por el flujo de solicitud de acceso).
         *
         *     El usuario tendrá `password_updated: false`, por lo que deberá cambiar su contraseña
         *     en el primer login.
         *
         *     **Rol requerido:** `admin`
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateUserRequest"];
                };
            };
            responses: {
                /** @description Usuario creado */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessResponse"] & {
                            data?: {
                                /** Format: uuid */
                                id?: string;
                                /** Format: uuid */
                                tenant_id?: string;
                                email?: string;
                                first_name?: string;
                                last_name?: string;
                                phone?: string;
                                role?: string;
                                /** Format: date-time */
                                created_at?: string;
                            };
                        };
                    };
                };
                /** @description Body inválido */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Rol insuficiente */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Ya existe un usuario con ese correo */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar agentes de un tenant
         * @description Devuelve los agentes del tenant indicado (id, name, target_role).
         *     Usado para poblar el dropdown de "Agente" en el flujo de aprobación de solicitudes.
         *
         *     **Rol requerido:** `admin` o `planner`
         */
        get: {
            parameters: {
                query: {
                    /** @description UUID del tenant cuyos agentes se quieren listar. */
                    tenant_id: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Lista de agentes */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessResponse"] & {
                            data?: components["schemas"]["AgentOption"][];
                        };
                    };
                };
                /** @description tenant_id faltante o inválido */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Tenant no encontrado */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Crear agente Snowflake Cortex
         * @description Registra un nuevo agente Snowflake Cortex asociado a un tenant.
         *
         *     Cada tenant puede tener múltiples agentes, uno por rol lógico (`target_role`).
         *     Al aprobar una solicitud de registro, se asigna el agente cuyo `target_role` coincide
         *     con el rol que recibirá el nuevo usuario.
         *
         *     **Rol requerido:** `admin`
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateAgentRequest"];
                };
            };
            responses: {
                /** @description Agente creado */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessResponse"] & {
                            data?: {
                                /** Format: uuid */
                                id?: string;
                                /** Format: uuid */
                                tenant_id?: string;
                                name?: string;
                                target_role?: string;
                                snowflake_db?: string;
                                snowflake_schema?: string;
                                snowflake_cortex_agent_name?: string;
                                warehouse?: string;
                                /** Format: date-time */
                                created_at?: string;
                                /** Format: date-time */
                                updated_at?: string;
                            };
                        };
                    };
                };
                /** @description Body inválido */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Rol insuficiente */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/access-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar solicitudes de acceso
         * @description Devuelve solicitudes de registro y recuperación de contraseña.
         *
         *     **Sin `status`:** devuelve **todas** (primero `pending` por `created_at` DESC,
         *     luego las gestionadas por `reviewed_at` DESC).
         *
         *     | `status` | Resultado |
         *     |----------|-----------|
         *     | *(omitir)* | Todas (pendientes + gestionadas) |
         *     | `pending` | Solo pendientes |
         *     | `history` | Solo gestionadas (aprobadas + rechazadas) |
         *     | `approved` | Solo aprobadas |
         *     | `rejected` | Solo rechazadas |
         *
         *     **Rol requerido:** `admin` o `planner`
         */
        get: {
            parameters: {
                query?: {
                    page?: number;
                    page_size?: number;
                    /** @description Filtro opcional de estado. */
                    status?: "pending" | "approved" | "rejected" | "history";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Lista paginada de solicitudes */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessResponse"] & {
                            data?: components["schemas"]["AccessRequestListResponse"];
                        };
                    };
                };
                /** @description Valor de `status` inválido */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/access-requests/{id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Aprobar solicitud de acceso
         * @description Aprueba una solicitud pendiente.
         *
         *     **Para `type: registration`:**
         *     - `tenant_id` y `agent_id` son **obligatorios**.
         *     - Se crea el usuario, se le asigna el tenant y agente indicados.
         *     - Se envía un email con la contraseña temporal al nuevo usuario.
         *
         *     **Para `type: password_reset`:**
         *     - `tenant_id` y `agent_id` **no se envían** (body vacío `{}`).
         *     - Se resetea la contraseña del usuario existente.
         *     - Se envía un email con la nueva contraseña temporal.
         *
         *     La respuesta incluye `temp_password` (mostrar al admin, no se almacena en BD).
         *
         *     **Rol requerido:** `admin` o `planner`
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description UUID de la solicitud a aprobar. */
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ApproveAccessRequestBody"];
                };
            };
            responses: {
                /** @description Solicitud aprobada */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessResponse"] & {
                            data?: {
                                /** @example solicitud aprobada */
                                message?: string;
                                request?: components["schemas"]["AccessRequestResponse"];
                                /** @description Contraseña temporal generada. Mostrar al admin y NO almacenar. */
                                temp_password?: string;
                            };
                        };
                    };
                };
                /** @description Faltan `tenant_id` / `agent_id` o son inválidos */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Solicitud no encontrada */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description La solicitud ya fue revisada, o el usuario ya existe */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/access-requests/{id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rechazar solicitud de acceso
         * @description Rechaza una solicitud pendiente.
         *     Se envía un email de notificación al solicitante.
         *
         *     **Rol requerido:** `admin` o `planner`
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description UUID de la solicitud a rechazar. */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": Record<string, never>;
                };
            };
            responses: {
                /** @description Solicitud rechazada */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessResponse"] & {
                            data?: {
                                /** @example solicitud rechazada */
                                message?: string;
                                request?: components["schemas"]["AccessRequestResponse"];
                            };
                        };
                    };
                };
                /** @description Solicitud no encontrada */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description La solicitud ya fue revisada */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        SuccessResponse: {
            /** @example true */
            success?: boolean;
            /** @description Payload específico del endpoint */
            data?: unknown;
        };
        ErrorResponse: {
            /** @example false */
            success?: boolean;
            /** @example credenciales inválidas */
            error?: string;
        };
        LoginRequest: {
            /**
             * Format: email
             * @example admin@empresa.com
             */
            email: string;
            /** @example MiClave#2026 */
            password: string;
        };
        LoginUserInfo: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            tenant_id?: string;
            /** Format: email */
            email?: string;
            first_name?: string;
            last_name?: string;
            phone?: string;
            /** @enum {string} */
            role?: "admin" | "planner" | "user";
            /**
             * @description `false` si el usuario debe cambiar su contraseña temporal.
             *     Mostrar modal bloqueante hasta que sea `true`.
             */
            password_updated?: boolean;
        };
        JWTTokenClaims: {
            /** Format: uuid */
            user_id?: string;
            /** Format: uuid */
            tenant_id?: string;
            role?: string;
            issuer?: string;
            subject?: string;
            /** Format: date-time */
            issued_at?: string;
            /** Format: date-time */
            expires_at?: string;
        };
        ChangePasswordRequest: {
            /** @example PasswordTemporal1! */
            current_password: string;
            /**
             * @description Debe cumplir todos los criterios:
             *     - Mínimo 8 caracteres
             *     - Al menos 1 letra
             *     - Al menos 1 número
             *     - Al menos 1 carácter especial (ej: ! @ # $ %)
             * @example NuevaClave#2026
             */
            new_password: string;
        };
        TenantPublicOption: {
            /** Format: uuid */
            id?: string;
            /** @example Acme Corp */
            name?: string;
        };
        SubmitAccessRequestBody: {
            /**
             * @description Nombre de la empresa escrito libremente. Texto libre, sin restricciones de formato.
             * @example Mi Empresa S.A.
             */
            company_name: string;
            /** @example Juan Pérez */
            full_name: string;
            /**
             * Format: email
             * @example juan@empresa.com
             */
            email: string;
            /** @example +573001234567 */
            phone: string;
            /** @example Analista de Datos */
            job_title: string;
            /** @example Generación de reportes de ventas mensuales */
            info_use: string;
            /**
             * @description Debe ser `true`. Si es `false` se rechaza la solicitud.
             * @example true
             */
            accepted_terms: boolean;
            /**
             * @description Debe ser `true`. Si es `false` se rechaza la solicitud.
             * @example true
             */
            accepted_privacy_policy: boolean;
        };
        SubmitPasswordResetBody: {
            /**
             * Format: email
             * @example usuario@empresa.com
             */
            email: string;
        };
        ReviewedByResponse: {
            /** Format: uuid */
            id?: string;
            /** @example Ana García */
            full_name?: string;
            /**
             * Format: email
             * @example ana@admin.com
             */
            email?: string;
        };
        AccessRequestResponse: {
            /** Format: uuid */
            id?: string;
            /**
             * @description `registration` = solicitud de ingreso. `password_reset` = recuperación de contraseña.
             * @enum {string}
             */
            type?: "registration" | "password_reset";
            /**
             * Format: uuid
             * @description Nulo hasta que sea aprobada.
             */
            tenant_id?: string | null;
            /** @description Nombre del tenant asignado al aprobar. */
            tenant_name?: string;
            /** Format: uuid */
            agent_id?: string | null;
            agent_name?: string;
            /** @description Texto libre escrito por el solicitante. */
            company_name?: string;
            full_name?: string;
            /** Format: email */
            email?: string;
            phone?: string;
            job_title?: string;
            info_use?: string;
            /** @enum {string} */
            status?: "pending" | "approved" | "rejected";
            /**
             * Format: uuid
             * @description UUID del usuario creado al aprobar (solo registration).
             */
            created_user_id?: string | null;
            /** Format: uuid */
            reviewed_by_user_id?: string | null;
            /** Format: date-time */
            reviewed_at?: string | null;
            reviewed_by?: components["schemas"]["ReviewedByResponse"];
            /** Format: date-time */
            created_at?: string;
        };
        AccessRequestListResponse: {
            items?: components["schemas"]["AccessRequestResponse"][];
            /** @example 42 */
            total?: number;
            /** @example 1 */
            page?: number;
            /** @example 20 */
            page_size?: number;
            /** @example 3 */
            total_pages?: number;
        };
        /**
         * @example {
         *       "tenant_id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
         *       "agent_id": "7c9e6679-7425-40de-944b-e07fc1f90ae7"
         *     }
         */
        ApproveAccessRequestBody: {
            /**
             * Format: uuid
             * @description Requerido para `registration`. Omitir o enviar vacío para `password_reset`.
             */
            tenant_id?: string;
            /**
             * Format: uuid
             * @description Requerido para `registration`. Omitir o enviar vacío para `password_reset`.
             */
            agent_id?: string;
        };
        ContentItem: {
            /** @example text */
            type: string;
            /** @example ¿Cuáles fueron las ventas del mes de marzo? */
            text: string;
        };
        Message: {
            /** @enum {string} */
            role: "user" | "assistant";
            content: components["schemas"]["ContentItem"][];
        };
        ChatRequest: {
            /** @description Historial de mensajes del turno actual. Incluye el mensaje del usuario como último ítem. */
            messages: components["schemas"]["Message"][];
            /**
             * Format: int64
             * @description ID del thread existente en Snowflake Cortex. Si se omite o es null se crea uno nuevo.
             */
            thread_id?: number | null;
            /**
             * Format: int64
             * @description ID del mensaje padre para continuidad en el thread.
             */
            parent_message_id?: number | null;
        };
        Thread: {
            /** Format: int64 */
            id?: number;
            name?: string;
            app?: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        ThreadMessage: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            parent_id?: number | null;
            /** Format: date-time */
            created_at?: string;
            /** @enum {string} */
            role?: "user" | "assistant";
            /** @description Contenido del mensaje en formato JSON (array de ContentItem). */
            content?: unknown;
            request_id?: string | null;
        };
        ThreadDetailResponse: {
            /** Format: int64 */
            id?: number;
            name?: string;
            app?: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
            messages?: components["schemas"]["ThreadMessage"][];
            /** @description true si hay más mensajes anteriores. Usar `last_message_id` para paginar. */
            has_more?: boolean;
        };
        UserThreadResponse: {
            /**
             * Format: uuid
             * @description UUID interno del registro en BD.
             */
            id?: string;
            /**
             * Format: int64
             * @description ID del thread en Snowflake Cortex.
             */
            thread_id?: number;
            thread_name?: string;
            agent_name?: string;
            role?: string;
            /** @description Primeros ~200 caracteres del mensaje inicial. Se usa también como nombre visible. */
            first_message_preview?: string;
            /** Format: int64 */
            last_message_id?: number | null;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        TicketSummary: {
            /** Format: int64 */
            ticket_id?: number;
            thread_id?: string;
            agent_id?: string;
            rol?: string;
            asunto?: string;
            mensaje?: string;
            /** Format: uri */
            imagen_adjunto?: string | null;
            /** @example open */
            status?: string;
            observacion?: string | null;
            visto_por_usuario?: boolean;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        CreateTenantRequest: {
            /** @example Acme Corp */
            name: string;
            /**
             * Format: uri
             * @example https://acme.snowflakecomputing.com
             */
            snowflake_url: string;
            /** @example ACME-ACCOUNT */
            snowflake_account: string;
            /** @example ACME_SVC_USER */
            snowflake_user: string;
            /** @example SYSADMIN */
            snowflake_role: string;
            /**
             * @description Clave privada RSA en formato PEM. Incluir saltos de línea como `\n`.
             *     ```
             *     -----BEGIN PRIVATE KEY-----
             *     MIIEvgIBADAN...
             *     -----END PRIVATE KEY-----
             *     ```
             */
            private_key_pem: string;
            /**
             * @description Passphrase de la clave privada. Dejar vacío si no está cifrada.
             * @example
             */
            private_key_passphrase?: string;
            /**
             * @description ARN de la clave AWS KMS usada para cifrar la clave privada en BD.
             * @example arn:aws:kms:us-east-1:123456789012:key/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
             */
            kms_key_arn: string;
        };
        TenantResponse: {
            /** Format: uuid */
            id?: string;
            name?: string;
            snowflake_url?: string;
            snowflake_account?: string;
            snowflake_user?: string;
            snowflake_role?: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        CreateUserRequest: {
            /** Format: uuid */
            tenant_id: string;
            /**
             * Format: email
             * @example usuario@empresa.com
             */
            email: string;
            /** @description Contraseña inicial (puede ser temporal). El usuario deberá cambiarla si `password_updated` queda en `false`. */
            password: string;
            /**
             * @default user
             * @example user
             */
            role: string;
            /** @example Juan */
            first_name?: string;
            /** @example Pérez */
            last_name?: string;
            /** @example +573001234567 */
            phone?: string;
        };
        CreateAgentRequest: {
            /**
             * Format: uuid
             * @description UUID del tenant al que pertenece este agente.
             */
            tenant_id: string;
            /**
             * @description Nombre visible del agente en la UI.
             * @example Agente ventas
             */
            name: string;
            /**
             * @description Rol lógico que recibirán los usuarios asignados a este agente al aprobar
             *     una solicitud de registro. Generalmente `user`.
             * @example user
             */
            target_role: string;
            /** @example SALES_DB */
            snowflake_db: string;
            /** @example PUBLIC */
            snowflake_schema: string;
            /** @example SALES_CORTEX_AGENT */
            snowflake_cortex_agent_name: string;
            /** @example COMPUTE_WH */
            warehouse: string;
        };
        AgentOption: {
            /** Format: uuid */
            id?: string;
            /** @example Agente ventas */
            name?: string;
            /** @example user */
            target_role?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
