/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/config/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Contexto del usuario del token
         * @description `DDConfigHandler.GetMe`. Las tabs salen del layout publicado del tenant,
         *     filtradas por `roles.tab_ids`. El filtrado por rol lo hace el servidor.
         */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Métricas del tenant, filtradas por rol
         * @description `data` es un **arreglo desnudo**, no `{ metrics: [...] }`. Sale de
         *     `SendSuccess(c, 200, metrics)` con `[]domain.DDCatalogMetric`.
         */
        get: operations["getCatalog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/blocks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * La tabla tipo ↔ formas ↔ rangos de span
         * @description Catálogo GLOBAL, no por tenant. Sale de la tabla `blocks`. `data` también
         *     es un arreglo desnudo.
         */
        get: operations["getBlocks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/tabs/{tabId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * La composición de una pestaña, sin datos
         * @description Paneles filtrados por `roles.hidden_metric_ids` y con
         *     `roles.layout_overrides` ya aplicados. Un `tabId` que no pertenece al
         *     tenant devuelve **404**, no 403.
         */
        get: operations["getTab"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/panels:batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Los payloads de varios paneles en una llamada
         * @description **Los dos campos del body son `required` en el binding de Gin**, así que
         *     un nombre equivocado devuelve 400 y no un batch vacío. `panel_ids` pide
         *     `min=1`.
         *
         *     Lee `dd_panel_data`, nunca Snowflake. La clave del mapa de respuesta es
         *     el `panel_id` en texto.
         */
        post: operations["batchPanels"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/me/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Persistir el tema del usuario
         * @description Escribe `users.theme`. **No hay ruta para leerlo**: `/config/me` no lo
         *     devuelve, así que la preferencia se guarda y no se puede recuperar.
         */
        put: operations["updatePreferences"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Preguntar desde un panel · stream SSE
         * @description **Transcrita el 2026-09-21 desde `82da946`**, no desde `733c13c` como el
         *     resto de este archivo: la ruta no existía cuando se transcribió lo demás.
         *     Leído `internal/adapters/handler/dd_chat_handler.go` (el handler),
         *     `internal/core/services/dd_chat_service.go` (`pump`, que arma los frames)
         *     y `internal/core/services/cortex_sse.go` (los siete nombres de evento).
         *
         *     **La respuesta NO es JSON: es `text/event-stream`**, y cada trama lleva
         *     DOS líneas — `event: <nombre>` y `data: <json>`. **El discriminador está
         *     en la línea `event:`**, no adentro del JSON, que es lo contrario de lo
         *     que declara `EventoDeChat` del contrato. Por eso hay traducción en
         *     `src/api/chat.ts` y no un `JSON.parse` a secas.
         *
         *     `panel_context` es `binding:"required"` con `panel_id` `uuid`: sin
         *     contexto de panel la llamada devuelve 400. No hay chat sin panel.
         */
        post: operations["askChat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/chat/threads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Los hilos del usuario, con el panel del que salieron
         * @description **Transcrita el 2026-09-21 desde `82da946`**, leyendo
         *     `internal/core/ports/dd_chat_service.go` —`DDChatThreadDTO`— y
         *     `internal/adapters/handler/dd_chat_handler.go` —`ListThreads`—.
         *
         *     **Devuelve un ARREGLO DESNUDO dentro del envelope**, no un objeto con
         *     una clave: `SendSuccess(c, http.StatusOK, threads)`.
         *
         *     **Trae los DOS ids, y no son intercambiables** — ver `ChatThread`.
         */
        get: operations["listChatThreads"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/panels/{panelId}/chat-suggestions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Qué preguntar sobre este panel
         * @description **Transcrita el 2026-09-21 desde `82da946`**, leyendo
         *     `internal/core/services/dd_chat_suggestions.go` y el handler
         *     `DDChatHandler.Suggestions`.
         *
         *     **Determinista y sin Cortex**: las arma `SuggestQuestions` con el
         *     contexto del panel —su forma, su estado y su valor—, así que **no
         *     gasta la cuota del agente** y no puede tardar.
         *
         *     **Cambian con el ESTADO del panel.** Un panel sin datos sugiere «¿Qué
         *     falta para que … tenga datos?»; uno con cifra sugiere por qué está en
         *     ese nivel, cómo se compara y qué la impulsa. Son entre 1 y 4.
         *
         *     **Sin `period` el servicio usa el mes actual en UTC**, que no es el del
         *     tenant. El front lo manda siempre: es el período que se está mirando.
         */
        get: operations["panelChatSuggestions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Envelope: {
            /** @enum {boolean} */
            success: true;
        };
        /**
         * @description **`error` es una CADENA, no un objeto.** `handler/response.go`:
         *
         *         type Response struct {
         *             Success bool        `json:"success"`
         *             Data    interface{} `json:"data,omitempty"`
         *             Error   string      `json:"error,omitempty"`
         *         }
         *
         *     No es el envelope de §4.1 del contrato, que declara
         *     `{ codigo, mensaje, campo, desbloqueaCon }`. Leer esta cadena como objeto
         *     da `code: undefined` y `message: ""` — una pantalla de error sin una
         *     palabra. Es el mismo defecto por el que existe `api/auth.ts`.
         */
        ErrorResponse: {
            /** @enum {boolean} */
            success: false;
            /**
             * @example tab not found
             * @example invalid request: Key: 'DDBatchRequest.PanelIDs' Error:Field validation for 'PanelIDs' failed on the 'required' tag
             */
            error: string;
        };
        /**
         * @description `ports.DDContextResponse`. Comparado con el `Contexto` del contrato, le
         *     faltan: `alcance`, `tenantsDisponibles`, `tenant.etiqueta`,
         *     `tenant.vertical`, `role.puedeAprobar`, `user.capacidades`,
         *     `user.preferencias.tema`, y en la pestaña `key`, `icono` y
         *     `chatSugerencias`.
         */
        ContextResponse: {
            user: components["schemas"]["UserInfo"];
            tenant: components["schemas"]["TenantInfo"];
            role: components["schemas"]["RoleInfo"];
            tabs: components["schemas"]["TabMeta"][];
            /**
             * @description **Cadenas sueltas, no objetos.** `availablePeriods()` devuelve los
             *     últimos doce meses del CALENDARIO contando desde `time.Now()`, tenga
             *     o no tenga materialización. No traen etiqueta, rango, estado ni
             *     grano.
             */
            periods: string[];
            /**
             * @description **Cuál de los doce está EN CURSO**, o sea incompleto. El resto están
             *     cerrados.
             *
             *     **Es del fork** —lo escribimos nosotros en `2fafe82`, B1.27— y
             *     `82da946` no lo trae: contra el servicio desplegado este campo **no
             *     llega**, y el selector se comporta como antes. Medido el 2026-09-22
             *     levantando upstream limpio al lado.
             *
             *     Sin él, el mes en curso se ofrece igual que los cerrados y alguien
             *     compara septiembre con nueve días contra agosto entero y lee una
             *     caída que es «el mes todavía no terminó» · F1.42.
             *
             *     **No se deduce contra `new Date()`**: el corte del día es del tenant
             *     y su huso, no del navegador · la regla de las dos zonas horarias.
             * @example 2026-09
             */
            open_period?: string;
            /**
             * @description Los dashboards que el rol ve. **Con más de uno, la consola necesita
             *     un selector** · F5.1.
             */
            dashboards?: {
                /** Format: uuid */
                id: string;
                name: string;
                slug: string;
                is_default: boolean;
            }[];
            /**
             * Format: uuid
             * @description El resuelto, y el orden de resolución lo declara su comentario:
             *     **preferencia del usuario > rol > default del tenant**. Ausente si
             *     no hay ninguno.
             */
            active_dashboard_id?: string;
            /**
             * Format: uuid
             * @description El layout del dashboard activo. Ausente si no hay ninguno.
             */
            active_layout_id?: string;
            catalog_version: number;
        };
        /** @description El nombre llega partido; el contrato lo pide junto. */
        UserInfo: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            first_name: string;
            last_name: string;
        };
        TenantInfo: {
            /** Format: uuid */
            id: string;
            /** @example Under Armour México */
            name: string;
        };
        RoleInfo: {
            /** Format: uuid */
            id: string;
            /** @example planner */
            name: string;
        };
        TabMeta: {
            /** Format: uuid */
            id: string;
            name: string;
            operational_question: string;
            sort_order: number;
        };
        /**
         * @description `domain.DDCatalogMetric`, serializado con sus etiquetas `json:`.
         *
         *     **`shape`, `family` y `layer` son `string` libre en Go**, no enumerados.
         *     Los valores de abajo son los que el sistema sabe manejar; el servicio no
         *     impide otros, y `sync-catalog` hace upsert de lo que diga una vista de
         *     Snowflake. Cerrarlos es trabajo del adaptador · F1.35.
         *
         *     Le faltan cuatro campos que el contrato declara: `ventana`, `estado`,
         *     `estadoRazon` y `notaLectura`.
         */
        CatalogMetric: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tenant_id: string;
            /**
             * @example revenue
             * @example platform_return
             */
            key: string;
            name: string;
            /**
             * @description Las que `materialize.TransformValue` sabe transformar. **Son quince
             *     desde `168a761`** y este texto decía nueve, que era cierto al
             *     transcribirlo: `scalar`, `scalar_with_interval`, `categorical`,
             *     `ranking`, `time_series`, `multi_series`, `tabular`, `prose`,
             *     `composition`, `compared_categorical`, `multi_attribute_profile`,
             *     `matrix`, `graph`, `flow`, `distribution` y `series_with_band`.
             *
             *     **El conteo viejo costó un mensaje equivocado al backend** el
             *     2026-09-25: se citó esta línea como si confirmara una medición
             *     nuestra, y era la misma lectura vieja escrita dos veces.
             *
             *     `distribution` emite `{bins:[{label, v, lo?, hi?}]}`.
             *
             *     **`series_with_band` es ESTRICTA desde `75b8ecc`**, el mismo día que
             *     se pidió: `{level, points:[{t, v, lo, hi}]}`, con `level` de nivel
             *     superior y `lo`/`hi` obligatorios por punto. Su transformer falla con
             *     `ErrMissingField` si falta cualquiera de los tres, así que lo que
             *     llega está completo o no llega — que es lo que deja al front aplicar
             *     «un pronóstico sin banda no se publica» sin tener que adivinar si es
             *     un intervalo faltante o una serie mal etiquetada.
             *
             *     Reverificado contra `75b8ecc` el 2026-09-25.
             * @example scalar
             * @example scalar_with_interval
             * @example time_series
             * @example multi_series
             * @example categorical
             * @example ranking
             * @example tabular
             * @example prose
             * @example composition
             */
            shape: string;
            /**
             * @description De acá sale el color de datos del front.
             * @example demand
             * @example media
             * @example inventory
             * @example customer
             * @example external
             */
            family: string;
            /**
             * @example BRONZE
             * @example SILVER
             * @example GOLD
             */
            layer: string;
            source: string;
            base: string;
            unit?: string | null;
            /**
             * @description **TEXTO que se pinta tal cual, no un código** · corregido el
             *     2026-09-14 contra el servicio real (F1.39).
             *
             *     La transcripción original decía «el servicio manda un CÓDIGO» y daba
             *     `HIGHER_IS_BETTER` de ejemplo — salía de leer el comentario de
             *     `dd_catalog_metric.go`, que dice «Ej. `HIGHER_IS_BETTER` para
             *     color/flecha en front». El dato real de las doce métricas del tenant
             *     dice `HIGHER = BETTER`: ya redactado, como el contrato lo declara.
             *
             *     Es la única diferencia que el humo encontró entre el cable real y
             *     esta transcripción. Cierra la pregunta 7 de §4 del plan de
             *     integración: **el front lo pinta y no lo traduce**, que es lo que el
             *     adaptador ya hacía.
             * @example HIGHER = BETTER
             */
            semantic_direction?: string | null;
            /**
             * @example day
             * @example week
             * @example month
             */
            min_grain: string;
            dimensions: string[];
            catalog_version: number;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        /** @description `dashboard.BlockRule`. Quince filas en la tabla `blocks`. */
        BlockRule: {
            /**
             * @example kpi
             * @example prose
             * @example series
             * @example bars
             * @example table
             * @example gauge
             * @example forecast
             * @example list
             * @example reco
             * @example composition
             * @example comparison
             * @example distribution
             * @example blocked
             * @example matrix
             * @example graph
             */
            type: string;
            /** @description Etiqueta para la UI de admin. El contrato no la tiene. */
            ui_name: string;
            /**
             * @description **`blocked` declara `["*"]`**, un comodín que el contrato no tiene.
             *     El adaptador lo expande o lo trata aparte.
             */
            accepted_shapes: string[];
            col_span_min: number;
            col_span_max: number;
            row_span_min: number;
            row_span_max: number;
            /**
             * @description Los nombres de param válidos, **en inglés**: `maximum`, `horizon`,
             *     `order`, `cap`, `normalization`, `pillars`, `columns`, `band`,
             *     `cut`, `window`. El front los espera en español · F1.41.
             */
            layout_params?: string[];
        };
        TabWithPanels: {
            tab: components["schemas"]["TabMeta"];
            panels: components["schemas"]["PanelDTO"][];
        };
        /**
         * @description `ports.DDPanelDTO`. En la base la columna es `block_type`; acá el campo
         *     es `type`. Mapea limpio al `PanelConfigurado` del contrato.
         */
        PanelDTO: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            metric_id: string;
            type: string;
            col_start: number;
            col_span: number;
            /** @description En unidades de grilla: px = 96·N − 16. */
            row_span: number;
            /**
             * @description **Interruptores, no datos.** Para `kpi` llega
             *     `{ "comparative": true, "meter": true }`: los booleanos dicen si
             *     mostrar, y los VALORES viajan en `presentation` del payload. El front
             *     hoy los busca acá, que es el bug de F1.40.
             */
            options?: {
                [key: string]: unknown;
            };
        };
        BatchRequest: {
            panel_ids: string[];
            /**
             * @description `ParsePeriod` solo acepta `YYYY-MM` y rechaza cualquier otra cosa —
             *     ni días, ni semanas, ni rangos.
             * @example 2026-08
             */
            period: string;
        };
        /**
         * @description `ports.DDPayloadDTO`. **No es una unión discriminada**: es un struct con
         *     campos `omitempty`, así que el tipo no impide un `BLOCKED` con valor ni
         *     un `AVAILABLE` sin gobierno. El contrato sí lo impide, y el adaptador es
         *     donde eso se vuelve a cerrar.
         *
         *     `governance` va ANIDADO; el contrato lo intersecta en el payload.
         */
        Payload: {
            /**
             * @description Las cinco constantes de `domain/dd_panel_data.go`. **En inglés**, y
             *     la guía de Postman del backend dice `DEGRADADO` — el código manda.
             * @enum {string}
             */
            status: "AVAILABLE" | "DEGRADED" | "BLOCKED" | "FORBIDDEN" | "ERROR";
            governance?: components["schemas"]["Governance"];
            /** @description El JSON crudo de `dd_panel_data.value`. Discriminado por `shape`. */
            value?: {
                [key: string]: unknown;
            };
            /**
             * @description **Solo se emite para `scalar` y `scalar_with_interval`.**
             *     `PresentationFromRows` devuelve `nil` para **todas las demás**, así
             *     que un panel de barras o de tabla llega sin rótulo.
             *
             *     Decía «las otras siete» y eso se venció: el `switch` de
             *     `TransformValue` pasó de nueve formas a quince en `168a761`.
             *     Reverificado contra `1e080ee` el 2026-09-25 — el comportamiento de
             *     `PresentationFromRows` no cambió, el conteo sí. Se escribe sin número
             *     para que no vuelva a vencerse.
             */
            presentation?: {
                [key: string]: unknown;
            };
            /** @description Razón del estado. En `DEGRADED` la redacta el servidor. */
            reason?: string;
            /**
             * @description **Llega vacío en `BLOCKED`.** El servicio solo lo escribe al derivar
             *     `DEGRADED`. §8 pide estado, razón y qué lo desbloquea.
             */
            unlocks_with?: string;
            /** @description Solo en `ERROR`. Sale de `validatePanelOptions`. */
            message?: string;
            /**
             * @description Solo en `FORBIDDEN`, y es **la constante `"administrator"`** escrita
             *     en el código, no el rol que decide sobre la métrica.
             * @example administrator
             */
            request_from?: string;
        };
        /**
         * @description `ports.DDGovernanceDTO`. Los cinco campos que el contrato pide, con otros
         *     nombres y un nivel más abajo.
         */
        Governance: {
            base: string;
            layer: string;
            source: string;
            /**
             * @description `materialized_at` en RFC 3339. **Cadena vacía** cuando el registro no
             *     tiene fecha de materialización, no `null`.
             */
            freshness: string;
            catalog_version: number;
        };
        /**
         * @description `ddChatRequest` de `dd_chat_handler.go`.
         *
         *     **`panel_context` dejó de ser obligatorio · reverificado contra
         *     `75b8ecc` el 2026-09-25.** Ahora el handler exige **exactamente uno** de
         *     `panel_context` o `tab_context` —`if (req.PanelContext == nil) ==
         *     (req.TabContext == nil)` devuelve 400— y su propio comentario cita la
         *     tarea: «exactamente uno de panel_context o tab_context (F3.15)».
         *
         *     **Es lo que pedimos el 2026-09-25 y lo hicieron el mismo día.** Y es lo
         *     que F3.15 esperaba: su candado dice «el cable exige un panel», y ya no.
         *     Queda anotado y **no se toma** — un candado vencido se dice y se
         *     pregunta.
         */
        ChatAskRequest: {
            question: string;
            /**
             * @description **La presencia del chat en la consola** · el `.pen` lo dibuja en las
             *     quince pantallas y colgaba de un panel. Con esto la pregunta puede
             *     ser de la pestaña entera.
             */
            tab_context?: {
                /** Format: uuid */
                tab_id: string;
                /** @example 2026-09 */
                period: string;
            };
            panel_context?: {
                /** Format: uuid */
                panel_id: string;
                /**
                 * @description `YYYY-MM`, validado con `^\d{4}-(0[1-9]|1[0-2])$` en
                 *     `dd_chat_service.go`. Otro formato devuelve 400 con
                 *     «período inválido, formato esperado YYYY-MM».
                 * @example 2026-09
                 */
                period: string;
            };
            /**
             * Format: int64
             * @description **Es un ENTERO, no un uuid.** Sale del frame `thread_info` y es lo
             *     que continúa la conversación. Ausente en la primera pregunta.
             */
            thread_id?: number | null;
        };
        /**
         * @description `event: thread_info`. **Siempre es la primera trama**, la emite `pump`
         *     antes de abrir el stream del agente.
         */
        ChatFrameThreadInfo: {
            /**
             * Format: int64
             * @description El que se manda de vuelta en `ChatAskRequest.thread_id`.
             */
            thread_id: number;
            /** Format: int64 */
            parent_message_id: number;
            /**
             * Format: uuid
             * @description El `:id` de `GET /config/chat/threads/{id}/messages`. **No sirve
             *     para continuar la conversación** — para eso va `thread_id`.
             */
            user_thread_id: string;
        };
        /**
         * @description `event: thinking`. **Tres formas distintas bajo un mismo nombre**, según
         *     de qué evento de Cortex salga: `{text}`, `{status, message}` o
         *     `{tool, status}`. Ninguna propiedad es obligatoria.
         */
        ChatFrameThinking: {
            text?: string;
            status?: string;
            message?: string;
            tool?: string;
        };
        /**
         * @description `event: delta`. Un fragmento de la respuesta. Se concatenan en orden.
         *     **La clave es `text`**, no `delta` como en el contrato.
         */
        ChatFrameDelta: {
            text: string;
        };
        /**
         * @description `event: sql`. El SQL que corrió el agente. **No trae fuentes
         *     consultadas ni límite declarado**: el agente los escribe dentro del
         *     markdown, como secciones `### Fuentes consultadas` y
         *     `### Límite declarado`.
         */
        ChatFrameSQL: {
            sql: string;
            tool?: string;
        };
        /**
         * @description `event: data`. Lo que `StructuredDataFromCortex` produjo.
         *
         *     **`shape` es la FORMA del valor, no el tipo de panel**, y `provenance`
         *     **no trae la BASE ni la capa Medallion** — los dos huecos por los que
         *     F3.6 sigue bloqueada. Se transcribe igual: describir el cable no es
         *     usarlo.
         */
        ChatFrameData: {
            /**
             * @description La forma de la métrica, o `tabular` si esa falló, o `raw` si no se
             *     pudo transformar nada.
             */
            shape: string;
            data: unknown;
            /**
             * @description **Creció el 2026-09-22 con `55e8419`**, que es lo que destrabó F3.6.
             *     Antes traía sólo las cinco primeras y no alcanzaba: `EventoDato`
             *     exige `familia` y los cinco campos de `Gobierno`.
             */
            provenance: {
                /** @example cortex_agent */
                source: string;
                tool?: string;
                metric_key: string;
                period: string;
                sql_available: boolean;
                /** @description El denominador y la ventana de la métrica. */
                base: string;
                /**
                 * @description `catalog` cuando la BASE salió del catálogo, vacío si no hay
                 *     base. **Es la declaración de que la BASE es la de la MÉTRICA**,
                 *     no una calculada para esta cifra en particular.
                 */
                base_source: string;
                /** @description Con qué familia se pinta. */
                family: string;
                /** @description La capa Medallion. */
                layer: string;
                source_system: string;
                catalog_version: number;
                /**
                 * @description RFC 3339 de la **última materialización de la métrica**. Cadena
                 *     vacía si nunca se materializó.
                 */
                freshness: string;
                /**
                 * @description RFC 3339 del momento en que **el agente produjo esta cifra**.
                 *     Lo pone el servicio al recibir el `tool_result`, así que sólo
                 *     viene cuando el agente consultó de verdad.
                 *
                 *     **No es lo mismo que `freshness` y confundirlos es el bug**: una
                 *     describe cuándo se materializó el panel y la otra cuándo se
                 *     calculó este número.
                 */
                queried_at: string;
            };
        };
        /**
         * @description `event: error`. Terminal: siempre lo sigue un `done`.
         *
         *     **No declara si lo ya recibido sigue valiendo**, que es el `parcial` del
         *     contrato. Lo que sí hace el servicio es persistir la respuesta
         *     acumulada —`defer s.persistAssistant(st)` en `pump`— antes de cerrar.
         */
        ChatFrameError: {
            /**
             * @description `upstream_error` cuando el agente falla sin código propio, y
             *     `empty_stream` cuando el stream cerró sin texto, sin dato y sin
             *     error.
             */
            code: string;
            message: string;
        };
        /**
         * @description `event: done`. **El objeto vacío `{}`**: no trae el id del hilo. El id
         *     llegó en `thread_info`, al principio.
         */
        ChatFrameDone: Record<string, never>;
        /**
         * @description `ports.DDChatThreadDTO`. Un hilo del chat contextual, ya cruzado con el
         *     tab y la métrica de donde salió.
         *
         *     **Los dos ids no son intercambiables, y confundirlos es el bug.**
         *     `id` es el uuid de `user_threads` y es el `:id` de
         *     `GET /config/chat/threads/{id}/messages`; `thread_id` es el entero que
         *     se manda de vuelta en `ChatAskRequest.thread_id` para continuar la
         *     conversación. Mandar el uuid donde va el entero da 400.
         *
         *     **Casi todo lo del panel es opcional**: los hilos abiertos antes de que
         *     existiera el contexto de panel no lo tienen.
         */
        ChatThread: {
            /** Format: uuid */
            id: string;
            /** Format: int64 */
            thread_id: number;
            thread_name: string;
            /** Format: uuid */
            agent_id: string;
            agent_name: string;
            role: string;
            /** @description La primera pregunta del hilo, tal como se escribió. */
            first_message_preview: string;
            /** Format: int64 */
            last_message_id?: number | null;
            /** Format: uuid */
            panel_id?: string | null;
            /**
             * @description `YYYY-MM`. **Cadena vacía cuando el hilo no tiene panel**, no
             *     `null`: el struct lo declara `string` con `omitempty`.
             */
            period?: string;
            /** Format: uuid */
            tab_id?: string | null;
            tab_name?: string;
            /** Format: uuid */
            metric_id?: string | null;
            metric_key?: string;
            metric_name?: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        /**
         * @description `ports.DDChatSuggestion`. Una pregunta que el servicio propone para este
         *     panel.
         * @example {
         *       "question": "¿Por qué Ventas está en USD 4.28M en septiembre?",
         *       "intent": "explain"
         *     }
         */
        ChatSuggestion: {
            /** @description La pregunta, ya redactada en español y lista para mandar. */
            question: string;
            /**
             * @description `explain`, `compare`, `drivers`, `breakdown`, `forecast` o `data`.
             *
             *     **El front no lo usa y por eso el adaptador lo descarta.** §PEN:C3
             *     dibuja las sugeridas como chips con su texto y nada más; conservar
             *     un campo que ninguna pantalla lee es cómo `BodyProps.presentation`
             *     estuvo meses declarada sin un solo consumidor.
             */
            intent: string;
        };
    };
    responses: {
        /** @description Request mal formado */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Token ausente, inválido, o sin `role_id` en los claims */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description No existe, o no es de este tenant */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Falla interna */
        ServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Contexto */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["ContextResponse"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["ServerError"];
        };
    };
    getCatalog: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Catálogo */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["CatalogMetric"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getBlocks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Reglas de bloque */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["BlockRule"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getTab: {
        parameters: {
            query?: {
                /**
                 * @description Sin él, el layout publicado del tenant. Con él, valida que el layout
                 *     sea del tenant y que la tab sea de ese layout — permite borradores.
                 */
                layoutId?: string;
            };
            header?: never;
            path: {
                tabId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pestaña con paneles */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["TabWithPanels"];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    batchPanels: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchRequest"];
            };
        };
        responses: {
            /** @description Mapa panelId → payload */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: {
                            [key: string]: components["schemas"]["Payload"];
                        };
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    updatePreferences: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    theme: "dark" | "light";
                    /**
                     * Format: uuid
                     * @description `null` limpia la preferencia y vuelve a la resolución por
                     *     rol. Ausente la deja como está.
                     */
                    preferred_dashboard_id?: string | null;
                };
            };
        };
        responses: {
            /** @description El tema guardado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: {
                            /** @enum {string} */
                            theme: "dark" | "light";
                        };
                    };
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    askChat: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatAskRequest"];
            };
        };
        responses: {
            /**
             * @description El stream. El esquema es `string` porque OpenAPI no describe tramas
             *     SSE; las formas de cada `data:` están en los `ChatFrame*` de
             *     `components/schemas`, que existen para que el traductor tipe contra
             *     algo y no contra structs de Go leídos a mano.
             */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /** @description El rol no ve el tab o la métrica del panel */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            404: components["responses"]["NotFound"];
            /** @description No hay agente activo para el tenant y el rol */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Rate limit por usuario, compartido con `/chat/*`. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listChatThreads: {
        parameters: {
            query?: {
                /**
                 * @description Filtra a los hilos abiertos desde ese panel. Es lo que permite que
                 *     la hoja de un panel muestre sus propias conversaciones.
                 */
                panel_id?: string;
                /**
                 * @description **Nuevo · reverificado contra `75b8ecc` el 2026-09-25.** El par del
                 *     `tab_context` de `POST /config/chat`: con el chat presente en la
                 *     pestaña, el riel tiene que poder mostrar los hilos de esa pestaña y
                 *     no los de un panel · F3.15.
                 */
                tab_id?: string;
                /** @description `YYYY-MM`. Otro formato devuelve **400**, no una lista vacía. */
                period?: string;
                /**
                 * @description Sin valor, o `<= 0`, el servicio usa **50**; por encima de **200**
                 *     lo recorta. Lo hace `clampLimit`.
                 */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Los hilos, del más reciente al más viejo */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["ChatThread"][];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    panelChatSuggestions: {
        parameters: {
            query?: {
                /** @description `YYYY-MM`. Otro formato devuelve 400. */
                period?: string;
            };
            header?: never;
            path: {
                panelId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Entre una y cuatro preguntas */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["ChatSuggestion"][];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /** @description El rol no ve el tab o la métrica del panel */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
}
