/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/config/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Contexto del usuario del token
         * @description `DDConfigHandler.GetMe`. Las tabs salen del layout publicado del tenant,
         *     filtradas por `roles.tab_ids`. El filtrado por rol lo hace el servidor.
         */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Métricas del tenant, filtradas por rol
         * @description `data` es un **arreglo desnudo**, no `{ metrics: [...] }`. Sale de
         *     `SendSuccess(c, 200, metrics)` con `[]domain.DDCatalogMetric`.
         */
        get: operations["getCatalog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/blocks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * La tabla tipo ↔ formas ↔ rangos de span
         * @description Catálogo GLOBAL, no por tenant. Sale de la tabla `blocks`. `data` también
         *     es un arreglo desnudo.
         */
        get: operations["getBlocks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/plots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * El repertorio de gráficos, con sus mínimos y sus topes
         * @description **B1.21 · LA ESCRIBIMOS NOSOTROS** · `b6f0e09` en
         *     `feature/config-plots` del fork, medida el 2026-09-29: **200 con 49
         *     entradas en 5 ms**. Estuvo pedida tres veces y no llegaba; la tabla era
         *     nuestra entera, así que lo que faltaba era la ruta.
         *
         *     ── **CONTRA UPSTREAM DA 404** · medido el 2026-10-01 ────────────────────
         *
         *     Levantado `d9147c3` —su rama, limpia— esta ruta **no existe**: `git grep`
         *     no encuentra `config/plots` en una sola línea de su código, y el servicio
         *     contesta 404. Upstream no tomó `b6f0e09`.
         *
         *     **Y eso se vio recién hoy porque el binario de `:4010` era el fork.** Es
         *     la trampa registrada en `CLAUDE.md` —«antes de medir, mirá qué binario
         *     está corriendo»— con la cara más cara: no hace que su código se vea como
         *     avance, hace que **nuestra propia ruta se vea como suya**. Comprobado
         *     levantando los dos: el viejo da 200 con 49 filas, `d9147c3` da 404.
         *
         *     **Lo que se apaga sin ella:** el selector de gráfico del builder entero.
         *     `PanelConfigurator` declara que un repertorio vacío apaga la sección —«un
         *     control que se abre vacío promete una elección que no se puede hacer»—
         *     así que contra upstream **no hay forma de elegir gráfico**, ni de ver el
         *     que el panel ya tiene. La consola sigue dibujando: el `chart` viaja en el
         *     layout y los cuerpos despachan sin el repertorio.
         *
         *     Catálogo **GLOBAL, no por tenant** —qué puede dibujar un gráfico no
         *     depende del cliente— y `data` es un **arreglo desnudo**, igual que
         *     `blocks`. Eso último fue una decisión al escribirla: envolverlo en
         *     `{"plots": [...]}` era más prolijo y obligaba a un segundo adaptador
         *     para dos rutas que son la misma cosa.
         *
         *     Las 49 filas están **generadas y no transcritas** —`tools/gen-plots.py`,
         *     desde el repertorio de v2, el `.pen`, la decisión de los mínimos y el
         *     mapa de formas del adaptador—. Pedirle al backend transcribir 49 filas
         *     de una tabla markdown era el modo de falla que ya costó quince filas mal
         *     en otra tabla.
         */
        get: operations["getPlots"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/tabs/{tabId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * La composición de una pestaña, sin datos
         * @description Paneles filtrados por `roles.hidden_metric_ids` y con
         *     `roles.layout_overrides` ya aplicados. Un `tabId` que no pertenece al
         *     tenant devuelve **404**, no 403.
         */
        get: operations["getTab"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/panels:batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Los payloads de varios paneles en una llamada
         * @description **Los dos campos del body son `required` en el binding de Gin**, así que
         *     un nombre equivocado devuelve 400 y no un batch vacío. `panel_ids` pide
         *     `min=1`.
         *
         *     Lee `dd_panel_data`, nunca Snowflake. La clave del mapa de respuesta es
         *     el `panel_id` en texto.
         */
        post: operations["batchPanels"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/me/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Persistir el tema del usuario
         * @description Escribe `users.theme`. **Y desde el 2026-09-26 SÍ se puede leer**:
         *     `/config/me` devuelve `user.theme` (B1.1). Acá decía «no hay ruta para
         *     leerlo, la preferencia se guarda y no se puede recuperar», que era cierto
         *     cuando se transcribió y dejó de serlo sin que nada avisara — el chequeo
         *     sólo miraba los campos que el yaml exige, no los que el servicio agrega.
         */
        put: operations["updatePreferences"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Preguntar desde un panel · stream SSE
         * @description **Transcrita el 2026-09-21 desde `82da946`**, no desde `733c13c` como el
         *     resto de este archivo: la ruta no existía cuando se transcribió lo demás.
         *     Leído `internal/adapters/handler/dd_chat_handler.go` (el handler),
         *     `internal/core/services/dd_chat_service.go` (`pump`, que arma los frames)
         *     y `internal/core/services/cortex_sse.go` (los siete nombres de evento).
         *
         *     **La respuesta NO es JSON: es `text/event-stream`**, y cada trama lleva
         *     DOS líneas — `event: <nombre>` y `data: <json>`. **El discriminador está
         *     en la línea `event:`**, no adentro del JSON, que es lo contrario de lo
         *     que declara `EventoDeChat` del contrato. Por eso hay traducción en
         *     `src/api/chat.ts` y no un `JSON.parse` a secas.
         *
         *     `panel_context` es `binding:"required"` con `panel_id` `uuid`: sin
         *     contexto de panel la llamada devuelve 400. No hay chat sin panel.
         */
        post: operations["askChat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Los agentes activos de todos los tenants · sólo admin
         * @description `ChatHandler.ListAgents` → `AgentService.ListAll` → `ports.AgentOption`.
         *     **Sólo `is_active = true`**, y de todos los tenants: un admin de
         *     plataforma puede preguntarle al agente de otro cliente.
         */
        get: operations["listChatAgents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/chat/threads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Los hilos del usuario, con el panel del que salieron
         * @description **Transcrita el 2026-09-21 desde `82da946`**, leyendo
         *     `internal/core/ports/dd_chat_service.go` —`DDChatThreadDTO`— y
         *     `internal/adapters/handler/dd_chat_handler.go` —`ListThreads`—.
         *
         *     **Devuelve un ARREGLO DESNUDO dentro del envelope**, no un objeto con
         *     una clave: `SendSuccess(c, http.StatusOK, threads)`.
         *
         *     **Trae los DOS ids, y no son intercambiables** — ver `ChatThread`.
         */
        get: operations["listChatThreads"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/panels/{panelId}/chat-suggestions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Qué preguntar sobre este panel
         * @description **Transcrita el 2026-09-21 desde `82da946`**, leyendo
         *     `internal/core/services/dd_chat_suggestions.go` y el handler
         *     `DDChatHandler.Suggestions`.
         *
         *     **Determinista y sin Cortex**: las arma `SuggestQuestions` con el
         *     contexto del panel —su forma, su estado y su valor—, así que **no
         *     gasta la cuota del agente** y no puede tardar.
         *
         *     **Cambian con el ESTADO del panel.** Un panel sin datos sugiere «¿Qué
         *     falta para que … tenga datos?»; uno con cifra sugiere por qué está en
         *     ese nivel, cómo se compara y qué la impulsa. Son entre 1 y 4.
         *
         *     **Sin `period` el servicio usa el mes actual en UTC**, que no es el del
         *     tenant. El front lo manda siempre: es el período que se está mirando.
         */
        get: operations["panelChatSuggestions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/panels/{panelId}/drilldown/dimensions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Por qué dimensiones se puede desagregar este panel
         * @description `DDDrillDownHandler.Dimensions` → `ddDrillDownService.Dimensions`.
         *
         *     **Es una lectura barata, y eso es lo que la hace útil al pintar.**
         *     Resuelve el rol, autoriza el panel y consulta `sfspec.DrillRegistry`,
         *     que es un mapa en memoria: **no toca Snowflake, no firma un JWT y no
         *     usa el agente**. Se le puede preguntar por cada panel de la pestaña.
         *
         *     Con eso la consola sabe si dibuja el CTA de «ver detalle» — la regla de
         *     la casa es que **un CTA sin manejador no se pinta**, y acá el manejador
         *     existe sólo cuando `supported` es `true`.
         *
         *     **No lleva el rate limit del chat**; el POST sí. Lo dice el router:
         *     `config.GET("/panels/:panelId/drilldown/dimensions", …)` sin
         *     `chatLimiter`.
         *
         *     **No toma `period`.** Qué dimensiones existen es de la métrica, no del
         *     mes que se está mirando.
         *
         *     **Medida en las quince del `overview`, una por una** · 2026-09-30 · y el
         *     reparto es 7/8, con tres juegos de dimensiones distintos:
         *
         *     · `sales`, `investment`, `roas` → `['day', 'week', 'platform']`
         *     · `orders`, `visits`, `units` → `['day', 'week']`
         *     · `investment_by_platform` → **`['day']` y nada más**: su spec declara una
         *       sola dimensión, la de día sobre la tabla de medios pagos
         *
         *     Las ocho con `supported: false` y `dimensions: []` son
         *     `executive_summary`, `decisions`, `goals_vs_actual`, `daily_trend`,
         *     `twelve_month_efficiency`, `platform_gap`, `platform_month_matrix` y
         *     `spend_flow`.
         *
         *     **La clave que viaja es la del CATÁLOGO, no la canónica**, y es por donde
         *     se entra a equivocarse: el registry se consulta con
         *     `CanonicalKey(metric.Key)` —`sales` → `revenue`, `visits` → `sessions`,
         *     `investment_by_platform` → `platform_return`— pero `metric_key` devuelve
         *     la del catálogo. Buscar `revenue` en esta respuesta no encuentra nada.
         */
        get: operations["panelDrillDownDimensions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/panels/{panelId}/drilldown": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Desagregar la métrica del panel por una dimensión · Snowflake en vivo
         * @description `DDDrillDownHandler.Query` → `ddDrillDownService.Query`.
         *
         *     **Esta sí consulta Snowflake, en vivo y con las credenciales del
         *     tenant**: resuelve el agente del tenant y del rol, firma un JWT, arma el
         *     SQL del registry y corre la consulta con timeout —20 s, o
         *     `DD_DRILLDOWN_TIMEOUT_SECONDS`—. **No persiste nada**: no escribe hilo
         *     ni materialización.
         *
         *     **Comparte la cuota del chat.** `config.POST("/panels/:panelId/drilldown",
         *     chatLimiter, …)` es el mismo `UserRateLimitMiddleware` que
         *     `POST /config/chat` —100 pedidos por usuario por minuto por defecto,
         *     `RATE_LIMIT_ENABLED` y `RATE_LIMIT_PER_USER_PER_MINUTE`—, así que abrir
         *     hojas de detalle gasta la misma cuota que preguntarle al agente.
         *
         *     **El nombre de columna NUNCA sale del input.** `dimension` se busca en
         *     la lista blanca de `DrillRegistry`; lo que viaja al SQL es la expresión
         *     que el registry declara. Lo que llega del cliente se compara
         *     `strings.ToLower(strings.TrimSpace(...))` y si no está, 400 con las
         *     soportadas.
         *
         *     ── **LAS PARTES NO SUMAN EL TOTAL DEL PANEL, Y HAY DOS RAZONES** ──────
         *
         *     Medido sobre `sales` (`80158182-…`, `2026-09`) el 2026-09-30, y es lo
         *     primero que la hoja de C2 tiene que no prometer:
         *
         *     1. **`platform` sale de OTRA TABLA y con OTRA MEDIDA.** `day` y `week`
         *        agregan `REV_TOTAL` del hecho de ecommerce; `platform` agrupa por
         *        `FUENTE` sobre la tabla de medios pagos y suma `INGRESOS_USD`. Medido:
         *        `day` y `week` dan **1 282 259** las dos, y `platform` da
         *        **968 169,49** — no es un error de redondeo, es el ingreso atribuido
         *        a medios pagos contra el total del sitio, que es justo lo que la BASE
         *        del panel dice («ALL CHANNELS»).
         *     2. **El panel es una foto y esto es en vivo.** El escalar del panel traía
         *        `1 232 721` con `freshness: 2026-09-30T17:37:34Z`, y la suma por día
         *        pedida a las 00:07 UTC daba `1 282 259`: el mes está en curso y la
         *        materialización es de siete horas antes. `queried_at` y `freshness`
         *        **no son lo mismo y confundirlos es el bug**, igual que en
         *        `ChatFrameData`.
         *
         *     **Y la respuesta no trae gobierno.** Ni BASE, ni capa, ni fuente, ni
         *     frescura: nueve campos y ninguno es de procedencia. El encabezado de la
         *     hoja los tiene que tomar del panel de origen —`POST /config/panels:batch`
         *     los trae— porque §8 pide que toda métrica declare su BASE y su
         *     PROCEDENCIA, y una cifra desagregada sigue siendo la métrica.
         */
        post: operations["panelDrillDown"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Envelope: {
            /** @enum {boolean} */
            success: true;
        };
        /**
         * @description `ports.AgentOption` de `internal/core/ports/agent.go` en `7b717aa`.
         *     **`target_role` es el NOMBRE del rol tal como está guardado**, con su
         *     mayúscula: en QA conviven `Planner` y `admin`.
         */
        ChatAgentOption: {
            /** Format: uuid */
            id: string;
            /** @description Puede traer espacios al final · medido en QA, «Terpel Lubricantes ». */
            name: string;
            target_role: string;
            /** Format: uuid */
            tenant_id: string;
            tenant_name: string;
        };
        /**
         * @description **`error` es una CADENA, no un objeto.** `handler/response.go`:
         *
         *         type Response struct {
         *             Success bool        `json:"success"`
         *             Data    interface{} `json:"data,omitempty"`
         *             Error   string      `json:"error,omitempty"`
         *         }
         *
         *     No es el envelope de §4.1 del contrato, que declara
         *     `{ codigo, mensaje, campo, desbloqueaCon }`. Leer esta cadena como objeto
         *     da `code: undefined` y `message: ""` — una pantalla de error sin una
         *     palabra. Es el mismo defecto por el que existe `api/auth.ts`.
         */
        ErrorResponse: {
            /** @enum {boolean} */
            success: false;
            /**
             * @description **El mensaje, y NO siempre en español** · remedido el 2026-09-28
             *     contra `5924bf2b`.
             *
             *     Su respuesta de ese día dice que «`error` sigue siendo el mensaje en
             *     español de siempre». **No lo es**, y este campo ya lo tenía
             *     transcripto desde antes: los dos ejemplos de abajo son literales
             *     medidos.
             *
             *     **No es una política, son handlers sueltos**: los errores del revert
             *     salen redactados y en español —«el layout no tiene una versión
             *     anterior a la que volver; indique to_layout_id»—.
             *
             *     **Y esto llega a la pantalla tal cual.** `client.ts` lo pasa sin
             *     tocarlo —redactar el error del servidor sería el front inventando— y
             *     `ErrorState` lo pinta como `phrase`. Un usuario puede ver el nombre
             *     de un struct de Go y el tag de un validador. Va pedido.
             * @example tab not found
             * @example invalid request: Key: 'DDBatchRequest.PanelIDs' Error:Field validation for 'PanelIDs' failed on the 'required' tag
             */
            error: string;
            /**
             * @description **B0.4 · llegó el 2026-09-28**, y es lo que hace accionable un error.
             *
             *     Forma: `FAMILIA_DETALLE`. **Se decide por la FAMILIA** —el prefijo
             *     hasta el primer `_`—: ellos suman detalles sin avisar, así que un
             *     `switch` sobre el valor entero se rompe solo.
             *
             *     Familias: `VALIDATION` (400/422), `AUTH` (401/403), `NOT_FOUND`
             *     (404), `CONFLICT` (409), `RATE_LIMIT` (429), `INTERNAL` (5xx).
             *
             *     **Medido en cuatro**, una llamada por familia: `AUTH_UNAUTHORIZED`
             *     sin token, `NOT_FOUND_RESOURCE` con una pestaña inexistente,
             *     `AUTH_FORBIDDEN` pegándole a `/admin/*` con token de planner, y
             *     `VALIDATION_REQUEST` mandando `theme: "morado"`.
             *
             *     Si una ruta no fija un detalle propio sale el genérico de su familia.
             * @example AUTH_UNAUTHORIZED
             * @example NOT_FOUND_RESOURCE
             * @example AUTH_FORBIDDEN
             * @example VALIDATION_REQUEST
             * @example CONFLICT_NOT_DRAFT
             */
            code: string;
        };
        /**
         * @description `ports.DDContextResponse`.
         *
         *     ── **B1.1 LLEGÓ A MEDIAS** · medido campo por campo el 2026-09-28 contra
         *     `5924bf2b` ────────────────────────────────────────────────────────────
         *
         *     El pedido tenía seis cosas. **Llegaron tres** —`scope` con sus tenants,
         *     el grano de cada período, y `icon`/`chat_suggestions` en la pestaña— y
         *     por eso B1.1 **sigue en ⚠️**: cerrarla sería el defecto de «el criterio
         *     se cumple a medias y nadie lo bajó».
         *
         *     **Lo que sigue faltando**, medido sobre la respuesta real: `tenant`
         *     trae `id`, `name`, `locale`, `currency` y `timezone` —no `etiqueta`—;
         *     `role` trae `id` y `name` —no `puedeAprobar`—; `user` trae `id`,
         *     `email`, nombre y `theme` —no `capacidades`—; y la pestaña no trae
         *     `key`.
         *
         *     **`tenant.vertical` salió del pedido y no es un olvido**: §3.5 declara
         *     `vertical` **y** `plantillaOrigen`, y ese mecanismo no existe de ninguno
         *     de los dos lados · `docs/DECISIONES-2026-09-28-estado-y-vertical.md`.
         */
        ContextResponse: {
            user: components["schemas"]["UserInfo"];
            tenant: components["schemas"]["TenantInfo"];
            role: components["schemas"]["RoleInfo"];
            /**
             * @description ── **PUEDE SER `null`, Y SE MIDIÓ ROMPIENDO LA CONSOLA** · 2026-09-26
             *
             *     Estaba declarado `array` a secas y está en `required`, así que el
             *     adaptador hacía `w.tabs.map(...)` sin mirar. **Un dashboard sin
             *     layout publicado devuelve `tabs: null`** —no `[]`— y ahí el
             *     adaptador tira.
             *
             *     Se encontró al crear un segundo dashboard para poder verificar F5.1:
             *     `POST /admin/tenants/{tenantId}/dashboards` deja crearlo sin layout,
             *     que es el estado normal de uno recién creado. Con la preferencia
             *     apuntada ahí, la consola muestra «No se pudo cargar tu contexto ·
             *     sin detalle del servidor» — y el fallo era nuestro.
             *
             *     **Sigue en `required`**: la clave viaja siempre, lo que cambia es
             *     que su valor puede ser nulo.
             */
            tabs: components["schemas"]["TabMeta"][] | null;
            /**
             * @description **Cadenas sueltas, no objetos.** `availablePeriods()` devuelve los
             *     últimos doce meses del CALENDARIO contando desde `time.Now()`, tenga
             *     o no tenga materialización. No traen etiqueta, rango, estado ni
             *     grano.
             */
            periods: string[];
            /**
             * @description **Cuál de los doce está EN CURSO**, o sea incompleto. El resto están
             *     cerrados.
             *
             *     **Es del fork** —lo escribimos nosotros en `2fafe82`, B1.27— y
             *     `82da946` no lo trae: contra el servicio desplegado este campo **no
             *     llega**, y el selector se comporta como antes. Medido el 2026-09-22
             *     levantando upstream limpio al lado.
             *
             *     Sin él, el mes en curso se ofrece igual que los cerrados y alguien
             *     compara septiembre con nueve días contra agosto entero y lee una
             *     caída que es «el mes todavía no terminó» · F1.42.
             *
             *     **No se deduce contra `new Date()`**: el corte del día es del tenant
             *     y su huso, no del navegador · la regla de las dos zonas horarias.
             * @example 2026-09
             */
            open_period?: string;
            /**
             * @description Los dashboards que el rol ve. **Con más de uno, la consola necesita
             *     un selector** · F5.1.
             */
            dashboards?: {
                /** Format: uuid */
                id: string;
                name: string;
                slug: string;
                is_default: boolean;
                /**
                 * @description **Cuántos meses de histórico ofrece ESTE dashboard**, contando
                 *     el mes en curso · llegó con `d9147c3`, medido el 2026-10-01.
                 *
                 *     La profundidad dejó de ser una constante de doce: la decide el
                 *     admin al crear el dashboard y el servicio la acota entre 1 y
                 *     120 —`VALIDATION_HISTORY_MONTHS` fuera de rango—. **Un
                 *     dashboard que no la declara sigue dando doce**, que es lo que
                 *     pedimos para no romper los que ya existen.
                 *
                 *     Viaja **por dashboard y no sólo en `periods`** porque el
                 *     usuario puede cambiar de dashboard sin recargar: `periods` es
                 *     la del activo, y ésta es la de cada uno.
                 * @example 12
                 */
                history_months: number;
            }[];
            /**
             * Format: uuid
             * @description El resuelto, y el orden de resolución lo declara su comentario:
             *     **preferencia del usuario > rol > default del tenant**. Ausente si
             *     no hay ninguno.
             */
            active_dashboard_id?: string;
            /**
             * Format: uuid
             * @description El layout del dashboard activo. **`null` cuando ese dashboard no
             *     tiene layout publicado**, medido el 2026-09-26 contra un dashboard
             *     recién creado — y ahí `tabs` también viene `null`. Los dos juntos
             *     son el estado «existe pero no se compuso todavía».
             */
            active_layout_id?: string | null;
            catalog_version: number;
            /**
             * @description El grano de **todos** los `periods` · B1.1 · medido `"month"`.
             *
             *     `week` queda declarado para cuando exista dato semanal, y entonces
             *     `periods_detail[].grain` lo dirá por período. **Hoy no se emite**:
             *     está acá porque ellos lo declaran, no porque se haya visto.
             * @enum {string}
             */
            period_grain: "month" | "week";
            /**
             * @description El mismo juego de `periods`, con sus bordes resueltos. `periods` no
             *     cambió: esto se suma al lado.
             *
             *     **`[start, end)`** — el fin es exclusivo, y eso lo dice el dato
             *     medido: `2026-09` va de `2026-09-01` a `2026-10-01`.
             */
            periods_detail: {
                /** @example 2026-09 */
                key: string;
                /** @enum {string} */
                grain: "month" | "week";
                /**
                 * Format: date
                 * @example 2026-09-01
                 */
                start: string;
                /**
                 * Format: date
                 * @example 2026-10-01
                 */
                end: string;
            }[];
            /**
             * @description Qué clientes ve este usuario · lo que el contrato llama `alcance` con
             *     `tenantsDisponibles`.
             *
             *     **Medido con los dos usuarios de la base local**: con el token de
             *     `planner` sale `single_tenant` y un solo tenant; el selector de
             *     cliente del navbar sólo tiene sentido con `multi_tenant`.
             */
            scope: {
                /** @enum {string} */
                kind: "single_tenant" | "multi_tenant";
                /** @description **Nunca `null`** · lo declaran ellos. */
                tenants: {
                    /** Format: uuid */
                    id: string;
                    /** @example Under Armour México */
                    name: string;
                    /**
                     * @description **La forma corta, y acá es DONDE SE USA.** Llegó en
                     *     `f70cec2` junto a `tenant.label` y el cable la declaraba
                     *     sólo en el tenant activo — medido el 2026-09-28: el
                     *     servicio la manda también en cada entrada de `tenants`.
                     *
                     *     **El selector de cliente del navbar es el navbar**, que es
                     *     para lo que la forma corta existe. Mientras el adaptador
                     *     leyó `name` acá, el selector decía «UNDER ARMOUR MÉXICO»
                     *     con la cabecera al lado diciendo la corta: se vio abriendo
                     *     la aplicación, no en una prueba.
                     *
                     *     El servicio la hace caer a `name` cuando el tenant no la
                     *     define, así que se lee siempre y sin respaldo.
                     * @example UA México
                     */
                    label: string;
                }[];
            };
        };
        /** @description El nombre llega partido; el contrato lo pide junto. */
        UserInfo: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            first_name: string;
            last_name: string;
            /**
             * @example light
             * @enum {string}
             */
            theme: "light" | "dark";
        };
        TenantInfo: {
            /**
             * @description **La forma corta para el navbar** · pedida en B1.1 y llegó el
             *     2026-09-28. El `.pen` pinta `UA MX` donde mostrábamos
             *     `Under Armour México`.
             *
             *     **Si el tenant no la define vale `name`**, y eso lo hacen ellos: «pueden
             *     pintar `label` siempre y olvidarse del fallback». Medido con el tenant
             *     local, que no la definió: `label` y `name` traen lo mismo.
             *
             *     Sale también en cada `scope.tenants[].label`.
             * @example UA MX
             */
            label: string;
            /** Format: uuid */
            id: string;
            /** @example Under Armour México */
            name: string;
            /**
             * @description Etiqueta BCP 47. **El valor de hoy es el default de la migración, no
             *     el del cliente**: el tenant «Under Armour México» trae `es-CO` con
             *     `COP` y `America/Bogota`, medido el 2026-09-26. Se corrige con
             *     `PUT /admin/tenants/{tenantId}`, que también llegó en `8633b10` — es
             *     dato a cargar, no un defecto del campo.
             * @example es-CO
             * @example es-MX
             */
            locale: string;
            /**
             * @description Código ISO 4217.
             *
             *     **NO es la moneda del país del cliente, y confundirlas es el bug.**
             *     Para UA MX vale `USD` — decidido el 2026-10-01 (producto) y medido
             *     el mismo día contra las tres fuentes que mandan acá:
             *
             *     · el **catálogo de Snowflake** declara `unit: USD` en las cinco
             *       métricas de dinero —`revenue`, `spend`, `spend_flow`,
             *       `platform_gap`, `platform_month_matrix`— y su texto de gobierno
             *       dice «Venta total del sitio … **en USD**»;
             *     · el **`.pen`** escribe `USD` en **62 de sus 63 nodos con moneda**;
             *       el único `MXN` es `A2 · Ficha · tenant en alta`, que dibuja otro
             *       cliente;
             *     · y el `locale` es independiente: `es-MX` decide los separadores
             *       —`1,232,721`— y no la divisa.
             *
             *     **El front no deriva ninguna cifra de este campo**: la unidad de un
             *     valor sale del `unit` de su métrica en el catálogo, que es quien
             *     conoce el dato. Este campo se ve en la ficha del cliente y, sobre
             *     todo, **lo lee el agente al redactar la prosa** — con `COP` escribía
             *     «los ingresos alcanzaron COP 1.144.876» sobre cifras que son
             *     dólares.
             * @example USD
             */
            currency: string;
            /**
             * @description IANA. **Del tenant y uno solo**, aunque tenga tiendas en varios
             *     países: una cifra que cambia según quién la mira no es auditable.
             * @example America/Bogota
             * @example America/Mexico_City
             */
            timezone: string;
        };
        RoleInfo: {
            /** Format: uuid */
            id: string;
            /** @example planner */
            name: string;
        };
        /**
         * @description ── **`icon` y `chat_suggestions` llegaron** · 2026-09-28, medidos contra
         *     `5924bf2b` ────────────────────────────────────────────────────────────
         *
         *     Eran el pedido de **B4.4**, abierto desde el 2026-09-15 cuando F4.8
         *     construyó el editor de pestañas: el builder los podía escribir y la
         *     consola no los recibía.
         *
         *     Entran por `PUT /admin/layouts/{id}` —se recortan, se descartan las
         *     vacías y **el máximo es 8**, más da `422 VALIDATION_CHAT_SUGGESTIONS`— y
         *     salen por acá.
         */
        TabMeta: {
            /** Format: uuid */
            id: string;
            name: string;
            operational_question: string;
            sort_order: number;
            /**
             * @description **La identidad estable de la pestaña dentro del dashboard** · pedida
             *     en B1.1 desde el principio, y llegó el 2026-09-28 por una segunda
             *     razón que ellos levantaron.
             *
             *     `roles.tab_ids` guarda ids de FILA, y las filas se recrean en cada
             *     versión publicada: **la primera publicación real desde el builder
             *     dejaba sin pestañas a todo rol con restricción**. La `key` sobrevive
             *     a las versiones, y la reversión la copia.
             *
             *     Es un slug, única por versión de layout. Ausente en el builder se
             *     deriva del nombre —`Visión General` → `vision-general`—; repetida da
             *     `422 VALIDATION_TAB_KEY`. Las existentes se rellenaron en la
             *     migración: medido, la sembrada trae `overview`.
             * @example overview
             * @example marca
             */
            key: string;
            /**
             * @description **Cadena vacía cuando no hay**, no `null` · medido. La semilla no
             *     trae ninguno, así que hoy llega `""` en las tres rutas que sirven
             *     `TabMeta`.
             * @example
             * @example box
             */
            icon: string;
            /**
             * @description **SIEMPRE lista, nunca `null`** · lo declaran ellos y se midió. Es lo
             *     que permite que el riel las recorra sin guardia — y la diferencia con
             *     `tabs`, que sí llega `null` en un dashboard sin componer.
             *
             *     **No se confunden con las de panel**, que siguen viniendo de
             *     `GET /config/panels/{panelId}/chat-suggestions` y no cambiaron.
             */
            chat_suggestions: string[];
        };
        /**
         * @description `domain.DDCatalogMetric`, serializado con sus etiquetas `json:`.
         *
         *     **`shape`, `family` y `layer` son `string` libre en Go**, no enumerados.
         *     Los valores de abajo son los que el sistema sabe manejar; el servicio no
         *     impide otros, y `sync-catalog` hace upsert de lo que diga una vista de
         *     Snowflake. Cerrarlos es trabajo del adaptador · F1.35.
         *
         *     Le faltan tres campos que el contrato declara: `estado`, `estadoRazon` y
         *     `notaLectura`. **Eran cuatro hasta el 2026-09-26**: `ventana` llegó como
         *     `measurement_window`, abajo.
         */
        CatalogMetric: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tenant_id: string;
            /**
             * @example revenue
             * @example platform_return
             */
            key: string;
            name: string;
            /**
             * @description Las que `materialize.TransformValue` sabe transformar. **Son quince
             *     desde `168a761`** y este texto decía nueve, que era cierto al
             *     transcribirlo: `scalar`, `scalar_with_interval`, `categorical`,
             *     `ranking`, `time_series`, `multi_series`, `tabular`, `prose`,
             *     `composition`, `compared_categorical`, `multi_attribute_profile`,
             *     `matrix`, `graph`, `flow`, `distribution` y `series_with_band`.
             *
             *     **El conteo viejo costó un mensaje equivocado al backend** el
             *     2026-09-25: se citó esta línea como si confirmara una medición
             *     nuestra, y era la misma lectura vieja escrita dos veces.
             *
             *     `distribution` emite `{bins:[{label, v, lo?, hi?}]}`.
             *
             *     **`series_with_band` es ESTRICTA desde `75b8ecc`**, el mismo día que
             *     se pidió: `{level, points:[{t, v, lo, hi}]}`, con `level` de nivel
             *     superior y `lo`/`hi` obligatorios por punto. Su transformer falla con
             *     `ErrMissingField` si falta cualquiera de los tres, así que lo que
             *     llega está completo o no llega — que es lo que deja al front aplicar
             *     «un pronóstico sin banda no se publica» sin tener que adivinar si es
             *     un intervalo faltante o una serie mal etiquetada.
             *
             *     Reverificado contra `75b8ecc` el 2026-09-25.
             * @example scalar
             * @example scalar_with_interval
             * @example time_series
             * @example multi_series
             * @example categorical
             * @example ranking
             * @example tabular
             * @example prose
             * @example composition
             */
            shape: string;
            /**
             * @description De acá sale el color de datos del front.
             * @example demand
             * @example media
             * @example inventory
             * @example customer
             * @example external
             */
            family: string;
            /**
             * @example BRONZE
             * @example SILVER
             * @example GOLD
             */
            layer: string;
            source: string;
            base: string;
            unit?: string | null;
            /**
             * @description **LLEGAN LAS DOS FORMAS, Y EL FRONT LO PINTA CRUDO** · corregido el
             *     2026-09-26, medido contra `8633b10`.
             *
             *     Acá decía «TEXTO que se pinta tal cual, no un código», con fecha y
             *     medición del 2026-09-14. **La medición era correcta y la conclusión
             *     no**: ese día el catálogo tenía sólo las doce métricas de la SEMILLA,
             *     y `dd_seed.go` escribe literal `HIGHER = BETTER`. Se generalizó de la
             *     semilla a Snowflake sin haber visto una fila de Snowflake.
             *
             *     Contado el 2026-09-26 sobre las 18 métricas del tenant, después de
             *     que `sync-catalog` corriera:
             *
             *       · `HIGHER_IS_BETTER`  6  ← de la vista `SYNAPSE_METRIC_CATALOG`
             *       · `HIGHER = BETTER`   8  ← de la semilla de Postgres
             *       · `null`              4
             *
             *     **Y `PanelShell` lo pinta dentro de un `Label` sin mirarlo**, así que
             *     seis paneles muestran `HIGHER_IS_BETTER` con guiones bajos. No es un
             *     defecto nuestro: la regla es que el adaptador no escribe copy de
             *     producto, y el dueño de este texto es el catálogo.
             *
             *     **Está pedido a DATOS**, y su propia vista de validación lo detecta:
             *     la séptima regla de `SYNAPSE_METRIC_CATALOG_ISSUES`. Hasta que las
             *     seis filas se retipeen, el front no lo traduce — traducir acá sería
             *     una tabla de equivalencias que nadie mantiene el día que el texto de
             *     origen cambie.
             * @example HIGHER = BETTER
             * @example HIGHER_IS_BETTER
             */
            semantic_direction?: string | null;
            /**
             * @example day
             * @example week
             * @example month
             */
            min_grain: string;
            /**
             * @description Ventana **ya redactada**, de la columna `MEASUREMENT_WINDOW`.
             *     `string` sin `omitempty`: siempre viene, vacío si no hay.
             * @example Mes calendario seleccionado
             */
            measurement_window: string;
            dimensions: string[];
            catalog_version: number;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        /**
         * @description Una entrada del repertorio · la tabla `plots`.
         *
         *     **Las formas van en el idioma del CABLE** —`scalar`, `time_series`—,
         *     igual que `accepted_shapes` de `BlockRule`, y el adaptador las traduce
         *     con el mismo mapa.
         */
        PlotRule: {
            /**
             * @example donut
             * @example treemap
             */
            id: string;
            /**
             * @description El título en mayúsculas, **transcripto del `.pen`** para los 43 que
             *     dibuja. Es copy de producto: lo pinta el selector del builder.
             * @example DONA
             * @example PARETO
             */
            name: string;
            /** @description Qué formas de dato sabe dibujar, en el idioma del cable. */
            shapes: string[];
            /**
             * @description Regla dura 6 · `series_with_band` sólo admite gráficos con esto en
             *     `true`. Un pronóstico sin banda no se publica.
             */
            supports_band: boolean;
            /**
             * @description Cuántos datos necesita para no engañar, **por forma**.
             *
             *     **Vacío es un valor legítimo y NUNCA llega `null`** · medido el
             *     2026-09-29: seis de los 49 salen `[]` y son exactamente los de
             *     `scalar` y `prose`. Vacío significa «no exige un mínimo» —una cifra
             *     es una cifra—, que es distinto de «no se sabe»; el servicio lo
             *     normaliza para que ningún consumidor tenga que distinguirlos.
             */
            minimums: {
                /** @example categorical */
                shape: string;
                /**
                 * @description La condición, legible y evaluable sobre el valor.
                 * @example items < 2
                 * @example puntos < 2
                 * @example filas < 2 o columnas < 2
                 */
                when: string;
                /**
                 * @description **Copy de producto, se pinta tal cual.** Viene redactada de
                 *     `design.md`; el front no la traduce ni la compone.
                 * @example una barra sola no compara nada
                 */
                reason: string;
            }[];
            /**
             * @description El techo que lo deshabilita, con su razón. Sólo cuatro de los 49 lo
             *     llevan.
             *
             *     **SE OMITE cuando no hay, NO viaja en `null`** · corregido el
             *     2026-10-02, y lo encontró el backend al implementar la ruta: acá
             *     decía `['object', 'null']` y «`null` cuando no tiene», y el archivo
             *     de datos que les entregamos omite la clave. Siguieron el archivo, que
             *     es el que vale — el Go lo declara `json:"cap,omitempty"`.
             *
             *     **La transcripción estaba mal desde que se escribió y nada la
             *     delató**, porque `adaptPlots` acepta las dos formas
             *     —`p.cap === undefined || p.cap === null`— y esa tolerancia tapaba la
             *     diferencia. Se deja igual: tolerar de más en el adaptador es barato,
             *     y que el cable mienta no.
             */
            cap?: {
                /** @example partes > 5 */
                when: string;
                /** @example más de cinco partes, ilegible en dona */
                reason: string;
            };
        };
        /** @description `dashboard.BlockRule`. Quince filas en la tabla `blocks`. */
        BlockRule: {
            /**
             * @example kpi
             * @example prose
             * @example series
             * @example bars
             * @example table
             * @example gauge
             * @example forecast
             * @example list
             * @example reco
             * @example composition
             * @example comparison
             * @example distribution
             * @example blocked
             * @example matrix
             * @example graph
             */
            type: string;
            /** @description Etiqueta para la UI de admin. El contrato no la tiene. */
            ui_name: string;
            /**
             * @description **`blocked` declara `["*"]`**, un comodín que el contrato no tiene.
             *     El adaptador lo expande o lo trata aparte.
             */
            accepted_shapes: string[];
            col_span_min: number;
            col_span_max: number;
            row_span_min: number;
            row_span_max: number;
            /**
             * @description Los nombres de param válidos, **en inglés**: `maximum`, `horizon`,
             *     `order`, `cap`, `normalization`, `pillars`, `columns`, `band`,
             *     `cut`, `window`. El front los espera en español · F1.41.
             */
            layout_params?: string[];
        };
        TabWithPanels: {
            tab: components["schemas"]["TabMeta"];
            panels: components["schemas"]["PanelDTO"][];
        };
        /**
         * @description `ports.DDPanelDTO`. En la base la columna es `block_type`; acá el campo
         *     es `type`. Mapea limpio al `PanelConfigurado` del contrato.
         *
         *     **`note` llegó el 2026-09-28** · B1.13 · medido: los nueve paneles que ve
         *     el planner la traen. Es lo único que quedaba de ese pedido — el grande,
         *     «`presentation` para las siete formas que no son escalares», lo habíamos
         *     retirado nosotros al descubrir que la lee un solo cuerpo.
         */
        PanelDTO: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            metric_id: string;
            type: string;
            col_start: number;
            col_span: number;
            /** @description En unidades de grilla: px = 96·N − 16. */
            row_span: number;
            /**
             * @description **Interruptores, no datos.** Para `kpi` llega
             *     `{ "comparative": true, "meter": true }`: los booleanos dicen si
             *     mostrar, y los VALORES viajan en `presentation` del payload. El front
             *     hoy los busca acá, que es el bug de F1.40.
             */
            options?: {
                [key: string]: unknown;
            };
            /**
             * @description **QUÉ VARIANTE dibuja este panel** · pedido el 2026-09-28 y llegó el
             *     mismo día, medido contra `f70cec2` en los doce paneles.
             *
             *     `type` elige el CUERPO y esto el dibujo de adentro. Hacían falta los
             *     dos porque **16 de los 49 gráficos sirven a más de una forma**.
             *
             *     **Cadena vacía = el gráfico por defecto del cuerpo**, que es lo que
             *     los doce publicados hacen hoy. Por eso el campo es aditivo y no
             *     migra ningún layout.
             *
             *     **Llega como `string` libre y lo cierra el adaptador**, igual que
             *     `shape`, `family` y `layer`: ellos lo guardan en minúsculas y
             *     recortado y **no lo validan contra el repertorio** —«eso es del
             *     front, que tiene los 49 y sus mínimos»—, así que un id desconocido
             *     puede llegar. El panel lo declara en vez de caer al de por defecto.
             * @example
             * @example waterfall
             * @example control
             */
            chart: string;
            /**
             * @description La nota de lectura del panel · **B1.13, llegó el 2026-09-28**.
             *
             *     La escribe el admin en el builder —`panels[].note` de
             *     `PUT /admin/layouts/{id}`— y vive en el layout, no en el dato: por
             *     eso viaja acá y no en el payload.
             *
             *     **Vacía cuando no hay**, no `null` · medido sobre los nueve paneles
             *     del planner. Un rol puede reemplazarla con
             *     `layout_overrides[tab_id][panel_id].note`.
             *
             *     **Y también aparece mezclada en `presentation.note`** del payload de
             *     `panels:batch`: se une en lectura sin pisar `label`, `meter` ni
             *     `comparative`, y no se guarda en `dd_panel_data`.
             */
            note: string;
        };
        BatchRequest: {
            panel_ids: string[];
            /**
             * @description `ParsePeriod` solo acepta `YYYY-MM` y rechaza cualquier otra cosa —
             *     ni días, ni semanas, ni rangos.
             * @example 2026-08
             */
            period: string;
        };
        /**
         * @description `ports.DDPayloadDTO`. **No es una unión discriminada**: es un struct con
         *     campos `omitempty`, así que el tipo no impide un `BLOCKED` con valor ni
         *     un `AVAILABLE` sin gobierno. El contrato sí lo impide, y el adaptador es
         *     donde eso se vuelve a cerrar.
         *
         *     `governance` va ANIDADO; el contrato lo intersecta en el payload.
         */
        Payload: {
            /**
             * @description Las cinco constantes de `domain/dd_panel_data.go`. **En inglés**, y
             *     la guía de Postman del backend dice `DEGRADADO` — el código manda.
             * @enum {string}
             */
            status: "AVAILABLE" | "DEGRADED" | "BLOCKED" | "FORBIDDEN" | "ERROR";
            governance?: components["schemas"]["Governance"];
            /** @description El JSON crudo de `dd_panel_data.value`. Discriminado por `shape`. */
            value?: {
                [key: string]: unknown;
            };
            /**
             * @description **Solo se emite para `scalar` y `scalar_with_interval`.**
             *     `PresentationFromRows` devuelve `nil` para **todas las demás**, así
             *     que un panel de barras o de tabla llega sin rótulo.
             *
             *     Decía «las otras siete» y eso se venció: el `switch` de
             *     `TransformValue` pasó de nueve formas a quince en `168a761`.
             *     Reverificado contra `1e080ee` el 2026-09-25 — el comportamiento de
             *     `PresentationFromRows` no cambió, el conteo sí. Se escribe sin número
             *     para que no vuelva a vencerse.
             */
            presentation?: {
                [key: string]: unknown;
            };
            /** @description Razón del estado. En `DEGRADED` la redacta el servidor. */
            reason?: string;
            /**
             * @description **Llega vacío en `BLOCKED`.** El servicio solo lo escribe al derivar
             *     `DEGRADED`. §8 pide estado, razón y qué lo desbloquea.
             */
            unlocks_with?: string;
            /** @description Solo en `ERROR`. Sale de `validatePanelOptions`. */
            message?: string;
            /**
             * @description Solo en `FORBIDDEN`, y es **la constante `"admin"`** escrita en el
             *     código, no el rol que decide sobre la métrica.
             *
             *     **Acá decía `"administrator"`, y no se había inventado: se
             *     VENCIÓ.** Ellos lo cambiaron y NOS LO AVISARON —
             *     `docs/RESPUESTA-2026-09-25-para-backend.md` §B1.6: «Hoy
             *     `request_from` en `FORBIDDEN` pasa de `"administrator"` a `"admin"`»,
             *     con su ejemplo de respuesta al lado. Se anotó en el documento y
             *     **nunca bajó al cable**, que es de donde sale el tipo.
             *
             *     **Es un modo de falla distinto al de escribir de memoria y conviene
             *     tenerlo aparte**: nadie adivinó nada, el aviso llegó, se guardó en
             *     prosa, y la prosa no la lee `openapi-typescript`. Un cambio anunciado
             *     no está transcripto hasta que está en el cable.
             *
             *     Medido el 2026-09-28 pidiéndole al token de `planner` los tres
             *     paneles que su rol oculta: los tres contestan
             *     `{"status":"FORBIDDEN","request_from":"admin"}` y nada más.
             *     `dd_config_service.go:726` lo declara —`const forbiddenRequestFrom =
             *     "admin"`—.
             *
             *     **Es un literal, no un rol resuelto.** Si el rol de administración de
             *     un tenant se llamara `owner` o `Administrador`, el servicio seguiría
             *     diciendo `admin`. El adaptador lo pasa tal cual igual: redactarlo
             *     sería el front inventando a quién pedirle.
             *
             *     **Y el payload de `FORBIDDEN` no trae nada más** — ni `reason` ni
             *     `unlocks_with`, que es la gramática de §8 que los otros estados sí
             *     traen. Pedido.
             * @example admin
             */
            request_from?: string;
        };
        /**
         * @description `ports.DDGovernanceDTO`. Los campos que el contrato pide, con otros
         *     nombres y un nivel más abajo.
         */
        Governance: {
            base: string;
            layer: string;
            source: string;
            /**
             * @description `materialized_at` en RFC 3339. **Cadena vacía** cuando el registro no
             *     tiene fecha de materialización, no `null`.
             */
            freshness: string;
            catalog_version: number;
            /**
             * @description Ventana de medición **ya redactada**, de la columna
             *     `MEASUREMENT_WINDOW` de la vista. No se deriva del período.
             * @example Mes calendario seleccionado
             * @example Cada día del mes calendario seleccionado
             */
            measurement_window: string;
        };
        /**
         * @description `ddChatRequest` de `dd_chat_handler.go`.
         *
         *     **`panel_context` dejó de ser obligatorio · reverificado contra
         *     `75b8ecc` el 2026-09-25.** Ahora el handler exige **exactamente uno** de
         *     `panel_context` o `tab_context` —`if (req.PanelContext == nil) ==
         *     (req.TabContext == nil)` devuelve 400— y su propio comentario cita la
         *     tarea: «exactamente uno de panel_context o tab_context (F3.15)».
         *
         *     **Es lo que pedimos el 2026-09-25 y lo hicieron el mismo día.** Y es lo
         *     que F3.15 esperaba: su candado dice «el cable exige un panel», y ya no.
         *     Queda anotado y **no se toma** — un candado vencido se dice y se
         *     pregunta.
         */
        ChatAskRequest: {
            question: string;
            /**
             * @description **La presencia del chat en la consola** · el `.pen` lo dibuja en las
             *     quince pantallas y colgaba de un panel. Con esto la pregunta puede
             *     ser de la pestaña entera.
             */
            tab_context?: {
                /** Format: uuid */
                tab_id: string;
                /** @example 2026-09 */
                period: string;
            };
            panel_context?: {
                /** Format: uuid */
                panel_id: string;
                /**
                 * @description `YYYY-MM`, validado con `^\d{4}-(0[1-9]|1[0-2])$` en
                 *     `dd_chat_service.go`. Otro formato devuelve 400 con
                 *     «período inválido, formato esperado YYYY-MM».
                 * @example 2026-09
                 */
                period: string;
            };
            /**
             * Format: uuid
             * @description **Sólo para `admin`** · leído en `7b717aa` el 2026-10-06
             *     (`dd_chat_handler.go:45`, `parseOptionalChatAgentID`) y medido en QA
             *     el mismo día: con él la pregunta contesta 200, sin él 409.
             *
             *     Omitido, el servicio busca el agente con `target_role` igual al rol
             *     del JWT **en el tenant del JWT**. Si el tenant no tiene agente para
             *     `admin` —el caso de UA en QA, cuyo único agente es `Planner`— eso es
             *     409 y el admin no puede preguntar nada sin elegir.
             *
             *     Otro rol que lo mande recibe 403 «solo administradores pueden
             *     seleccionar un agente». **Se ignora si va `thread_id`**: el agente
             *     queda fijado al crear el hilo, así que cambiar de agente es empezar
             *     un hilo nuevo.
             */
            agent_id?: string | null;
            /**
             * Format: int64
             * @description **Es un ENTERO, no un uuid.** Sale del frame `thread_info` y es lo
             *     que continúa la conversación. Ausente en la primera pregunta.
             */
            thread_id?: number | null;
        };
        /**
         * @description `event: thread_info`. **Siempre es la primera trama**, la emite `pump`
         *     antes de abrir el stream del agente.
         */
        ChatFrameThreadInfo: {
            /**
             * Format: int64
             * @description El que se manda de vuelta en `ChatAskRequest.thread_id`.
             */
            thread_id: number;
            /** Format: int64 */
            parent_message_id: number;
            /**
             * Format: uuid
             * @description El `:id` de `GET /config/chat/threads/{id}/messages`. **No sirve
             *     para continuar la conversación** — para eso va `thread_id`.
             */
            user_thread_id: string;
        };
        /**
         * @description `event: thinking`. **Tres formas distintas bajo un mismo nombre**, según
         *     de qué evento de Cortex salga: `{text}`, `{status, message}` o
         *     `{tool, status}`. Ninguna propiedad es obligatoria.
         */
        ChatFrameThinking: {
            text?: string;
            status?: string;
            message?: string;
            tool?: string;
        };
        /**
         * @description `event: delta`. Un fragmento de la respuesta. Se concatenan en orden.
         *     **La clave es `text`**, no `delta` como en el contrato.
         */
        ChatFrameDelta: {
            text: string;
        };
        /**
         * @description `event: sql`. El SQL que corrió el agente. **No trae fuentes
         *     consultadas ni límite declarado**: el agente los escribe dentro del
         *     markdown, como secciones `### Fuentes consultadas` y
         *     `### Límite declarado`.
         */
        ChatFrameSQL: {
            sql: string;
            tool?: string;
        };
        /**
         * @description `event: data`. Lo que `StructuredDataFromCortex` produjo.
         *
         *     **`shape` es la FORMA del valor, no el tipo de panel**, y `provenance`
         *     **no trae la BASE ni la capa Medallion** — los dos huecos por los que
         *     F3.6 sigue bloqueada. Se transcribe igual: describir el cable no es
         *     usarlo.
         */
        ChatFrameData: {
            /**
             * @description La forma de la métrica, o `tabular` si esa falló, o `raw` si no se
             *     pudo transformar nada.
             */
            shape: string;
            data: unknown;
            /**
             * @description **Creció el 2026-09-22 con `55e8419`**, que es lo que destrabó F3.6.
             *     Antes traía sólo las cinco primeras y no alcanzaba: `EventoDato`
             *     exige `familia` y los cinco campos de `Gobierno`.
             */
            provenance: {
                /** @example cortex_agent */
                source: string;
                tool?: string;
                metric_key: string;
                period: string;
                sql_available: boolean;
                /** @description El denominador y la ventana de la métrica. */
                base: string;
                /**
                 * @description `catalog` cuando la BASE salió del catálogo, vacío si no hay
                 *     base. **Es la declaración de que la BASE es la de la MÉTRICA**,
                 *     no una calculada para esta cifra en particular.
                 */
                base_source: string;
                /** @description Con qué familia se pinta. */
                family: string;
                /** @description La capa Medallion. */
                layer: string;
                source_system: string;
                catalog_version: number;
                /**
                 * @description RFC 3339 de la **última materialización de la métrica**. Cadena
                 *     vacía si nunca se materializó.
                 */
                freshness: string;
                /**
                 * @description RFC 3339 del momento en que **el agente produjo esta cifra**.
                 *     Lo pone el servicio al recibir el `tool_result`, así que sólo
                 *     viene cuando el agente consultó de verdad.
                 *
                 *     **No es lo mismo que `freshness` y confundirlos es el bug**: una
                 *     describe cuándo se materializó el panel y la otra cuándo se
                 *     calculó este número.
                 */
                queried_at: string;
            };
        };
        /**
         * @description `event: error`. Terminal: siempre lo sigue un `done`.
         *
         *     **No declara si lo ya recibido sigue valiendo**, que es el `parcial` del
         *     contrato. Lo que sí hace el servicio es persistir la respuesta
         *     acumulada —`defer s.persistAssistant(st)` en `pump`— antes de cerrar.
         */
        ChatFrameError: {
            /**
             * @description `upstream_error` cuando el agente falla sin código propio, y
             *     `empty_stream` cuando el stream cerró sin texto, sin dato y sin
             *     error.
             */
            code: string;
            message: string;
        };
        /**
         * @description `event: done`. **El objeto vacío `{}`**: no trae el id del hilo. El id
         *     llegó en `thread_info`, al principio.
         */
        ChatFrameDone: Record<string, never>;
        /**
         * @description `ports.DDChatThreadDTO`. Un hilo del chat contextual, ya cruzado con el
         *     tab y la métrica de donde salió.
         *
         *     **Los dos ids no son intercambiables, y confundirlos es el bug.**
         *     `id` es el uuid de `user_threads` y es el `:id` de
         *     `GET /config/chat/threads/{id}/messages`; `thread_id` es el entero que
         *     se manda de vuelta en `ChatAskRequest.thread_id` para continuar la
         *     conversación. Mandar el uuid donde va el entero da 400.
         *
         *     **Casi todo lo del panel es opcional**: los hilos abiertos antes de que
         *     existiera el contexto de panel no lo tienen.
         */
        ChatThread: {
            /** Format: uuid */
            id: string;
            /** Format: int64 */
            thread_id: number;
            thread_name: string;
            /** Format: uuid */
            agent_id: string;
            agent_name: string;
            role: string;
            /** @description La primera pregunta del hilo, tal como se escribió. */
            first_message_preview: string;
            /** Format: int64 */
            last_message_id?: number | null;
            /** Format: uuid */
            panel_id?: string | null;
            /**
             * @description `YYYY-MM`. **Cadena vacía cuando el hilo no tiene panel**, no
             *     `null`: el struct lo declara `string` con `omitempty`.
             */
            period?: string;
            /** Format: uuid */
            tab_id?: string | null;
            tab_name?: string;
            /** Format: uuid */
            metric_id?: string | null;
            metric_key?: string;
            metric_name?: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        /**
         * @description `ports.DDChatSuggestion`. Una pregunta que el servicio propone para este
         *     panel.
         * @example {
         *       "question": "¿Por qué Ventas está en USD 4.28M en septiembre?",
         *       "intent": "explain"
         *     }
         */
        ChatSuggestion: {
            /** @description La pregunta, ya redactada en español y lista para mandar. */
            question: string;
            /**
             * @description `explain`, `compare`, `drivers`, `breakdown`, `forecast` o `data`.
             *
             *     **El front no lo usa y por eso el adaptador lo descarta.** §PEN:C3
             *     dibuja las sugeridas como chips con su texto y nada más; conservar
             *     un campo que ninguna pantalla lee es cómo `BodyProps.presentation`
             *     estuvo meses declarada sin un solo consumidor.
             */
            intent: string;
        };
        /** @description `ports.DDDrillDownDimensions`. Qué se puede desagregar de este panel. */
        DrillDownDimensions: {
            /** Format: uuid */
            panel_id: string;
            /**
             * @description **La clave del catálogo**, no la canónica del registry · ver la
             *     descripción de la ruta.
             * @example sales
             * @example investment_by_platform
             */
            metric_key: string;
            /**
             * @description `true` cuando `DrillRegistry` tiene la métrica canónica. **Es lo que
             *     decide si el CTA de detalle se pinta.**
             */
            supported: boolean;
            /**
             * @description **Nunca `null`.** El servicio inicializa el DTO con `[]string{}` y
             *     sólo después mira el registry, así que una métrica sin drill-down
             *     llega con `[]` — medido en las ocho.
             *
             *     Los valores son los que el registry declara, y hoy son tres:
             *     `day`, `week` y `platform`. **No es un enum del cable**: agregar una
             *     dimensión es agregar una fila en `DrillRegistry`, y entonces este
             *     arreglo trae una cuarta sin que nada más cambie.
             * @example [
             *       "day",
             *       "week",
             *       "platform"
             *     ]
             * @example []
             */
            dimensions: string[];
        };
        /**
         * @description `ddDrillDownRequest` de `dd_drilldown_handler.go`. Los dos primeros son
         *     `binding:"required"`.
         */
        DrillDownRequest: {
            /**
             * @description Una de las que `GET …/drilldown/dimensions` devolvió para este panel.
             *     El servicio la compara en minúsculas y sin espacios
             *     —`strings.ToLower(strings.TrimSpace(...))`— contra la lista blanca.
             * @example platform
             * @example day
             * @example week
             */
            dimension: string;
            /**
             * @description `YYYY-MM`, el mismo `ParsePeriod` del resto del cable. Un día
             *     —`2026-09-01`— devuelve 400.
             * @example 2026-09
             */
            period: string;
            /**
             * @description **No estaba en el encargo y existe**: `drillDefaultLimit = 50`,
             *     `drillMaxLimit = 500`, y `<= 0` cae al default.
             *
             *     **El recorte ocurre en el SQL** —`LIMIT %d`—, así que `row_count`
             *     ya viene recortado y **nada en la respuesta dice que se recortó**:
             *     medido con `limit: 3` sobre `day`, contesta `row_count: 3` y tres
             *     ítems, idéntico a un mes de tres días. Si la hoja de C2 lo usa para
             *     paginar, el «hay más» lo tiene que saber por otro lado.
             * @default 50
             * @example 50
             */
            limit: number;
        };
        /**
         * @description `ports.DDDrillDownResponse`. **Nueve campos y ninguno es de
         *     procedencia** — ver la ruta.
         */
        DrillDownResponse: {
            /** Format: uuid */
            panel_id: string;
            /**
             * @description La del catálogo, igual que en `DrillDownDimensions`.
             * @example sales
             */
            metric_key: string;
            /**
             * @description El nombre de la métrica tal como lo trae el catálogo. **Hoy sale en
             *     inglés en los paneles del `overview`** —medido `"Sales"` y
             *     `"Investment and return by platform"`— porque esos paneles apuntan a
             *     las métricas de la semilla; las de Snowflake están en español. **No
             *     se traduce acá ni en el adaptador**: el dueño del copy que describe
             *     datos es el catálogo.
             * @example Sales
             * @example Investment and return by platform
             */
            metric_name: string;
            /**
             * @description La dimensión resuelta —`dim.Key` del registry—, no el texto que
             *     mandó el cliente.
             * @example platform
             */
            dimension: string;
            /** @example 2026-09 */
            period: string;
            /**
             * @description **Está CABLEADO en el servicio** —`Shape: "categorical"` en
             *     `dd_drilldown_service.go`—, no derivado de la métrica ni de la
             *     dimensión: las tres dimensiones de `sales` contestan lo mismo,
             *     medido. Un `day` con treinta ítems llega como categórico y no como
             *     serie de tiempo, así que **el cuerpo que lo dibuja lo elige la
             *     consola**, con `/config/plots` como repertorio: para `categorical`
             *     declara siete —`columns`, `bars`, `lollipop`, `donut`, `treemap`,
             *     `radial`, `pareto`—.
             * @enum {string}
             */
            shape: "categorical";
            /**
             * @description El payload **con la misma forma que un panel `categorical`**, que es
             *     lo que permite reusar el cuerpo: `{ shape: 'categorical', items:
             *     [{ label, v }] }`, y los ítems traen esas dos claves y nada más.
             *     Lo produce `materialize.Materialize("categorical", rows, …)`, que
             *     repite `shape` adentro.
             *
             *     **El orden lo fija el registry, no el cliente.** `platform` ordena
             *     por valor descendente —`byValue`, `2 DESC NULLS LAST`— y `day` y
             *     `week` por etiqueta: medido `'2026-09-01'…` en día y
             *     `'2026-08-31', '2026-09-07', '2026-09-14', '2026-09-21',
             *     '2026-09-28'` en semana. **La semana es el inicio del balde**
             *     —`DATE_TRUNC('week', DATE)`—, así que el primero puede empezar en el
             *     mes anterior y traer sólo los días que caen dentro del período.
             *
             *     **Y los ceros vienen.** Medido en `platform`: 29 de los 37 ítems en
             *     `0`. Una barra en cero no es un hueco de datos, es una plataforma sin
             *     gasto en el mes.
             */
            value: {
                /** @enum {string} */
                shape: "categorical";
                items: {
                    /** @example Google PMax */
                    label: string;
                    /** @example 537180.1 */
                    v: number;
                }[];
            };
            /**
             * @description `len(rows)` **de Snowflake**, y **NO es la cantidad de ítems** · es
             *     pérdida silenciosa y se midió: `platform` sobre `sales` contestó
             *     `row_count: 39` con **37** ítems.
             *
             *     Las dos filas se van en `transformCategorical`, que saltea toda fila
             *     sin `label` o sin `v` —`if !okLabel || !okV { continue }`— y también
             *     las comparativas —`isComparativeRow`—. **Nada avisa de la
             *     diferencia**: un «39 filas» en la hoja sobre una lista de 37 es una
             *     cifra que no cierra con lo que se ve.
             * @example 39
             */
            row_count: number;
            /**
             * Format: date-time
             * @description **Cuándo se corrió ESTA consulta** · `time.Now().UTC()`, RFC 3339.
             *
             *     **No es la frescura del panel y confundirlos es el bug**, igual que
             *     en `ChatFrameData.provenance`: `governance.freshness` dice cuándo se
             *     materializó la métrica y esto dice cuándo se leyó Snowflake. Medido
             *     el 2026-09-30 son siete horas de diferencia sobre el mes en curso, y
             *     con ellas el total del panel y la suma del detalle no coinciden.
             * @example 2026-10-01T00:07:50.780199Z
             */
            queried_at: string;
        };
    };
    responses: {
        /** @description Request mal formado */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Token ausente, inválido, o sin `role_id` en los claims */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description No existe, o no es de este tenant */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Falla interna */
        ServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Contexto */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["ContextResponse"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["ServerError"];
        };
    };
    getCatalog: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Catálogo */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["CatalogMetric"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getBlocks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Reglas de bloque */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["BlockRule"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getPlots: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description El repertorio entero, en el orden de §5 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["PlotRule"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getTab: {
        parameters: {
            query?: {
                /**
                 * @description Sin él, el layout publicado del tenant. Con él, valida que el layout
                 *     sea del tenant y que la tab sea de ese layout — permite borradores.
                 */
                layoutId?: string;
            };
            header?: never;
            path: {
                tabId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pestaña con paneles */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["TabWithPanels"];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    batchPanels: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchRequest"];
            };
        };
        responses: {
            /** @description Mapa panelId → payload */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: {
                            [key: string]: components["schemas"]["Payload"];
                        };
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    updatePreferences: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    theme: "dark" | "light";
                    /**
                     * Format: uuid
                     * @description `null` limpia la preferencia y vuelve a la resolución por
                     *     rol. Ausente la deja como está.
                     */
                    preferred_dashboard_id?: string | null;
                };
            };
        };
        responses: {
            /** @description El tema guardado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: {
                            /** @enum {string} */
                            theme: "dark" | "light";
                            /**
                             * Format: uuid
                             * @description **`null` cuando el pedido no lo mandó**, porque es
                             *     un puntero sin `omitempty`: el eco no distingue
                             *     «no lo pedí» de «lo limpié».
                             */
                            preferred_dashboard_id: string | null;
                        };
                    };
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    askChat: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatAskRequest"];
            };
        };
        responses: {
            /**
             * @description El stream. El esquema es `string` porque OpenAPI no describe tramas
             *     SSE; las formas de cada `data:` están en los `ChatFrame*` de
             *     `components/schemas`, que existen para que el traductor tipe contra
             *     algo y no contra structs de Go leídos a mano.
             */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /** @description El rol no ve el tab o la métrica del panel */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            404: components["responses"]["NotFound"];
            /** @description No hay agente activo para el tenant y el rol */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Rate limit por usuario, compartido con `/chat/*`. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listChatAgents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description La lista, sin paginar. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        data: components["schemas"]["ChatAgentOption"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description El rol no es admin · «acceso no autorizado» */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listChatThreads: {
        parameters: {
            query?: {
                /**
                 * @description Filtra a los hilos abiertos desde ese panel. Es lo que permite que
                 *     la hoja de un panel muestre sus propias conversaciones.
                 */
                panel_id?: string;
                /**
                 * @description **Nuevo · reverificado contra `75b8ecc` el 2026-09-25.** El par del
                 *     `tab_context` de `POST /config/chat`: con el chat presente en la
                 *     pestaña, el riel tiene que poder mostrar los hilos de esa pestaña y
                 *     no los de un panel · F3.15.
                 */
                tab_id?: string;
                /** @description `YYYY-MM`. Otro formato devuelve **400**, no una lista vacía. */
                period?: string;
                /**
                 * @description Sin valor, o `<= 0`, el servicio usa **50**; por encima de **200**
                 *     lo recorta. Lo hace `clampLimit`.
                 */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Los hilos, del más reciente al más viejo */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["ChatThread"][];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    panelChatSuggestions: {
        parameters: {
            query?: {
                /** @description `YYYY-MM`. Otro formato devuelve 400. */
                period?: string;
            };
            header?: never;
            path: {
                panelId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Entre una y cuatro preguntas */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["ChatSuggestion"][];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /** @description El rol no ve el tab o la métrica del panel */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    panelDrillDownDimensions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                panelId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Las dimensiones del panel, o la lista vacía */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["DrillDownDimensions"];
                    };
                };
            };
            /**
             * @description `panelId` que no parsea como uuid. Medido: `"panelId inválido"` con
             *     `VALIDATION_REQUEST`. **No es un 404**: el handler no llega a
             *     buscarlo.
             */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /**
             * @description El rol no ve la pestaña del panel, o la métrica está en sus
             *     `hidden_metric_ids`. Transcrito del handler —`ErrChatPanelForbidden`—,
             *     no medido.
             */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /**
             * @description Medido: `"panel o pestaña no encontrados"` con `NOT_FOUND_RESOURCE`.
             *     Un panel de otro tenant cae acá, no en 403.
             */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    panelDrillDown: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                panelId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DrillDownRequest"];
            };
        };
        responses: {
            /** @description La desagregación, con la misma forma que un panel `categorical` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["DrillDownResponse"];
                    };
                };
            };
            /**
             * @description Cuatro formas distintas, las cuatro medidas, y **las cuatro con
             *     `VALIDATION_REQUEST`** — el detalle del `code` no las distingue:
             *
             *     · `panelId` que no parsea · `"panelId inválido"`
             *     · falta `dimension` o `period` · `"solicitud inválida: Key:
             *       'ddDrillDownRequest.period' Error:Field validation for 'period'
             *       failed on the 'required' tag"` — **el nombre del struct de Go y el
             *       tag del validador llegan a la pantalla**, que es lo que
             *       `ErrorResponse.error` ya advierte
             *     · `period` que no es `YYYY-MM` · `"período inválido, formato esperado
             *       YYYY-MM"`
             *     · dimensión no declarada · `"dimensión inválida para esta métrica:
             *       soportadas [day week platform]"` · **trae la lista blanca**, así
             *       que el mensaje alcanza para corregir el pedido
             */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /**
             * @description El rol no ve la pestaña del panel o la métrica está oculta para él ·
             *     `ErrChatPanelForbidden`. Transcrito del handler, no medido.
             */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Medido: `"panel o pestaña no encontrados"` con `NOT_FOUND_RESOURCE`. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /**
             * @description El tenant no tiene agente activo para ese rol ·
             *     `ErrChatAgentUnavailable`. **El mismo candado que el chat**: sin
             *     agente cargado no hay credenciales de Snowflake con las que
             *     consultar. Transcrito del handler, no medido.
             */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /**
             * @description **Dos razones distintas bajo el mismo código**, y para la pantalla no
             *     son lo mismo:
             *
             *     · `"la métrica no soporta drill-down"` · `VALIDATION_RULE` · medido
             *       pidiéndole `day` a un panel de `goals_vs_actual`. Es el mismo
             *       estado que `supported: false` y **no debería pasar** si la consola
             *       preguntó primero por las dimensiones.
             *     · `"Snowflake no devolvió filas para ese período y dimensión"` ·
             *       `ErrDrillNoData`, transcrito del servicio y no medido. Acá sí hay
             *       que pintar un vacío declarado: la dimensión existe y el período no
             *       tiene filas.
             */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /**
             * @description Rate limit por usuario, **compartido con `/config/chat`**. Viene con
             *     cabecera `Retry-After` —segundos— y el mensaje
             *     `"límite de peticiones por usuario excedido; reintenta más tarde"`,
             *     que es uno de los pocos ya redactados en español. Transcrito de
             *     `handler/ratelimit.go`, no medido: habría que gastar la cuota.
             */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /**
             * @description La rama `default` del handler, y **no es sólo «algo falló»**: caen acá
             *     el tenant que no se encuentra, el JWT que no se puede firmar y
             *     —esto importa— **que ninguna fila sobreviva a la transformación**.
             *     `transformCategorical` devuelve `ErrInvalidRow` cuando ninguna trae
             *     `label` y `v`, y el servicio lo envuelve como «drilldown: transformar
             *     filas». Transcrito del código, no medido.
             */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /**
             * @description La consulta a Snowflake falló o se pasó del timeout ·
             *     `ErrChatUpstream`. Transcrito del handler, no medido.
             */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
