/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/config/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Quién sos, qué tenant, qué rol y qué pestañas te tocan
         * @description Una vez al montar la aplicación. Devuelve la composición ya resuelta
         *     para el rol del token: las pestañas que le tocan, en su orden.
         *
         *     **El filtrado por rol se aplica acá** (invariante 2.3). El front no
         *     recibe pestañas que no le corresponden y no las filtra.
         */
        get: operations["obtenerContexto"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Las métricas del tenant, filtradas por rol
         * @description El catálogo gobierna: un panel se ancla a un `metricId` y nunca a un SQL
         *     ni a un nombre de tabla. Devuelve **solo** las métricas del tenant y del
         *     rol del token.
         */
        get: operations["obtenerCatalogo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/blocks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * La tabla forma ↔ tipo de panel
         * @description Declarada en §4.4 de backend-handoff.md. **Vive en el backend** y es la
         *     misma tabla que usa `layout:validate`, para que el builder y el front no
         *     la dupliquen.
         */
        get: operations["obtenerBloques"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/tabs/{tabId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * La composición de una pestaña
         * @description **Verificación de pertenencia obligatoria:** el `tabId` debe pertenecer
         *     al tenant y rol del usuario del token. Si no, `404` y no `403` — no se
         *     revela la existencia.
         */
        get: operations["obtenerPestana"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Preguntar al agente · responde por SSE
         * @description **Decisión del 2026-08-19 (humano): la respuesta llega por SSE**, no de
         *     una vez. El agente consulta Gold y razona; esperar en silencio a que
         *     termine se siente como que la pantalla se colgó, y C3 muestra una
         *     conversación, así que la respuesta progresiva es coherente con lo que la
         *     pantalla promete.
         *
         *     **El agente es por cliente y su nombre no viaja.** `SYNAPSE_UA` es el de
         *     Under Armour y cada cliente tiene el suyo; la resolución vive en
         *     `agents.tenant_id`. Exponerlo sería hacer circular un identificador de
         *     cliente por el navegador, además de violar §7.3.
         *
         *     **REGLA DURA SOBRE EL ORDEN DE LOS EVENTOS.** §1.3 exige que toda cifra
         *     declare su BASE y su procedencia. Si la cifra llegara en un evento y la
         *     procedencia en otro, habría un instante —medio segundo— con un número en
         *     pantalla sin su badge. Por eso el evento `dato` lleva las dos cosas y el
         *     esquema las hace obligatorias: es estructuralmente imposible mandar una
         *     cifra sin su procedencia, igual que en el payload de un panel.
         */
        post: operations["preguntarASynapse"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/chat/hilos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * El historial del riel de C3
         * @description **Solo los hilos del usuario del token** (decisión del 2026-08-19). El
         *     rol define qué pudo preguntar, no qué puede leer: dos personas con el
         *     mismo rol no ven las consultas de la otra.
         *
         *     Esto precisa lo que el `.pen` dice —«las consultas quedan en el tenant,
         *     visibles solo para tu rol»—, que admitía las dos lecturas. Se resolvió
         *     por la estricta, que además es la que sugiere el nombre `user_threads`.
         *
         *     **Retención: 12 meses.** Cubre el ciclo anual del negocio y permite
         *     reabrir la consulta del mismo mes del año previo, que es una comparación
         *     que el producto ya hace en sus paneles.
         *
         *     Devuelve los hilos ordenados por actividad, del más reciente al más
         *     viejo. **El agrupado por tiempo —HOY, ESTA SEMANA, JULIO— lo hace el
         *     front**: es presentación y depende del huso del usuario.
         */
        get: operations["listarHilos"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/chat/hilos/{hiloId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Una conversación completa, con sus cifras como llegaron
         * @description **Las cifras vienen congeladas** (decisión del 2026-08-19): se guarda el
         *     payload tal como llegó, no se recalcula al abrir.
         *
         *     La razón es que el texto y las cifras tienen que seguir diciendo lo
         *     mismo. Un hilo de julio que dice «el ROAS subió a 4.1x» recalculado hoy
         *     mostraría 3.8x al lado de esa frase, y §1.3 existe para que eso no pase.
         *
         *     **Y no hace falta ningún aviso nuevo:** la procedencia que ya viaja con
         *     cada cifra declara su frescura, así que el panel muestra «HACE 45 D» y el
         *     usuario ve solo que está mirando julio. El badge que ya existe resuelve
         *     el problema.
         */
        get: operations["obtenerHilo"];
        put?: never;
        post?: never;
        /**
         * Borrar un hilo propio
         * @description **Salvo los marcados como decisión** (decisión del 2026-08-19). Un hilo
         *     asociado a una decisión de C4 es la traza de por qué se decidió algo, y
         *     esa traza no se borra: C4 declara la hipótesis, quién aprobó y contra qué
         *     se midió, y el hilo es de dónde salió.
         *
         *     Cuando el hilo es decisión responde **409** con la razón, no 403: no es
         *     un problema de permiso sino de regla, y la gramática de §8 pide decir
         *     qué lo bloquea.
         */
        delete: operations["borrarHilo"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/decisiones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Las decisiones del período · alimenta C4 */
        get: operations["listarDecisiones"];
        put?: never;
        /**
         * Aprobar o rechazar una recomendación
         * @description **Solo si el rol del token tiene `puedeAprobar`.** Si no, `403` — pero el
         *     front no debería llegar acá: `/config/me` ya le dijo que no pinte el CTA.
         *
         *     Una decisión declara su **ventana de medición** al crearse, y no es
         *     opcional: sin ventana no hay contra qué medirla después, y C4 existe
         *     justamente para mostrar el observado contra el estimado.
         */
        post: operations["decidirRecomendacion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/decisiones/{decisionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** El detalle de C4 */
        get: operations["obtenerDecision"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/accionables": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Promover un hallazgo a accionable · desde el chat de C3
         * @description **Es interno.** Requiere la capacidad `registrar_accionable`, que el
         *     super-admin asigna **por usuario** y no por rol (`PS-16`, humano
         *     2026-08-21). §1.4.20 ya separa permiso de composición, así que esto vive
         *     en el eje del permiso y no toca §3.3.
         *
         *     **Ocurre en el hallazgo, no en una pantalla aparte.** La regla de
         *     cobertura del framework dice que toda observación se resuelve y ninguna
         *     queda en el limbo; si para registrar hay que ir a otro lado, las
         *     observaciones se pierden. `A6` administra la cola; no es donde se la
         *     llena.
         *
         *     **El snapshot es obligatorio y ya existe.** El evento `auditoria` del
         *     chat emite `sql` y `fuentesConsultadas` porque §1.3 obliga a que toda
         *     cifra declare de dónde salió — y eso es exactamente el `sql_congelado`
         *     que pide `SNAPSHOT_CONSULTA`. Medir después es re-correr esa misma
         *     consulta sobre Gold. Sin ella, el «observado contra estimado» compara dos
         *     cosas distintas.
         *
         *     # DECIDIDO 2026-09-03 (humano): **lo emite Snowflake.** La versión del
         *     # modelo semántico no la inventa el backend ni la reconstruye el
         *     # `DECISION_LOG`: sale de Snowflake, que es donde la consulta se
         *     # resuelve.
         *     #
         *     # Consecuencia: **el evento la estampa al responder**, junto al `sql`
         *     # congelado. Resolverla recién al re-medir no sirve, porque `inconcluso`
         *     # compara DOS momentos —la versión con la que se respondió contra la de
         *     # cuando se mide— y la primera no se puede reconstruir después: si la
         *     # definición cambió, Snowflake ya devuelve la nueva.
         *     #
         *     # El campo ya existe en `snapshot` más abajo. Lo que queda abierto es su
         *     # `nullable: true`: si Snowflake la emite siempre, pasa a requerido
         *     # dentro de `snapshot` y `inconcluso` deja de tener un tercer caso
         *     # —«no sé con qué versión se respondió»— que hoy el tipo permite.
         */
        post: operations["promoverAccionable"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/accionables/{id}/respuesta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * El cliente acepta o rechaza una recomendación · ruta B del framework
         * @description Cierra el **hueco 3** de `handoff/propuesta-escritura.md`: hasta el
         *     2026-08-21 `APROBAR` y `RECHAZAR` no escribían en ningún lado.
         *
         *     Lo destrabó `PS-15`. §7.1 declara ahora **dos ejes** de interacción del
         *     usuario de cliente, y el segundo es **registrar una decisión** sobre lo
         *     que la consola le propone. Decisión del humano: «que el cliente acepte
         *     es parte de la aprobación que se debe hacer para ejecutar».
         *
         *     Escribe en `DB_BT_UA.BT_UA_DECISION_LOG` — `accionable.respuesta_cliente`
         *     más una fila en `historial_estado`. Ver `handoff/accionables.md`.
         *
         *     **Quién puede.** El rol del cliente y el super-admin (humano,
         *     2026-08-21), **con dos límites que no son negociables**:
         *
         *     - **Un rol solo puede responder lo que ve.** Es §1.4.20 aplicada: si el
         *       backend no le envía el payload de la métrica objetivo, tampoco le
         *       acepta la respuesta. En `ua_mx` eso deja al `planner` fuera de todo
         *       accionable que dependa de inversión de medios.
         *     - **Una respuesta de super-admin no es una respuesta del cliente.**
         *       `actor` las distingue y `respuesta_cliente` sigue en `sin_respuesta`.
         *       Si no, se rompe el «seguro de atribución»: una fila aprobada dejaría de
         *       probar que el cliente decidió.
         *
         *     # DECIDIDO 2026-09-03 (humano): **lo deriva del token.** El front no
         *     # manda `actor`, y el request no lo declara.
         *     #
         *     # Es lo que sostiene el «seguro de atribución» que este mismo bloque
         *     # describe: `actor` es lo que distingue una respuesta del cliente de una
         *     # de super-admin. Si el cliente pudiera escribir ese campo, una fila
         *     # aprobada dejaría de PROBAR que el cliente decidió — probaría que
         *     # alguien dijo que el cliente decidió, que no es lo mismo y es
         *     # exactamente lo que el framework necesita que no pase.
         */
        post: operations["responderAccionable"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/solicitudes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Mis solicitudes de acceso · alimenta C5
         * @description Las del usuario del token. **C5 las consulta para no dejar pedir dos
         *     veces**: si ya hay una pendiente para esa métrica, el CTA se reemplaza
         *     por su estado.
         */
        get: operations["listarSolicitudes"];
        put?: never;
        /**
         * Pedir acceso a una métrica que el rol no ve
         * @description Decisión del 2026-08-19 (humano): **si ya hay una pendiente para esa
         *     métrica, no se crea otra**. Responde `409` con el estado de la que
         *     existe.
         *
         *     Pedir dos veces sin saberlo es el fallo obvio de esta pantalla: llena la
         *     bandeja de quien resuelve y deja al que pide sin señal de que su primer
         *     pedido llegó.
         */
        post: operations["solicitarAcceso"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/me/preferencias": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * El tema del usuario
         * @description §2.4 de design.md: **el tema es preferencia de usuario, no de tenant, y
         *     se persiste por usuario**. Por eso va contra el perfil y no en el
         *     navegador: la misma cuenta se vería distinta en dos máquinas.
         */
        put: operations["guardarPreferencias"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/panels:batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Los payloads de una pestaña, en una sola llamada
         * @description **Un request por pestaña, no uno por panel.** Ocho paneles en una
         *     llamada.
         *
         *     **Fallo parcial:** si un panel no resuelve, su entrada lleva
         *     `estado: ERROR` y el resto vuelve normal. No se falla el batch completo.
         *
         *     Es `POST` por el cuerpo, no porque modifique: el front lo cachea,
         *     invalida y reintenta como una lectura.
         */
        post: operations["obtenerPayloads"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Envelope: {
            /** @enum {boolean} */
            success: true;
        };
        RespuestaError: {
            /** @enum {boolean} */
            success: false;
            error: {
                /**
                 * @description Código estable, para decidir en código.
                 * @example REGLA_VIOLADA
                 */
                codigo: string;
                /**
                 * @description Escrito desde el lado del usuario. §8: los errores no se
                 *     disculpan y nunca son vagos — «El feed de inventario tiene 31
                 *     horas» y no «Error al obtener snapshot».
                 */
                mensaje: string;
                /** @description Qué input señalar, cuando el error es de un campo. */
                campo?: string | null;
                /**
                 * @description Mismo vocabulario que los estados degradados de §8, así que el
                 *     front ya sabe renderizarlo.
                 */
                desbloqueaCon?: string | null;
            };
        };
        /**
         * @description La forma del dato. Decide qué tipos de panel puede usar.
         * @enum {string}
         */
        Forma: "escalar" | "escalarConIntervalo" | "serieTemporal" | "serieConBanda" | "seriesMultiples" | "categorica" | "categoricaComparada" | "perfilMultiatributo" | "composicion" | "distribucion" | "matriz" | "flujo" | "grafo" | "ranking" | "tabular" | "prosa";
        /** @enum {string} */
        TipoPanel: "kpi" | "prose" | "series" | "bars" | "table" | "gauge" | "forecast" | "list" | "reco" | "composition" | "comparison" | "distribution" | "blocked" | "matrix" | "graph";
        /**
         * @description Capa Medallion. Una métrica compuesta hereda la peor.
         * @enum {string}
         */
        Capa: "BRONZE" | "SILVER" | "GOLD";
        /**
         * @description De acá sale el color de la serie. El componente no lo elige: la
         *     asignación vive en el catálogo, que es lo que sostiene la persistencia
         *     cromática de §2.2.
         * @enum {string}
         */
        Familia: "demanda" | "medios" | "inventario" | "cliente" | "externo";
        /**
         * @description Cómo se lee la métrica. **Texto que se pinta tal cual**, no un código.
         * @example MÁS ALTO = MEJOR
         * @example MÁS BAJO = MEJOR
         * @example CERCA DEL 100% = MEJOR
         * @example MENOS DÍAS = MÁS URGENTE
         * @example MENOS SKU AFECTADOS = MEJOR
         */
        DireccionSemantica: string;
        /**
         * @description Gobierno de la métrica. No confundir con el estado del panel.
         * @enum {string}
         */
        EstadoMetrica: "DISPONIBLE" | "DEGRADADO" | "BLOQUEADO";
        /**
         * @description Clave absoluta, nunca relativa: `2026-07` y no `actual`. Con clave
         *     relativa el selector de período obliga a reconstruir el índice.
         * @example 2026-07
         * @example 2026-W32
         */
        PeriodoId: string;
        Contexto: {
            /**
             * @description Con qué clase de token se está mirando esta consola.
             *
             *     `usuario` · pertenece al tenant. El navbar muestra su nombre.
             *     `plataforma` · equipo interno mirando la consola de un cliente. El
             *     navbar muestra el selector y el acceso queda auditado.
             *
             *     **El alcance se declara en el chrome** (§8 de parametros-front.md),
             *     así que el front necesita saberlo para decidir qué pinta.
             * @enum {string}
             */
            alcance: "usuario" | "plataforma";
            /**
             * @description Solo con `alcance: plataforma`. Los tenants que este operador puede
             *     abrir. Con `alcance: usuario` viene vacío o ausente: un usuario de
             *     cliente pertenece a uno y no elige.
             */
            tenantsDisponibles?: {
                /** Format: uuid */
                id: string;
                etiqueta: string;
            }[];
            user: {
                /** Format: uuid */
                id: string;
                nombre: string;
                /** Format: email */
                email: string;
                /**
                 * @description Qué puede hacer **este usuario**, no su rol · `PS-16`, 2026-08-21.
                 *
                 *     §1.4.20 ya separa los dos ejes: «el permiso se aplica en el
                 *     backend; la composición solo decide qué se muestra de lo que ya
                 *     está permitido». La composición es por rol (§3.3); una capacidad
                 *     es por usuario y vive en el otro eje, así que no lo contradice.
                 *
                 *     Hoy hay una: **`registrar_accionable`**, que el super-admin
                 *     asigna en A3. Habilita promover un hallazgo desde el chat y
                 *     registrar un reparto desde el controlador del MMM.
                 *
                 *     **Sin ella el front no monta el CTA, y el servidor la verifica
                 *     igual**: ocultar no es permitir.
                 */
                capacidades?: string[];
                /**
                 * @description §3.5 de design.md las declara en el usuario: `Usuario { …,
                 *     preferencias: { tema } }`. Van acá y no en un endpoint aparte
                 *     porque el front las necesita **antes del primer pixel**: leerlas
                 *     en una segunda llamada haría que la consola pinte oscura y
                 *     cambie a clara a la vista del usuario.
                 *
                 *     Se escriben con `PUT /config/me/preferencias`.
                 */
                preferencias?: {
                    /**
                     * @description §2.4: el tema es preferencia de USUARIO, no de tenant. Por eso
                     *     va contra el perfil y no en el navegador — un `localStorage`
                     *     haría que la misma cuenta se viera distinta en dos máquinas.
                     *
                     *     Ausente significa que el usuario nunca eligió. El front aplica
                     *     `dark`, que es el defecto que emite `tokens.css`.
                     * @enum {string}
                     */
                    tema?: "dark" | "light";
                };
            };
            tenant: {
                /** Format: uuid */
                id: string;
                /** @example Under Armour México */
                nombre: string;
                /**
                 * @description La forma corta, para el navbar.
                 * @example UA MX
                 */
                etiqueta: string;
                /** @example retail_apparel */
                vertical: string;
            };
            role: {
                id: string;
                /** @example Planner */
                nombre: string;
                descripcion?: string;
                /**
                 * @description Si este rol puede aprobar o rechazar una recomendación.
                 *
                 *     Decisión del 2026-08-19 (humano): **es configurable por rol**, no
                 *     fijo al CEO. Cada tenant declara qué roles deciden.
                 *
                 *     **El front necesita saberlo para no pintar un CTA que va a
                 *     fallar.** Un botón que se aprieta y devuelve 403 es peor que un
                 *     botón ausente: promete una acción que no existe para vos. Con
                 *     esto, el panel de recomendaciones muestra APROBAR y RECHAZAR
                 *     solo a quien puede, y a los demás la recomendación se lee sin
                 *     acción — que es la misma gramática con la que A1 marca la fila
                 *     propia como «sin acción sobre tu cuenta».
                 */
                puedeAprobar: boolean;
            };
            /** @description Las pestañas del rol, en su orden. Ya filtradas. */
            tabs: components["schemas"]["Pestana"][];
            periodos: components["schemas"]["Periodo"][];
            /** @description Con qué versión del catálogo se resolvió esta respuesta. */
            catalogVersion: number;
        };
        Periodo: {
            id: components["schemas"]["PeriodoId"];
            /** @example JUL 2026 */
            etiqueta: string;
            /** @example 1 – 31 JUL 2026 */
            rango?: string;
            /**
             * @example MTD CERRADO
             * @example CERRADO
             */
            estado?: string;
            /**
             * @description Qué tan fino es este período. Es la otra mitad de `granoMinimo`: sin
             *     él, el front sabe que una métrica de marca es mensual pero no sabe si
             *     `2026-W32` es una semana, así que no puede decidir nada.
             *
             *     El front lo deduce de la forma del id cuando no llega —`2026-07` mes,
             *     `2026-W32` semana, `2026-07-15` día—, pero deducir del id es frágil
             *     en cuanto aparezca un período con nombre propio (un trimestre, una
             *     temporada). Mejor que lo declare quien lo construye.
             * @default mes
             * @enum {string}
             */
            grano: "dia" | "semana" | "mes";
        };
        Pestana: {
            /** Format: uuid */
            id: string;
            /** @example inventory */
            key: string;
            /** @example Inventory & Shopping */
            nombre: string;
            /** @example box */
            icono?: string;
            /**
             * @description La pregunta operativa de la pestaña. Es el título de la pantalla:
             *     una pestaña que no contesta una pregunta no se compone.
             * @example ¿Tenemos stock y lo estamos mostrando?
             */
            pregunta: string;
            orden: number;
            chatSugerencias?: string[];
        };
        PestanaConPaneles: {
            tab: components["schemas"]["Pestana"];
            panels: components["schemas"]["PanelConfigurado"][];
        };
        /**
         * @description La colocación del panel en la grilla. **No lleva datos**: los datos
         *     vienen de `panels:batch`, y por eso cambiar de período no obliga a pedir
         *     el layout de nuevo.
         */
        PanelConfigurado: {
            /** Format: uuid */
            id: string;
            tipo: components["schemas"]["TipoPanel"];
            /** Format: uuid */
            metricId: string;
            colStart: number;
            colSpan: number;
            /** @description En unidades de grilla, nunca en píxeles: `px = 96·N − 16`. */
            rowSpan: number;
            /**
             * @description Interruptores de composición, no datos: «mostrar medidor», «ordenar
             *     por». Lo que el medidor MARCA viaja en el payload, porque depende
             *     del período.
             */
            opciones?: {
                [key: string]: unknown;
            };
        };
        /** @description Una fila de la tabla de §4.4. */
        Bloque: {
            tipo: components["schemas"]["TipoPanel"];
            formasAceptadas: components["schemas"]["Forma"][];
            colSpanMin: number;
            colSpanMax: number;
            rowSpanMin: number;
            rowSpanMax: number;
            paramsDisponibles?: string[];
        };
        Metrica: {
            /** Format: uuid */
            id: string;
            /** @example inv_riesgo */
            key: string;
            /** @example Venta diaria en riesgo */
            nombre: string;
            forma: components["schemas"]["Forma"];
            familia: components["schemas"]["Familia"];
            capa: components["schemas"]["Capa"];
            /** @example ERP + Analítica de sitio */
            fuente: string;
            /**
             * @description La mitad de la BASE — el período que mide.
             * @example Venta media de los últimos treinta días
             */
            ventana: string;
            /**
             * @description El denominador. **Obligatorio en el catálogo y no solo en el
             *     payload**: §4.1 exige que la BASE siga visible mientras el panel
             *     carga, falla o está bloqueado, y un payload bloqueado no lleva
             *     gobierno. Sin este campo, un panel bloqueado no puede declarar su
             *     BASE aunque la anatomía lo exija.
             * @example 312 SKU críticos sobre 18.240 activos
             */
            base: string;
            /**
             * @description `USD` (moneda, va delante), `%` o `x` (símbolo, va pegado), o un
             *     NOMBRE como «órdenes» (no se pega: pertenece al label).
             */
            unidad?: string | null;
            /** @description Por dónde se puede desagregar en el drill-down. */
            dimensiones?: string[];
            /** @description Null cuando la métrica no es compuesta. */
            direccionSemantica?: components["schemas"]["DireccionSemantica"] | null;
            /** @description Lo que hay que saber para no malinterpretarla. */
            notaLectura?: string | null;
            /**
             * @description El período más fino que esta métrica puede responder.
             *
             *     No es un detalle: verificado contra Snowflake, las métricas de marca
             *     son **mensuales** —`BR_MONTH_TD`, `REPORT_MONTH`— y las de ecommerce
             *     diarias. Con el selector en una semana, una pestaña de marca no
             *     tiene nada que devolver.
             *
             *     Decisión del 2026-08-19 (humano): la métrica lo declara y **el
             *     selector de período deshabilita lo que no aplica, con la razón
             *     visible**. Ofrecer un período que la métrica no puede contestar es
             *     el mismo problema que un panel sin BASE: promete algo que no puede
             *     sostener.
             * @default dia
             * @enum {string}
             */
            granoMinimo: "dia" | "semana" | "mes";
            estado: components["schemas"]["EstadoMetrica"];
            estadoRazon?: string | null;
            catalogVersion: number;
        };
        Payload: components["schemas"]["PayloadDisponible"] | components["schemas"]["PayloadDegradado"] | components["schemas"]["PayloadBloqueado"] | components["schemas"]["PayloadSinPermiso"] | components["schemas"]["PayloadError"];
        /**
         * @description **Qué se puede hacer con cada ítem del panel** · `PS-17`, 2026-08-24.
         *
         *     Va acá y no dentro de `valor` porque la responsabilidad ya estaba
         *     partida así: `Gobierno` dice de dónde salió el dato, `Presentacion` cómo
         *     se muestra, `Valor` qué es. **Qué se puede hacer con él es una cuarta
         *     cosa**, y hasta que un panel escribió algo no había tenido lugar.
         *
         *     La consecuencia buena es que **§5 no cambia**: `valor` sigue siendo
         *     geometría pura, y cualquier cuerpo puede volverse respondible sin
         *     cambiar de forma. El controlador del MMM va a usar esto mismo.
         *
         *     **Está keyeado por `ref` y no por índice.** `ParamsReco.tope` recorta los
         *     pilares antes de pintarlos, así que el ítem 2 del cuerpo no es el ítem 2
         *     del payload en cuanto alguien configure un tope. Un `acciones[i]`
         *     posicional pondría el botón de aprobar sobre la recomendación
         *     equivocada, en silencio y solo con cierta configuración.
         */
        Acciones: {
            /** @description Llave = el `ref` opaco del ítem en `valor`. */
            porRef: {
                [key: string]: {
                    accionableId: string;
                    estado: components["schemas"]["EstadoDeAccionable"];
                    /**
                     * @description **Lo decide el backend, no la UI.** §1.4.20 —ocultar no es
                     *     permitir— más las dos reglas del 2026-08-21: un rol solo
                     *     responde lo que ve, y una decisión registrada no se renegocia.
                     *     El front lo obedece; el servidor lo vuelve a verificar.
                     */
                    puedeResponder: boolean;
                    /**
                     * @description Por qué no se puede responder. **Un CTA deshabilitado que no
                     *     dice por qué es una pared**, y §8 pide estado, razón y qué lo
                     *     desbloquea. Nulo cuando `puedeResponder` es verdadero.
                     */
                    razonSiNo?: string | null;
                };
            };
        };
        /**
         * @description Lo que §1.3 hace obligatorio en toda cifra. Va intersectado en los dos
         *     estados que muestran número, así que **un valor sin procedencia es
         *     imposible de construir**.
         */
        Gobierno: {
            base: string;
            capa: components["schemas"]["Capa"];
            fuente: string;
            /** Format: date-time */
            frescura: string;
            catalogVersion: number;
        };
        PayloadDisponible: components["schemas"]["Gobierno"] & {
            /** @enum {string} */
            estado: "DISPONIBLE";
            valor: components["schemas"]["Valor"];
            presentacion?: components["schemas"]["Presentacion"];
            /**
             * @description Cuando el valor no tiene filas, qué falta y qué hacer. §8 pide
             *     que el estado vacío sea invitación a actuar y no un error, y un
             *     array vacío no alcanza para escribir «el período cierra el 1 de
             *     septiembre».
             */
            vacioRazon?: string | null;
            vacioDesbloqueaCon?: string | null;
            acciones?: components["schemas"]["Acciones"];
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            estado: "DISPONIBLE";
        };
        PayloadDegradado: components["schemas"]["Gobierno"] & {
            /** @enum {string} */
            estado: "DEGRADADO";
            valor: components["schemas"]["Valor"];
            presentacion?: components["schemas"]["Presentacion"];
            /** @description Qué limitación tiene el dato y cuál es su alcance. */
            razon: string;
            desbloqueaCon: string;
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            estado: "DEGRADADO";
        };
        /**
         * @description **Sin valor, y sin posibilidad de tenerlo.** No lleva `Gobierno` porque
         *     sin cifra no hay procedencia de cifra: la BASE y la capa las declara el
         *     catálogo.
         */
        PayloadBloqueado: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            estado: "BLOQUEADO";
            /** @example Falta identificador de persona en la orden */
            razon: string;
            /** @example Feed transaccional con identidad estable */
            desbloqueaCon: string;
        };
        PayloadSinPermiso: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            estado: "SIN_PERMISO";
            /**
             * @description Qué rol decide sobre esta métrica.
             * @example CMO
             */
            solicitarA: string;
        };
        PayloadError: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            estado: "ERROR";
            mensaje: string;
        };
        EventoDeChat: components["schemas"]["EventoTexto"] | components["schemas"]["EventoDato"] | components["schemas"]["EventoAuditoria"] | components["schemas"]["EventoSugerencias"] | components["schemas"]["EventoFin"] | components["schemas"]["EventoErrorChat"];
        /** @description Un fragmento de la respuesta en prosa. Se concatenan en orden. */
        EventoTexto: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            tipo: "texto";
            delta: string;
        };
        DatoDeRespuesta: components["schemas"]["Gobierno"] & {
            valor: components["schemas"]["Valor"];
            /**
             * @description Con qué familia se pinta. **Obligatoria, y entró al contrato el
             *     2026-08-19 por un defecto real**: el front la tenía cableada a
             *     `demanda` porque el evento no la traía, o sea que el color de
             *     una cifra del chat era inventado. §2.2 hace del color una
             *     propiedad de la métrica, no una decisión del componente — y eso
             *     vale igual cuando la cifra la compuso el agente para responder.
             */
            familia: components["schemas"]["Familia"];
            presentacion?: components["schemas"]["Presentacion"];
            /**
             * @description Cuando la respuesta se apoya en una métrica del catálogo. Null
             *     si el agente la compuso para responder — y en ese caso el front
             *     la muestra sin CTA de drill-down, porque no hay a dónde ir.
             */
            metricId?: string | null;
            titulo?: string | null;
        };
        EventoDato: components["schemas"]["DatoDeRespuesta"] & {
            /** @enum {string} */
            tipo: "dato";
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            tipo: "dato";
        };
        /**
         * @description **El SQL que el agente generó para responder.** §7.1 lo hace obligatorio:
         *     «toda respuesta muestra el SQL generado en un desplegable — es la
         *     auditabilidad que sostiene el producto».
         *
         *     Entró al contrato el 2026-08-19 al construir C3: la pantalla lo exige y
         *     no había campo donde viajara.
         *
         *     **No contradice la regla de que el front no lleva SQL.** La regla
         *     prohíbe escribirlo en el código —un panel se ancla a un `metricId`,
         *     jamás a una consulta—; esto es SQL que el backend devuelve como dato
         *     para que el usuario pueda auditar de dónde salió la cifra. Es lo
         *     contrario de improvisar una consulta: es mostrar la que se corrió.
         */
        EventoAuditoria: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            tipo: "auditoria";
            sql: string;
            fuentesConsultadas?: string[];
            /**
             * @description Qué NO puede afirmar esta respuesta. §7.1 lo pide junto al SQL: una
             *     respuesta sin límite declarado se lee como si abarcara todo.
             */
            limiteDeclarado?: string | null;
        };
        /** @description Qué más se puede preguntar desde acá. */
        EventoSugerencias: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            tipo: "sugerencias";
            sugerencias: string[];
        };
        EventoFin: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            tipo: "fin";
            /**
             * Format: uuid
             * @description Con qué id continuar la conversación.
             */
            hiloId: string;
        };
        /**
         * @description El stream se corta. Lleva `mensaje` escrito desde el lado del usuario y
         *     `parcial` para que el front sepa si lo que ya llegó se conserva o se
         *     descarta — con SSE, reintentar no es simplemente volver a llamar.
         */
        EventoErrorChat: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            tipo: "error";
            mensaje: string;
            /** @description Si lo recibido hasta acá sigue siendo válido. */
            parcial: boolean;
        };
        /**
         * @description Contra qué se va a medir la decisión. **No es opcional**: sin ventana no
         *     hay cómo saber después si funcionó, y C4 existe para mostrar exactamente
         *     eso.
         */
        VentanaDeMedicion: {
            /**
             * Format: uuid
             * @description Qué métrica se espera mover.
             */
            metricId: string;
            /** Format: date */
            desde: string;
            /** Format: date */
            hasta: string;
            /** @description Qué se espera que pase. Va con su banda, nunca solo. */
            estimado?: number;
            banda?: {
                lo: number;
                hi: number;
                nivel: number;
            };
        };
        /**
         * @description Una recomendación que alguien decidió, con su traza y —cuando la ventana
         *     cierra— su resultado.
         */
        Decision: {
            /** Format: uuid */
            id: string;
            /**
             * @description El nombre corto de la decisión, para encabezar C4 y listarla.
             *
             *     Va en el contrato porque el front NO lo puede derivar: `hipotesis` es
             *     una frase entera y recortarla produciría títulos que cambian de
             *     sentido a mitad. Lo escribe quien propone la recomendación.
             * @example Criteo canibalizaba búsqueda de marca
             */
            titulo: string;
            /**
             * @description `cerrada` es cuando la ventana venció y el resultado ya se calculó.
             * @enum {string}
             */
            estado: "aprobada" | "rechazada" | "cerrada";
            /** @description Qué se creía que estaba pasando. */
            hipotesis: string;
            accionAprobada?: string | null;
            /**
             * @description Quién propuso, quién aprobó y sobre qué base. Es lo que convierte una
             *     decisión en algo auditable en vez de un recuerdo.
             */
            traza: {
                /** @example Equipo growth */
                propuestaPor: string;
                /** @example Ana Ruiz · CEO */
                decididaPor: string;
                /** Format: date-time */
                decididaEn: string;
                /**
                 * @description Con qué método se estimó.
                 * @example Geo-lift 6 semanas · 4 celdas, 2 de control
                 */
                baseEmpirica: string;
                /**
                 * Format: uuid
                 * @description De qué conversación salió.
                 */
                hiloId?: string | null;
            };
            ventanaMedicion: components["schemas"]["VentanaDeMedicion"];
            /**
             * @description Null hasta que la ventana cierre. Decisión del 2026-08-19: **se
             *     calcula automáticamente** cuando vence, no lo carga nadie. Una
             *     decisión que nadie se acordó de medir queda sin cerrar y no se
             *     entera nadie.
             */
            resultado?: components["schemas"]["ResultadoDeDecision"] | null;
        };
        /**
         * @description Observado contra estimado. **La banda es obligatoria**, igual que en
         *     cualquier pronóstico: la regla dura 6 no hace excepción porque el número
         *     ya pasó. Sin banda no se puede decir si el resultado confirma o desmiente.
         */
        ResultadoDeDecision: {
            observado: number;
            estimado: number;
            diferenciaPct?: number;
            banda: {
                lo: number;
                hi: number;
                nivel: number;
            };
            /**
             * @description Si el observado cayó dentro de la banda declarada. `fuera_de_banda`
             *     no significa que la decisión estuvo mal: significa que la estimación
             *     lo estuvo, y esa distinción es la que C4 muestra.
             * @enum {string}
             */
            veredicto: "dentro_de_banda" | "fuera_de_banda";
            /** Format: date-time */
            medidoEn: string;
            /** @description Qué se aprende para la próxima. */
            queCambia?: {
                enLaEstimacion?: string;
                enLaDecision?: string;
            };
        };
        /**
         * @description Los once estados de la máquina del framework. Las tres ramas terminales
         *     —`descartado`, `rechazado`, `sin_respuesta`— **no son fallas del
         *     proceso**: son valor probatorio, y por eso se muestran.
         * @enum {string}
         */
        EstadoDeAccionable: "propuesto" | "priorizado" | "descartado" | "en_ejecucion" | "compartido" | "aceptado" | "rechazado" | "sin_respuesta" | "ejecutado" | "medido" | "cerrado";
        /**
         * @description Un accionable del framework · `DB_BT_UA.BT_UA_DECISION_LOG.ACCIONABLE`.
         *     Espejo parcial: solo lo que la consola del cliente necesita leer.
         *
         *     **No incluye `sql_congelado` ni `id_insight_origen`**: son vocabulario de
         *     infraestructura y §7.3 los prohíbe en pantalla. La trazabilidad existe y
         *     no se muestra.
         */
        Accionable: {
            id: string;
            /** @description La acción concreta. Específica, no genérica. */
            accion: string;
            /**
             * @description La hipótesis, fijada **antes** de ejecutar. Se muestra junto al
             *     resultado, nunca el resultado solo — es el pre-registro.
             */
            efectoEsperado?: string;
            /** @description El `metricId` con que se medirá. Nunca un SQL (L13). */
            metricaObjetivo?: string;
            ventanaDias: number;
            /**
             * @description **Es la procedencia de un accionable.** No tiene capa Medallion que
             *     declarar, así que §1.3 se cumple con esto: A controlado, B
             *     cuasi-experimental, C observacional. Un nivel C sugiere; no prueba.
             * @enum {string}
             */
            nivelEvidencia: "A" | "B" | "C";
            estado: components["schemas"]["EstadoDeAccionable"];
            resultadoMedido?: number | null;
            /**
             * @description `inconcluso` cubre datos insuficientes, ventana contaminada **o
             *     cambio en la definición semántica durante el período**.
             * @enum {string|null}
             */
            veredicto?: "validado" | "refutado" | "inconcluso" | null;
            /**
             * @description Solo ruta B. **`sin_respuesta` es el seguro de atribución**: si el
             *     cliente no ejecuta y los números caen, queda documentado que se le
             *     marcó. No lo pisa una aprobación de super-admin.
             * @enum {string|null}
             */
            respuestaCliente?: "aceptado" | "rechazado" | "sin_respuesta" | null;
            razonRespuesta?: string | null;
            /** Format: date-time */
            fechaCreacion?: string;
            /** Format: date-time */
            fechaCierre?: string | null;
        };
        SolicitudDeAcceso: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            metricId: string;
            /** @enum {string} */
            estado: "pendiente" | "aprobada" | "rechazada";
            /** Format: date-time */
            creadaEn: string;
            /** Format: date-time */
            resueltaEn?: string | null;
            resueltaPor?: string | null;
            motivo?: string | null;
            /**
             * @description Si se rechazó, por qué. Un rechazo sin razón deja al que pidió sin
             *     saber si insistir o no — la misma gramática de §8.
             */
            razonDeRechazo?: string | null;
        };
        /** @description Una fila del riel de C3. */
        HiloResumen: {
            /** Format: uuid */
            id: string;
            /**
             * @description La primera pregunta del hilo. El riel la muestra tal cual —«Por qué
             *     subió el ROAS si la inversión está plana»—, así que no se resume ni
             *     se recorta acá: el front decide cuánto entra en 220px.
             */
            titulo: string;
            /** Format: date-time */
            creadoEn: string;
            /**
             * Format: date-time
             * @description Por acá se ordena el riel.
             */
            actualizadoEn: string;
            /**
             * @description El hilo quedó asociado a una decisión de C4. El riel lo marca con un
             *     badge y **no se puede borrar**: es la traza de por qué se decidió.
             */
            esDecision: boolean;
            /** Format: uuid */
            decisionId?: string | null;
        };
        Hilo: components["schemas"]["HiloResumen"] & {
            mensajes: components["schemas"]["MensajeDeChat"][];
        };
        MensajeDeChat: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            autor: "usuario" | "synapse";
            /** Format: date-time */
            creadoEn: string;
            /**
             * @description La respuesta completa en prosa. En el stream llega por fragmentos;
             *     acá ya está armada.
             */
            texto: string;
            /**
             * @description Las cifras que acompañaron la respuesta, **como llegaron**. Cada una
             *     trae su procedencia, así que un hilo viejo se lee sin ambigüedad: el
             *     badge dice «HACE 45 D».
             */
            datos?: components["schemas"]["DatoDeRespuesta"][];
            sugerencias?: string[];
            /**
             * @description La consulta que produjo esta respuesta, guardada con ella. Un hilo
             *     viejo sin su SQL pierde justamente lo que lo hacía auditable.
             */
            sql?: string | null;
            limiteDeclarado?: string | null;
        };
        /**
         * @description Los rótulos y las cifras de apoyo que el panel pinta alrededor del
         *     valor. **Viajan con el dato y no con el layout**, porque dependen del
         *     período: el medidor marca 61% este mes y otra cosa el siguiente.
         *
         *     Decisión del 2026-08-19 (humano): el backend devuelve los rótulos ya
         *     redactados. Razón: §1.3 ya obliga a que la BASE, la procedencia y la
         *     dirección semántica vengan del backend, y estos rótulos son de la misma
         *     familia — describen el dato, no la interfaz. Partirlos en dos orígenes
         *     es lo que hace que una pantalla diga una cosa y el dato otra.
         *
         *     Si un rótulo no existe todavía, se genera para que coincida.
         */
        Presentacion: {
            /**
             * @description Qué dice el rótulo sobre la cifra grande. Lleva la unidad, y por eso
             *     la cifra no la lleva pegada: a 44px «USD 4.28M» no entra en un panel
             *     de colSpan 3 y «4.28M» con «USD · TOTAL» arriba sí.
             * @example USD · TOTAL
             */
            label?: string;
            /** @description Avance contra un objetivo o peso sobre un total. */
            medidor?: {
                /** @example PESO DE PERFORMANCE */
                label: string;
                /** @example 61 */
                porcentaje: number;
                /**
                 * @description Qué es el 100%.
                 * @example USD 2.61M DE USD 4.28M
                 */
                nota?: string;
            };
            /**
             * @description Comparaciones contra otro período. **El signo comunica la
             *     dirección; el color no** — regla dura 3, así que no viene ninguna
             *     indicación cromática.
             */
            comparativo?: {
                /** @example VS MES ANTERIOR */
                label: string;
                /** @example 6.4 */
                delta: number;
                /** @example % */
                unidad?: string;
            }[];
            /** @description Lectura al pie del panel, cuando la métrica la necesita. */
            nota?: string;
        };
        Valor: components["schemas"]["ValorEscalar"] | components["schemas"]["ValorEscalarConIntervalo"] | components["schemas"]["ValorSerieTemporal"] | components["schemas"]["ValorSerieConBanda"] | components["schemas"]["ValorSeriesMultiples"] | components["schemas"]["ValorCategorica"] | components["schemas"]["ValorRanking"] | components["schemas"]["ValorComposicion"] | components["schemas"]["ValorDistribucion"] | components["schemas"]["ValorTabular"] | components["schemas"]["ValorProsa"];
        Punto: {
            /**
             * @description La etiqueta del eje, ya lista para pintar.
             * @example jul
             * @example 2026-07-15
             */
            t: string;
            v: number;
        };
        ValorEscalar: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            forma: "escalar";
            v: number;
        };
        /**
         * @description **Prohibida la estimación puntual sin intervalo** (regla dura 6). Por
         *     eso `lo`, `hi` y `nivel` son obligatorios y no opcionales: un pronóstico
         *     sin banda no se puede construir.
         */
        ValorEscalarConIntervalo: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            forma: "escalarConIntervalo";
            v: number;
            lo: number;
            hi: number;
            /**
             * @description Nivel de confianza, entre 0 y 1.
             * @example 0.8
             */
            nivel: number;
        };
        ValorSerieTemporal: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            forma: "serieTemporal";
            puntos: components["schemas"]["Punto"][];
        };
        /**
         * @description Cada punto lleva su banda. **Un `serieConBanda` sin banda no se puede
         *     construir**, que es la regla dura 6 verificada por el tipo en vez de por
         *     el lint.
         */
        ValorSerieConBanda: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            forma: "serieConBanda";
            nivel: number;
            puntos: {
                t: string;
                v: number;
                lo: number;
                hi: number;
            }[];
        };
        ValorSeriesMultiples: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            forma: "seriesMultiples";
            series: {
                etiqueta: string;
                puntos: components["schemas"]["Punto"][];
            }[];
        };
        ValorCategorica: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            forma: "categorica";
            items: {
                etiqueta: string;
                v: number;
            }[];
        };
        ValorRanking: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            forma: "ranking";
            items: {
                etiqueta: string;
                v: number;
                posicion: number;
            }[];
        };
        ValorComposicion: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            forma: "composicion";
            partes: {
                etiqueta: string;
                v: number;
                /**
                 * @description Lo calcula el backend y no el front: la suma tiene que dar 100
                 *     y redondear en el cliente produce columnas que suman 99.9.
                 */
                porcentaje: number;
            }[];
        };
        /**
         * @description Cortes de una distribución. Entró al contrato el 2026-08-19 porque
         *     `depth_by_dimension` la usa y el compilador no dejó construir su cuerpo
         *     sin ella — que es el orden correcto: primero la pantalla prueba que hace
         *     falta, después el contrato la declara.
         */
        ValorDistribucion: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            forma: "distribucion";
            cortes: {
                etiqueta: string;
                v: number;
            }[];
        };
        ValorTabular: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            forma: "tabular";
            columnas: {
                clave: string;
                titulo: string;
                numerica: boolean;
                /**
                 * @description Cuántos decimales muestra la COLUMNA ENTERA. Sin esto, una
                 *     columna de ROAS sale «4.2 · 4.5 · 3.5 · 3»: la última pierde
                 *     su decimal y la coma deja de alinearse. Cada celda está bien y
                 *     la columna se lee mal.
                 */
                decimales?: number | null;
                unidad?: string | null;
            }[];
            filas: {
                [key: string]: string | number | null;
            }[];
        };
        ValorProsa: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            forma: "prosa";
            titular: string;
            /**
             * @description Tres campos por pilar y no una cadena. §2.3 los declara como
             *     `string[]`, y con eso el cuerpo tendría que **parsear texto** para
             *     encontrar la cifra — justo lo que el contrato existe para evitar.
             */
            pilares: {
                /**
                 * @description Llave opaca del ítem, **sin semántica de negocio** · `PS-17`.
                 *     Existe para que `acciones.porRef` pueda apuntarle sin depender
                 *     del índice, que el `tope` del panel invalida. Identificar filas
                 *     es genérico —una tabla tiene claves—, así que esto sigue siendo
                 *     geometría y no ensucia la forma.
                 */
                ref?: string;
                /** @example VENTAS */
                label: string;
                /**
                 * @description Ya formateado. Es el único lugar donde eso es correcto: el
                 *     pilar cita una cifra que ya aparece en el titular, y
                 *     reformatearla podría hacer que digan distinto.
                 * @example USD 4.28M
                 */
                valor: string;
                /** @example +6.4% VS JUN */
                nota?: string;
            }[];
        };
    };
    responses: {
        /** @description Token ausente, vencido o de otra audiencia */
        NoAutorizado: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["RespuestaError"];
            };
        };
        /** @description No existe, o existe y no es tuyo — no se distinguen */
        NoExiste: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["RespuestaError"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    obtenerContexto: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Contexto del usuario */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["Contexto"];
                    };
                };
            };
            401: components["responses"]["NoAutorizado"];
        };
    };
    obtenerCatalogo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Catálogo de métricas */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: {
                            metrics: components["schemas"]["Metrica"][];
                        };
                    };
                };
            };
            401: components["responses"]["NoAutorizado"];
        };
    };
    obtenerBloques: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tipos de panel con sus formas y rangos */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: {
                            blocks: components["schemas"]["Bloque"][];
                        };
                    };
                };
            };
        };
    };
    obtenerPestana: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tabId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pestaña con sus paneles */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["PestanaConPaneles"];
                    };
                };
            };
            404: components["responses"]["NoExiste"];
        };
    };
    preguntarASynapse: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    pregunta: string;
                    /**
                     * Format: uuid
                     * @description Desde qué pestaña se pregunta. Da contexto al agente y es de
                     *     donde salen las `chatSugerencias`.
                     */
                    tabId?: string;
                    /**
                     * Format: uuid
                     * @description Para continuar una conversación.
                     */
                    hiloId?: string;
                };
            };
        };
        responses: {
            /**
             * @description Flujo de eventos. Cada uno es una línea `data:` con un objeto
             *     `EventoDeChat` serializado.
             */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["EventoDeChat"];
                };
            };
            401: components["responses"]["NoAutorizado"];
        };
    };
    listarHilos: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Hilos del usuario */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: {
                            hilos: components["schemas"]["HiloResumen"][];
                        };
                    };
                };
            };
        };
    };
    obtenerHilo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                hiloId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description La conversación */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["Hilo"];
                    };
                };
            };
            404: components["responses"]["NoExiste"];
        };
    };
    borrarHilo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                hiloId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Borrado */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NoExiste"];
            /** @description Es la traza de una decisión y no se puede borrar */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaError"];
                };
            };
        };
    };
    listarDecisiones: {
        parameters: {
            query?: {
                periodo?: components["schemas"]["PeriodoId"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Decisiones del tenant en ese período */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: {
                            decisiones: components["schemas"]["Decision"][];
                        };
                    };
                };
            };
        };
    };
    decidirRecomendacion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    recomendacionId: string;
                    /** @enum {string} */
                    veredicto: "aprobada" | "rechazada";
                    ventanaMedicion: components["schemas"]["VentanaDeMedicion"];
                    /**
                     * Format: uuid
                     * @description De qué conversación salió, si salió de una. Es lo que hace
                     *     que ese hilo no se pueda borrar después.
                     */
                    hiloId?: string;
                    nota?: string;
                };
            };
        };
        responses: {
            /** @description Decisión registrada */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["Decision"];
                    };
                };
            };
            /** @description El rol no puede aprobar */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaError"];
                };
            };
        };
    };
    obtenerDecision: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                decisionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description La decisión con su traza y su resultado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["Decision"];
                    };
                };
            };
            404: components["responses"]["NoExiste"];
        };
    };
    promoverAccionable: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Específica, no genérica. */
                    accion: string;
                    /**
                     * @description La hipótesis. **Obligatoria por la regla de oro del
                     *     framework**: «sin owner y sin efecto esperado, no es un
                     *     accionable: es un comentario».
                     */
                    efectoEsperado: string;
                    /** @description Un `metricId` del catálogo. Jamás un SQL (L13). */
                    metricaObjetivo: string;
                    /** @description Cuánto dura el experimento antes de medir. */
                    ventanaDias: number;
                    /** @enum {string} */
                    nivelEvidencia: "A" | "B" | "C";
                    /**
                     * @description Quién ejecuta. **La etiqueta que ve el usuario no dice
                     *     «Synapse ejecuta»**: la plataforma no ejecuta —§1.3.16—, lo
                     *     hace el equipo interno o de marketing (humano, 2026-08-21).
                     *     El valor del contrato se queda en el dato; la pantalla nombra
                     *     al equipo.
                     * @default recomendacion
                     * @enum {string}
                     */
                    ruta?: "equipo_interno" | "recomendacion";
                    /** @description La consulta congelada, tal como la emitió el chat. */
                    snapshot: {
                        sql: string;
                        fuentesConsultadas: string[];
                        versionModeloSemantico?: string | null;
                    };
                };
            };
        };
        responses: {
            /** @description Promovido, en estado `propuesto` */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["Accionable"];
                    };
                };
            };
            /** @description El usuario no tiene la capacidad `registrar_accionable`. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /**
             * @description Falta la hipótesis, la métrica objetivo no está en el catálogo, o el
             *     snapshot viene sin consulta.
             */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    responderAccionable: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description El `id_accionable` del `DECISION_LOG`. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    respuesta: "aceptado" | "rechazado";
                    /**
                     * @description **Obligatoria al rechazar.** Un rechazo sin razón no sirve
                     *     para medir después por qué no se ejecutó, que es la mitad del
                     *     valor probatorio de la bitácora (§4.3 de `accionables.md`).
                     */
                    razon?: string;
                };
            };
        };
        responses: {
            /** @description La respuesta quedó registrada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["Accionable"];
                    };
                };
            };
            /**
             * @description Ya tiene respuesta, o su estado no la admite. **No se sobreescribe**:
             *     una decisión registrada no se renegocia (§7.1, segundo eje).
             */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Rechazo sin razón. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listarSolicitudes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Solicitudes del usuario */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: {
                            solicitudes: components["schemas"]["SolicitudDeAcceso"][];
                        };
                    };
                };
            };
        };
    };
    solicitarAcceso: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    metricId: string;
                    motivo?: string;
                };
            };
        };
        responses: {
            /** @description Solicitud creada */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["SolicitudDeAcceso"];
                    };
                };
            };
            /** @description Ya hay una solicitud pendiente para esa métrica */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaError"];
                };
            };
        };
    };
    guardarPreferencias: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    tema?: "dark" | "light";
                };
            };
        };
        responses: {
            /** @description Guardado */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    obtenerPayloads: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    panelIds: string[];
                    periodo: components["schemas"]["PeriodoId"];
                };
            };
        };
        responses: {
            /** @description Un payload por panel pedido */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: {
                            /** @description Clave = `panelId`. */
                            payloads: {
                                [key: string]: components["schemas"]["Payload"];
                            };
                        };
                    };
                };
            };
        };
    };
}
